package mx.com.ebs.inter.data.dao.facbanco;

import java.util.List;
import mx.com.ebs.inter.data.model.facbanco.MCfd;
import mx.com.ebs.inter.data.model.facbanco.MCfdExample;
import org.apache.ibatis.annotations.Param;

public interface MCfdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    int countByExample(MCfdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    int deleteByExample(MCfdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    int insert(MCfd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    int insertSelective(MCfd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    List<MCfd> selectByExample(MCfdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    MCfd selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    int updateByExampleSelective(@Param("record") MCfd record, @Param("example") MCfdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    int updateByExample(@Param("record") MCfd record, @Param("example") MCfdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    int updateByPrimaryKeySelective(MCfd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_INTERACCIONES.M_CFD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    int updateByPrimaryKey(MCfd record);
}