package mx.com.ebs.inter.data.model.proc;

public class AgtFelEnvioKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.ANIO_MES_DIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Integer ANIO_MES_DIA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.ANO_MES
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Integer ANO_MES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.ID_AGENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Integer ID_AGENTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.ID_VERSION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Short ID_VERSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.ANIO_MES_DIA
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.ANIO_MES_DIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Integer getANIO_MES_DIA() {
        return ANIO_MES_DIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.ANIO_MES_DIA
     *
     * @param ANIO_MES_DIA the value for AGENTES.AGT_FEL_ENVIO.ANIO_MES_DIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setANIO_MES_DIA(Integer ANIO_MES_DIA) {
        this.ANIO_MES_DIA = ANIO_MES_DIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.ANO_MES
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.ANO_MES
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Integer getANO_MES() {
        return ANO_MES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.ANO_MES
     *
     * @param ANO_MES the value for AGENTES.AGT_FEL_ENVIO.ANO_MES
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setANO_MES(Integer ANO_MES) {
        this.ANO_MES = ANO_MES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.ID_AGENTE
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.ID_AGENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Integer getID_AGENTE() {
        return ID_AGENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.ID_AGENTE
     *
     * @param ID_AGENTE the value for AGENTES.AGT_FEL_ENVIO.ID_AGENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setID_AGENTE(Integer ID_AGENTE) {
        this.ID_AGENTE = ID_AGENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.ID_VERSION
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.ID_VERSION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Short getID_VERSION() {
        return ID_VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.ID_VERSION
     *
     * @param ID_VERSION the value for AGENTES.AGT_FEL_ENVIO.ID_VERSION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setID_VERSION(Short ID_VERSION) {
        this.ID_VERSION = ID_VERSION;
    }
}