package mx.com.ebs.inter.data.model.proc;

import java.math.BigDecimal;
import java.util.Date;

public class AgtFelEnvio extends AgtFelEnvioKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.ID_SUPERVISORIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Short ID_SUPERVISORIA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.ID_EMPRESA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Integer ID_EMPRESA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.RFC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String RFC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_PAGO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal TOT_IMP_PAGO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_ISR
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal TOT_IMP_ISR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_RET
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal TOT_IMP_IVA_RET;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_PAG
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal TOT_IMP_IVA_PAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.IMP_DEDUCCION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal IMP_DEDUCCION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.IMP_TOTAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal IMP_TOTAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.ID_USUARIO_CREAC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String ID_USUARIO_CREAC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.B_FACT_ELECT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String b_FACT_ELECT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.CVE_ORIGEN_APLIC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String CVE_ORIGEN_APLIC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.FH_CARGA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Date FH_CARGA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.FH_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Date FH_ENVIO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.FH_RESPUESTA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Date FH_RESPUESTA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.COD_RESPUESTA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Long COD_RESPUESTA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.COD_TRANSACCION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Long COD_TRANSACCION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.COD_CONFIRMACION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String COD_CONFIRMACION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.B_CORRECTO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String b_CORRECTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.F_INI_REG
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Date f_INI_REG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.F_TER_REG
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Date f_TER_REG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.B_ULT_REG_DIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String b_ULT_REG_DIA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.AGT_FEL_ENVIO.IMP_SUBTOTAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal IMP_SUBTOTAL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.ID_SUPERVISORIA
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.ID_SUPERVISORIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Short getID_SUPERVISORIA() {
        return ID_SUPERVISORIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.ID_SUPERVISORIA
     *
     * @param ID_SUPERVISORIA the value for AGENTES.AGT_FEL_ENVIO.ID_SUPERVISORIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setID_SUPERVISORIA(Short ID_SUPERVISORIA) {
        this.ID_SUPERVISORIA = ID_SUPERVISORIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.ID_EMPRESA
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.ID_EMPRESA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Integer getID_EMPRESA() {
        return ID_EMPRESA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.ID_EMPRESA
     *
     * @param ID_EMPRESA the value for AGENTES.AGT_FEL_ENVIO.ID_EMPRESA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setID_EMPRESA(Integer ID_EMPRESA) {
        this.ID_EMPRESA = ID_EMPRESA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.RFC
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.RFC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getRFC() {
        return RFC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.RFC
     *
     * @param RFC the value for AGENTES.AGT_FEL_ENVIO.RFC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setRFC(String RFC) {
        this.RFC = RFC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_PAGO
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.TOT_IMP_PAGO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getTOT_IMP_PAGO() {
        return TOT_IMP_PAGO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_PAGO
     *
     * @param TOT_IMP_PAGO the value for AGENTES.AGT_FEL_ENVIO.TOT_IMP_PAGO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setTOT_IMP_PAGO(BigDecimal TOT_IMP_PAGO) {
        this.TOT_IMP_PAGO = TOT_IMP_PAGO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_ISR
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.TOT_IMP_ISR
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getTOT_IMP_ISR() {
        return TOT_IMP_ISR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_ISR
     *
     * @param TOT_IMP_ISR the value for AGENTES.AGT_FEL_ENVIO.TOT_IMP_ISR
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setTOT_IMP_ISR(BigDecimal TOT_IMP_ISR) {
        this.TOT_IMP_ISR = TOT_IMP_ISR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_RET
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_RET
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getTOT_IMP_IVA_RET() {
        return TOT_IMP_IVA_RET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_RET
     *
     * @param TOT_IMP_IVA_RET the value for AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_RET
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setTOT_IMP_IVA_RET(BigDecimal TOT_IMP_IVA_RET) {
        this.TOT_IMP_IVA_RET = TOT_IMP_IVA_RET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_PAG
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_PAG
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getTOT_IMP_IVA_PAG() {
        return TOT_IMP_IVA_PAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_PAG
     *
     * @param TOT_IMP_IVA_PAG the value for AGENTES.AGT_FEL_ENVIO.TOT_IMP_IVA_PAG
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setTOT_IMP_IVA_PAG(BigDecimal TOT_IMP_IVA_PAG) {
        this.TOT_IMP_IVA_PAG = TOT_IMP_IVA_PAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.IMP_DEDUCCION
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.IMP_DEDUCCION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getIMP_DEDUCCION() {
        return IMP_DEDUCCION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.IMP_DEDUCCION
     *
     * @param IMP_DEDUCCION the value for AGENTES.AGT_FEL_ENVIO.IMP_DEDUCCION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setIMP_DEDUCCION(BigDecimal IMP_DEDUCCION) {
        this.IMP_DEDUCCION = IMP_DEDUCCION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.IMP_TOTAL
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.IMP_TOTAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getIMP_TOTAL() {
        return IMP_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.IMP_TOTAL
     *
     * @param IMP_TOTAL the value for AGENTES.AGT_FEL_ENVIO.IMP_TOTAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setIMP_TOTAL(BigDecimal IMP_TOTAL) {
        this.IMP_TOTAL = IMP_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.ID_USUARIO_CREAC
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.ID_USUARIO_CREAC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getID_USUARIO_CREAC() {
        return ID_USUARIO_CREAC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.ID_USUARIO_CREAC
     *
     * @param ID_USUARIO_CREAC the value for AGENTES.AGT_FEL_ENVIO.ID_USUARIO_CREAC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setID_USUARIO_CREAC(String ID_USUARIO_CREAC) {
        this.ID_USUARIO_CREAC = ID_USUARIO_CREAC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.B_FACT_ELECT
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.B_FACT_ELECT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getB_FACT_ELECT() {
        return b_FACT_ELECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.B_FACT_ELECT
     *
     * @param b_FACT_ELECT the value for AGENTES.AGT_FEL_ENVIO.B_FACT_ELECT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setB_FACT_ELECT(String b_FACT_ELECT) {
        this.b_FACT_ELECT = b_FACT_ELECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.CVE_ORIGEN_APLIC
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.CVE_ORIGEN_APLIC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getCVE_ORIGEN_APLIC() {
        return CVE_ORIGEN_APLIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.CVE_ORIGEN_APLIC
     *
     * @param CVE_ORIGEN_APLIC the value for AGENTES.AGT_FEL_ENVIO.CVE_ORIGEN_APLIC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setCVE_ORIGEN_APLIC(String CVE_ORIGEN_APLIC) {
        this.CVE_ORIGEN_APLIC = CVE_ORIGEN_APLIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.FH_CARGA
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.FH_CARGA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Date getFH_CARGA() {
        return FH_CARGA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.FH_CARGA
     *
     * @param FH_CARGA the value for AGENTES.AGT_FEL_ENVIO.FH_CARGA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setFH_CARGA(Date FH_CARGA) {
        this.FH_CARGA = FH_CARGA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.FH_ENVIO
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.FH_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Date getFH_ENVIO() {
        return FH_ENVIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.FH_ENVIO
     *
     * @param FH_ENVIO the value for AGENTES.AGT_FEL_ENVIO.FH_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setFH_ENVIO(Date FH_ENVIO) {
        this.FH_ENVIO = FH_ENVIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.FH_RESPUESTA
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.FH_RESPUESTA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Date getFH_RESPUESTA() {
        return FH_RESPUESTA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.FH_RESPUESTA
     *
     * @param FH_RESPUESTA the value for AGENTES.AGT_FEL_ENVIO.FH_RESPUESTA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setFH_RESPUESTA(Date FH_RESPUESTA) {
        this.FH_RESPUESTA = FH_RESPUESTA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.COD_RESPUESTA
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.COD_RESPUESTA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Long getCOD_RESPUESTA() {
        return COD_RESPUESTA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.COD_RESPUESTA
     *
     * @param COD_RESPUESTA the value for AGENTES.AGT_FEL_ENVIO.COD_RESPUESTA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setCOD_RESPUESTA(Long COD_RESPUESTA) {
        this.COD_RESPUESTA = COD_RESPUESTA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.COD_TRANSACCION
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.COD_TRANSACCION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Long getCOD_TRANSACCION() {
        return COD_TRANSACCION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.COD_TRANSACCION
     *
     * @param COD_TRANSACCION the value for AGENTES.AGT_FEL_ENVIO.COD_TRANSACCION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setCOD_TRANSACCION(Long COD_TRANSACCION) {
        this.COD_TRANSACCION = COD_TRANSACCION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.COD_CONFIRMACION
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.COD_CONFIRMACION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getCOD_CONFIRMACION() {
        return COD_CONFIRMACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.COD_CONFIRMACION
     *
     * @param COD_CONFIRMACION the value for AGENTES.AGT_FEL_ENVIO.COD_CONFIRMACION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setCOD_CONFIRMACION(String COD_CONFIRMACION) {
        this.COD_CONFIRMACION = COD_CONFIRMACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.B_CORRECTO
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.B_CORRECTO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getB_CORRECTO() {
        return b_CORRECTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.B_CORRECTO
     *
     * @param b_CORRECTO the value for AGENTES.AGT_FEL_ENVIO.B_CORRECTO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setB_CORRECTO(String b_CORRECTO) {
        this.b_CORRECTO = b_CORRECTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.F_INI_REG
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.F_INI_REG
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Date getF_INI_REG() {
        return f_INI_REG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.F_INI_REG
     *
     * @param f_INI_REG the value for AGENTES.AGT_FEL_ENVIO.F_INI_REG
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setF_INI_REG(Date f_INI_REG) {
        this.f_INI_REG = f_INI_REG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.F_TER_REG
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.F_TER_REG
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Date getF_TER_REG() {
        return f_TER_REG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.F_TER_REG
     *
     * @param f_TER_REG the value for AGENTES.AGT_FEL_ENVIO.F_TER_REG
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setF_TER_REG(Date f_TER_REG) {
        this.f_TER_REG = f_TER_REG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.B_ULT_REG_DIA
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.B_ULT_REG_DIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getB_ULT_REG_DIA() {
        return b_ULT_REG_DIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.B_ULT_REG_DIA
     *
     * @param b_ULT_REG_DIA the value for AGENTES.AGT_FEL_ENVIO.B_ULT_REG_DIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setB_ULT_REG_DIA(String b_ULT_REG_DIA) {
        this.b_ULT_REG_DIA = b_ULT_REG_DIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.AGT_FEL_ENVIO.IMP_SUBTOTAL
     *
     * @return the value of AGENTES.AGT_FEL_ENVIO.IMP_SUBTOTAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getIMP_SUBTOTAL() {
        return IMP_SUBTOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.AGT_FEL_ENVIO.IMP_SUBTOTAL
     *
     * @param IMP_SUBTOTAL the value for AGENTES.AGT_FEL_ENVIO.IMP_SUBTOTAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setIMP_SUBTOTAL(BigDecimal IMP_SUBTOTAL) {
        this.IMP_SUBTOTAL = IMP_SUBTOTAL;
    }
}