package mx.com.ebs.inter.data.model.proc;

import java.math.BigDecimal;
import java.util.Date;

public class RecFelogger {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.FECHA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Date FECHA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.CLASE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String CLASE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.METODO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String METODO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.NIVEL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String NIVEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.ID
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.MENSAJE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String MENSAJE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.AGENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String AGENTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.ANO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String ANO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.MES
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String MES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTES.REC_FELOGGER.SIT_COMPROBANTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal SIT_COMPROBANTE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.FECHA
     *
     * @return the value of AGENTES.REC_FELOGGER.FECHA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Date getFECHA() {
        return FECHA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.FECHA
     *
     * @param FECHA the value for AGENTES.REC_FELOGGER.FECHA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setFECHA(Date FECHA) {
        this.FECHA = FECHA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.CLASE
     *
     * @return the value of AGENTES.REC_FELOGGER.CLASE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getCLASE() {
        return CLASE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.CLASE
     *
     * @param CLASE the value for AGENTES.REC_FELOGGER.CLASE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setCLASE(String CLASE) {
        this.CLASE = CLASE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.METODO
     *
     * @return the value of AGENTES.REC_FELOGGER.METODO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getMETODO() {
        return METODO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.METODO
     *
     * @param METODO the value for AGENTES.REC_FELOGGER.METODO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setMETODO(String METODO) {
        this.METODO = METODO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.NIVEL
     *
     * @return the value of AGENTES.REC_FELOGGER.NIVEL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getNIVEL() {
        return NIVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.NIVEL
     *
     * @param NIVEL the value for AGENTES.REC_FELOGGER.NIVEL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setNIVEL(String NIVEL) {
        this.NIVEL = NIVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.ID
     *
     * @return the value of AGENTES.REC_FELOGGER.ID
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.ID
     *
     * @param ID the value for AGENTES.REC_FELOGGER.ID
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setID(String ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.MENSAJE
     *
     * @return the value of AGENTES.REC_FELOGGER.MENSAJE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getMENSAJE() {
        return MENSAJE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.MENSAJE
     *
     * @param MENSAJE the value for AGENTES.REC_FELOGGER.MENSAJE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setMENSAJE(String MENSAJE) {
        this.MENSAJE = MENSAJE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.AGENTE
     *
     * @return the value of AGENTES.REC_FELOGGER.AGENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getAGENTE() {
        return AGENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.AGENTE
     *
     * @param AGENTE the value for AGENTES.REC_FELOGGER.AGENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setAGENTE(String AGENTE) {
        this.AGENTE = AGENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.ANO
     *
     * @return the value of AGENTES.REC_FELOGGER.ANO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getANO() {
        return ANO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.ANO
     *
     * @param ANO the value for AGENTES.REC_FELOGGER.ANO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setANO(String ANO) {
        this.ANO = ANO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.MES
     *
     * @return the value of AGENTES.REC_FELOGGER.MES
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getMES() {
        return MES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.MES
     *
     * @param MES the value for AGENTES.REC_FELOGGER.MES
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setMES(String MES) {
        this.MES = MES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTES.REC_FELOGGER.SIT_COMPROBANTE
     *
     * @return the value of AGENTES.REC_FELOGGER.SIT_COMPROBANTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getSIT_COMPROBANTE() {
        return SIT_COMPROBANTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTES.REC_FELOGGER.SIT_COMPROBANTE
     *
     * @param SIT_COMPROBANTE the value for AGENTES.REC_FELOGGER.SIT_COMPROBANTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setSIT_COMPROBANTE(BigDecimal SIT_COMPROBANTE) {
        this.SIT_COMPROBANTE = SIT_COMPROBANTE;
    }
}