package mx.com.ebs.inter.data.model.proc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecInvoiceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public RecInvoiceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDIAIsNull() {
            addCriterion("DIA is null");
            return (Criteria) this;
        }

        public Criteria andDIAIsNotNull() {
            addCriterion("DIA is not null");
            return (Criteria) this;
        }

        public Criteria andDIAEqualTo(String value) {
            addCriterion("DIA =", value, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIANotEqualTo(String value) {
            addCriterion("DIA <>", value, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIAGreaterThan(String value) {
            addCriterion("DIA >", value, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIAGreaterThanOrEqualTo(String value) {
            addCriterion("DIA >=", value, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIALessThan(String value) {
            addCriterion("DIA <", value, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIALessThanOrEqualTo(String value) {
            addCriterion("DIA <=", value, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIALike(String value) {
            addCriterion("DIA like", value, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIANotLike(String value) {
            addCriterion("DIA not like", value, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIAIn(List<String> values) {
            addCriterion("DIA in", values, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIANotIn(List<String> values) {
            addCriterion("DIA not in", values, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIABetween(String value1, String value2) {
            addCriterion("DIA between", value1, value2, "DIA");
            return (Criteria) this;
        }

        public Criteria andDIANotBetween(String value1, String value2) {
            addCriterion("DIA not between", value1, value2, "DIA");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONIsNull() {
            addCriterion("NO_APROBACION is null");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONIsNotNull() {
            addCriterion("NO_APROBACION is not null");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONEqualTo(BigDecimal value) {
            addCriterion("NO_APROBACION =", value, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONNotEqualTo(BigDecimal value) {
            addCriterion("NO_APROBACION <>", value, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONGreaterThan(BigDecimal value) {
            addCriterion("NO_APROBACION >", value, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NO_APROBACION >=", value, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONLessThan(BigDecimal value) {
            addCriterion("NO_APROBACION <", value, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NO_APROBACION <=", value, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONIn(List<BigDecimal> values) {
            addCriterion("NO_APROBACION in", values, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONNotIn(List<BigDecimal> values) {
            addCriterion("NO_APROBACION not in", values, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NO_APROBACION between", value1, value2, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_APROBACIONNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NO_APROBACION not between", value1, value2, "NO_APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONIsNull() {
            addCriterion("APROBACION is null");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONIsNotNull() {
            addCriterion("APROBACION is not null");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONEqualTo(BigDecimal value) {
            addCriterion("APROBACION =", value, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONNotEqualTo(BigDecimal value) {
            addCriterion("APROBACION <>", value, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONGreaterThan(BigDecimal value) {
            addCriterion("APROBACION >", value, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("APROBACION >=", value, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONLessThan(BigDecimal value) {
            addCriterion("APROBACION <", value, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONLessThanOrEqualTo(BigDecimal value) {
            addCriterion("APROBACION <=", value, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONIn(List<BigDecimal> values) {
            addCriterion("APROBACION in", values, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONNotIn(List<BigDecimal> values) {
            addCriterion("APROBACION not in", values, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APROBACION between", value1, value2, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andAPROBACIONNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APROBACION not between", value1, value2, "APROBACION");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOIsNull() {
            addCriterion("NO_CERTIFICADO is null");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOIsNotNull() {
            addCriterion("NO_CERTIFICADO is not null");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOEqualTo(String value) {
            addCriterion("NO_CERTIFICADO =", value, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADONotEqualTo(String value) {
            addCriterion("NO_CERTIFICADO <>", value, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOGreaterThan(String value) {
            addCriterion("NO_CERTIFICADO >", value, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOGreaterThanOrEqualTo(String value) {
            addCriterion("NO_CERTIFICADO >=", value, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOLessThan(String value) {
            addCriterion("NO_CERTIFICADO <", value, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOLessThanOrEqualTo(String value) {
            addCriterion("NO_CERTIFICADO <=", value, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOLike(String value) {
            addCriterion("NO_CERTIFICADO like", value, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADONotLike(String value) {
            addCriterion("NO_CERTIFICADO not like", value, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOIn(List<String> values) {
            addCriterion("NO_CERTIFICADO in", values, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADONotIn(List<String> values) {
            addCriterion("NO_CERTIFICADO not in", values, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADOBetween(String value1, String value2) {
            addCriterion("NO_CERTIFICADO between", value1, value2, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andNO_CERTIFICADONotBetween(String value1, String value2) {
            addCriterion("NO_CERTIFICADO not between", value1, value2, "NO_CERTIFICADO");
            return (Criteria) this;
        }

        public Criteria andIMPORTEIsNull() {
            addCriterion("IMPORTE is null");
            return (Criteria) this;
        }

        public Criteria andIMPORTEIsNotNull() {
            addCriterion("IMPORTE is not null");
            return (Criteria) this;
        }

        public Criteria andIMPORTEEqualTo(Double value) {
            addCriterion("IMPORTE =", value, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTENotEqualTo(Double value) {
            addCriterion("IMPORTE <>", value, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTEGreaterThan(Double value) {
            addCriterion("IMPORTE >", value, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTEGreaterThanOrEqualTo(Double value) {
            addCriterion("IMPORTE >=", value, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTELessThan(Double value) {
            addCriterion("IMPORTE <", value, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTELessThanOrEqualTo(Double value) {
            addCriterion("IMPORTE <=", value, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTEIn(List<Double> values) {
            addCriterion("IMPORTE in", values, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTENotIn(List<Double> values) {
            addCriterion("IMPORTE not in", values, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTEBetween(Double value1, Double value2) {
            addCriterion("IMPORTE between", value1, value2, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTENotBetween(Double value1, Double value2) {
            addCriterion("IMPORTE not between", value1, value2, "IMPORTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVAIsNull() {
            addCriterion("IMPORTE_IVA is null");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVAIsNotNull() {
            addCriterion("IMPORTE_IVA is not null");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVAEqualTo(Double value) {
            addCriterion("IMPORTE_IVA =", value, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVANotEqualTo(Double value) {
            addCriterion("IMPORTE_IVA <>", value, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVAGreaterThan(Double value) {
            addCriterion("IMPORTE_IVA >", value, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVAGreaterThanOrEqualTo(Double value) {
            addCriterion("IMPORTE_IVA >=", value, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVALessThan(Double value) {
            addCriterion("IMPORTE_IVA <", value, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVALessThanOrEqualTo(Double value) {
            addCriterion("IMPORTE_IVA <=", value, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVAIn(List<Double> values) {
            addCriterion("IMPORTE_IVA in", values, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVANotIn(List<Double> values) {
            addCriterion("IMPORTE_IVA not in", values, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVABetween(Double value1, Double value2) {
            addCriterion("IMPORTE_IVA between", value1, value2, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_IVANotBetween(Double value1, Double value2) {
            addCriterion("IMPORTE_IVA not between", value1, value2, "IMPORTE_IVA");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALIsNull() {
            addCriterion("IMPORTE_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALIsNotNull() {
            addCriterion("IMPORTE_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALEqualTo(Double value) {
            addCriterion("IMPORTE_TOTAL =", value, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALNotEqualTo(Double value) {
            addCriterion("IMPORTE_TOTAL <>", value, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALGreaterThan(Double value) {
            addCriterion("IMPORTE_TOTAL >", value, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALGreaterThanOrEqualTo(Double value) {
            addCriterion("IMPORTE_TOTAL >=", value, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALLessThan(Double value) {
            addCriterion("IMPORTE_TOTAL <", value, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALLessThanOrEqualTo(Double value) {
            addCriterion("IMPORTE_TOTAL <=", value, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALIn(List<Double> values) {
            addCriterion("IMPORTE_TOTAL in", values, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALNotIn(List<Double> values) {
            addCriterion("IMPORTE_TOTAL not in", values, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALBetween(Double value1, Double value2) {
            addCriterion("IMPORTE_TOTAL between", value1, value2, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_TOTALNotBetween(Double value1, Double value2) {
            addCriterion("IMPORTE_TOTAL not between", value1, value2, "IMPORTE_TOTAL");
            return (Criteria) this;
        }

        public Criteria andRFCIsNull() {
            addCriterion("RFC is null");
            return (Criteria) this;
        }

        public Criteria andRFCIsNotNull() {
            addCriterion("RFC is not null");
            return (Criteria) this;
        }

        public Criteria andRFCEqualTo(String value) {
            addCriterion("RFC =", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCNotEqualTo(String value) {
            addCriterion("RFC <>", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCGreaterThan(String value) {
            addCriterion("RFC >", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCGreaterThanOrEqualTo(String value) {
            addCriterion("RFC >=", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCLessThan(String value) {
            addCriterion("RFC <", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCLessThanOrEqualTo(String value) {
            addCriterion("RFC <=", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCLike(String value) {
            addCriterion("RFC like", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCNotLike(String value) {
            addCriterion("RFC not like", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCIn(List<String> values) {
            addCriterion("RFC in", values, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCNotIn(List<String> values) {
            addCriterion("RFC not in", values, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCBetween(String value1, String value2) {
            addCriterion("RFC between", value1, value2, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCNotBetween(String value1, String value2) {
            addCriterion("RFC not between", value1, value2, "RFC");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALIsNull() {
            addCriterion("RAZON_SOCIAL is null");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALIsNotNull() {
            addCriterion("RAZON_SOCIAL is not null");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALEqualTo(String value) {
            addCriterion("RAZON_SOCIAL =", value, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALNotEqualTo(String value) {
            addCriterion("RAZON_SOCIAL <>", value, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALGreaterThan(String value) {
            addCriterion("RAZON_SOCIAL >", value, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALGreaterThanOrEqualTo(String value) {
            addCriterion("RAZON_SOCIAL >=", value, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALLessThan(String value) {
            addCriterion("RAZON_SOCIAL <", value, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALLessThanOrEqualTo(String value) {
            addCriterion("RAZON_SOCIAL <=", value, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALLike(String value) {
            addCriterion("RAZON_SOCIAL like", value, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALNotLike(String value) {
            addCriterion("RAZON_SOCIAL not like", value, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALIn(List<String> values) {
            addCriterion("RAZON_SOCIAL in", values, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALNotIn(List<String> values) {
            addCriterion("RAZON_SOCIAL not in", values, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALBetween(String value1, String value2) {
            addCriterion("RAZON_SOCIAL between", value1, value2, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andRAZON_SOCIALNotBetween(String value1, String value2) {
            addCriterion("RAZON_SOCIAL not between", value1, value2, "RAZON_SOCIAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALIsNull() {
            addCriterion("CALLE_FISCAL is null");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALIsNotNull() {
            addCriterion("CALLE_FISCAL is not null");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALEqualTo(String value) {
            addCriterion("CALLE_FISCAL =", value, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALNotEqualTo(String value) {
            addCriterion("CALLE_FISCAL <>", value, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALGreaterThan(String value) {
            addCriterion("CALLE_FISCAL >", value, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALGreaterThanOrEqualTo(String value) {
            addCriterion("CALLE_FISCAL >=", value, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALLessThan(String value) {
            addCriterion("CALLE_FISCAL <", value, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALLessThanOrEqualTo(String value) {
            addCriterion("CALLE_FISCAL <=", value, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALLike(String value) {
            addCriterion("CALLE_FISCAL like", value, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALNotLike(String value) {
            addCriterion("CALLE_FISCAL not like", value, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALIn(List<String> values) {
            addCriterion("CALLE_FISCAL in", values, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALNotIn(List<String> values) {
            addCriterion("CALLE_FISCAL not in", values, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALBetween(String value1, String value2) {
            addCriterion("CALLE_FISCAL between", value1, value2, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCALLE_FISCALNotBetween(String value1, String value2) {
            addCriterion("CALLE_FISCAL not between", value1, value2, "CALLE_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALIsNull() {
            addCriterion("NUMERO_EXTERIOR_FISCAL is null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALIsNotNull() {
            addCriterion("NUMERO_EXTERIOR_FISCAL is not null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALEqualTo(String value) {
            addCriterion("NUMERO_EXTERIOR_FISCAL =", value, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALNotEqualTo(String value) {
            addCriterion("NUMERO_EXTERIOR_FISCAL <>", value, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALGreaterThan(String value) {
            addCriterion("NUMERO_EXTERIOR_FISCAL >", value, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALGreaterThanOrEqualTo(String value) {
            addCriterion("NUMERO_EXTERIOR_FISCAL >=", value, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALLessThan(String value) {
            addCriterion("NUMERO_EXTERIOR_FISCAL <", value, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALLessThanOrEqualTo(String value) {
            addCriterion("NUMERO_EXTERIOR_FISCAL <=", value, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALLike(String value) {
            addCriterion("NUMERO_EXTERIOR_FISCAL like", value, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALNotLike(String value) {
            addCriterion("NUMERO_EXTERIOR_FISCAL not like", value, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALIn(List<String> values) {
            addCriterion("NUMERO_EXTERIOR_FISCAL in", values, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALNotIn(List<String> values) {
            addCriterion("NUMERO_EXTERIOR_FISCAL not in", values, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALBetween(String value1, String value2) {
            addCriterion("NUMERO_EXTERIOR_FISCAL between", value1, value2, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_EXTERIOR_FISCALNotBetween(String value1, String value2) {
            addCriterion("NUMERO_EXTERIOR_FISCAL not between", value1, value2, "NUMERO_EXTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALIsNull() {
            addCriterion("NUMERO_INTERIOR_FISCAL is null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALIsNotNull() {
            addCriterion("NUMERO_INTERIOR_FISCAL is not null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALEqualTo(String value) {
            addCriterion("NUMERO_INTERIOR_FISCAL =", value, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALNotEqualTo(String value) {
            addCriterion("NUMERO_INTERIOR_FISCAL <>", value, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALGreaterThan(String value) {
            addCriterion("NUMERO_INTERIOR_FISCAL >", value, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALGreaterThanOrEqualTo(String value) {
            addCriterion("NUMERO_INTERIOR_FISCAL >=", value, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALLessThan(String value) {
            addCriterion("NUMERO_INTERIOR_FISCAL <", value, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALLessThanOrEqualTo(String value) {
            addCriterion("NUMERO_INTERIOR_FISCAL <=", value, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALLike(String value) {
            addCriterion("NUMERO_INTERIOR_FISCAL like", value, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALNotLike(String value) {
            addCriterion("NUMERO_INTERIOR_FISCAL not like", value, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALIn(List<String> values) {
            addCriterion("NUMERO_INTERIOR_FISCAL in", values, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALNotIn(List<String> values) {
            addCriterion("NUMERO_INTERIOR_FISCAL not in", values, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALBetween(String value1, String value2) {
            addCriterion("NUMERO_INTERIOR_FISCAL between", value1, value2, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andNUMERO_INTERIOR_FISCALNotBetween(String value1, String value2) {
            addCriterion("NUMERO_INTERIOR_FISCAL not between", value1, value2, "NUMERO_INTERIOR_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALIsNull() {
            addCriterion("COLONIA_FISCAL is null");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALIsNotNull() {
            addCriterion("COLONIA_FISCAL is not null");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALEqualTo(String value) {
            addCriterion("COLONIA_FISCAL =", value, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALNotEqualTo(String value) {
            addCriterion("COLONIA_FISCAL <>", value, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALGreaterThan(String value) {
            addCriterion("COLONIA_FISCAL >", value, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALGreaterThanOrEqualTo(String value) {
            addCriterion("COLONIA_FISCAL >=", value, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALLessThan(String value) {
            addCriterion("COLONIA_FISCAL <", value, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALLessThanOrEqualTo(String value) {
            addCriterion("COLONIA_FISCAL <=", value, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALLike(String value) {
            addCriterion("COLONIA_FISCAL like", value, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALNotLike(String value) {
            addCriterion("COLONIA_FISCAL not like", value, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALIn(List<String> values) {
            addCriterion("COLONIA_FISCAL in", values, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALNotIn(List<String> values) {
            addCriterion("COLONIA_FISCAL not in", values, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALBetween(String value1, String value2) {
            addCriterion("COLONIA_FISCAL between", value1, value2, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCOLONIA_FISCALNotBetween(String value1, String value2) {
            addCriterion("COLONIA_FISCAL not between", value1, value2, "COLONIA_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALIsNull() {
            addCriterion("CIUDAD_FISCAL is null");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALIsNotNull() {
            addCriterion("CIUDAD_FISCAL is not null");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALEqualTo(String value) {
            addCriterion("CIUDAD_FISCAL =", value, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALNotEqualTo(String value) {
            addCriterion("CIUDAD_FISCAL <>", value, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALGreaterThan(String value) {
            addCriterion("CIUDAD_FISCAL >", value, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALGreaterThanOrEqualTo(String value) {
            addCriterion("CIUDAD_FISCAL >=", value, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALLessThan(String value) {
            addCriterion("CIUDAD_FISCAL <", value, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALLessThanOrEqualTo(String value) {
            addCriterion("CIUDAD_FISCAL <=", value, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALLike(String value) {
            addCriterion("CIUDAD_FISCAL like", value, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALNotLike(String value) {
            addCriterion("CIUDAD_FISCAL not like", value, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALIn(List<String> values) {
            addCriterion("CIUDAD_FISCAL in", values, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALNotIn(List<String> values) {
            addCriterion("CIUDAD_FISCAL not in", values, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALBetween(String value1, String value2) {
            addCriterion("CIUDAD_FISCAL between", value1, value2, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCIUDAD_FISCALNotBetween(String value1, String value2) {
            addCriterion("CIUDAD_FISCAL not between", value1, value2, "CIUDAD_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALIsNull() {
            addCriterion("MUNICIPIO_FISCAL is null");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALIsNotNull() {
            addCriterion("MUNICIPIO_FISCAL is not null");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALEqualTo(String value) {
            addCriterion("MUNICIPIO_FISCAL =", value, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALNotEqualTo(String value) {
            addCriterion("MUNICIPIO_FISCAL <>", value, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALGreaterThan(String value) {
            addCriterion("MUNICIPIO_FISCAL >", value, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALGreaterThanOrEqualTo(String value) {
            addCriterion("MUNICIPIO_FISCAL >=", value, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALLessThan(String value) {
            addCriterion("MUNICIPIO_FISCAL <", value, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALLessThanOrEqualTo(String value) {
            addCriterion("MUNICIPIO_FISCAL <=", value, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALLike(String value) {
            addCriterion("MUNICIPIO_FISCAL like", value, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALNotLike(String value) {
            addCriterion("MUNICIPIO_FISCAL not like", value, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALIn(List<String> values) {
            addCriterion("MUNICIPIO_FISCAL in", values, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALNotIn(List<String> values) {
            addCriterion("MUNICIPIO_FISCAL not in", values, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALBetween(String value1, String value2) {
            addCriterion("MUNICIPIO_FISCAL between", value1, value2, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andMUNICIPIO_FISCALNotBetween(String value1, String value2) {
            addCriterion("MUNICIPIO_FISCAL not between", value1, value2, "MUNICIPIO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALIsNull() {
            addCriterion("ESTADO_FISCAL is null");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALIsNotNull() {
            addCriterion("ESTADO_FISCAL is not null");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALEqualTo(String value) {
            addCriterion("ESTADO_FISCAL =", value, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALNotEqualTo(String value) {
            addCriterion("ESTADO_FISCAL <>", value, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALGreaterThan(String value) {
            addCriterion("ESTADO_FISCAL >", value, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALGreaterThanOrEqualTo(String value) {
            addCriterion("ESTADO_FISCAL >=", value, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALLessThan(String value) {
            addCriterion("ESTADO_FISCAL <", value, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALLessThanOrEqualTo(String value) {
            addCriterion("ESTADO_FISCAL <=", value, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALLike(String value) {
            addCriterion("ESTADO_FISCAL like", value, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALNotLike(String value) {
            addCriterion("ESTADO_FISCAL not like", value, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALIn(List<String> values) {
            addCriterion("ESTADO_FISCAL in", values, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALNotIn(List<String> values) {
            addCriterion("ESTADO_FISCAL not in", values, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALBetween(String value1, String value2) {
            addCriterion("ESTADO_FISCAL between", value1, value2, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andESTADO_FISCALNotBetween(String value1, String value2) {
            addCriterion("ESTADO_FISCAL not between", value1, value2, "ESTADO_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALIsNull() {
            addCriterion("PAIS_FISCAL is null");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALIsNotNull() {
            addCriterion("PAIS_FISCAL is not null");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALEqualTo(String value) {
            addCriterion("PAIS_FISCAL =", value, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALNotEqualTo(String value) {
            addCriterion("PAIS_FISCAL <>", value, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALGreaterThan(String value) {
            addCriterion("PAIS_FISCAL >", value, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALGreaterThanOrEqualTo(String value) {
            addCriterion("PAIS_FISCAL >=", value, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALLessThan(String value) {
            addCriterion("PAIS_FISCAL <", value, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALLessThanOrEqualTo(String value) {
            addCriterion("PAIS_FISCAL <=", value, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALLike(String value) {
            addCriterion("PAIS_FISCAL like", value, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALNotLike(String value) {
            addCriterion("PAIS_FISCAL not like", value, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALIn(List<String> values) {
            addCriterion("PAIS_FISCAL in", values, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALNotIn(List<String> values) {
            addCriterion("PAIS_FISCAL not in", values, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALBetween(String value1, String value2) {
            addCriterion("PAIS_FISCAL between", value1, value2, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andPAIS_FISCALNotBetween(String value1, String value2) {
            addCriterion("PAIS_FISCAL not between", value1, value2, "PAIS_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALIsNull() {
            addCriterion("CODI_POSTAL_FISCAL is null");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALIsNotNull() {
            addCriterion("CODI_POSTAL_FISCAL is not null");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALEqualTo(String value) {
            addCriterion("CODI_POSTAL_FISCAL =", value, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALNotEqualTo(String value) {
            addCriterion("CODI_POSTAL_FISCAL <>", value, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALGreaterThan(String value) {
            addCriterion("CODI_POSTAL_FISCAL >", value, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALGreaterThanOrEqualTo(String value) {
            addCriterion("CODI_POSTAL_FISCAL >=", value, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALLessThan(String value) {
            addCriterion("CODI_POSTAL_FISCAL <", value, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALLessThanOrEqualTo(String value) {
            addCriterion("CODI_POSTAL_FISCAL <=", value, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALLike(String value) {
            addCriterion("CODI_POSTAL_FISCAL like", value, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALNotLike(String value) {
            addCriterion("CODI_POSTAL_FISCAL not like", value, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALIn(List<String> values) {
            addCriterion("CODI_POSTAL_FISCAL in", values, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALNotIn(List<String> values) {
            addCriterion("CODI_POSTAL_FISCAL not in", values, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALBetween(String value1, String value2) {
            addCriterion("CODI_POSTAL_FISCAL between", value1, value2, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andCODI_POSTAL_FISCALNotBetween(String value1, String value2) {
            addCriterion("CODI_POSTAL_FISCAL not between", value1, value2, "CODI_POSTAL_FISCAL");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOIsNull() {
            addCriterion("TIPO_DOCUMENTO is null");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOIsNotNull() {
            addCriterion("TIPO_DOCUMENTO is not null");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOEqualTo(String value) {
            addCriterion("TIPO_DOCUMENTO =", value, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTONotEqualTo(String value) {
            addCriterion("TIPO_DOCUMENTO <>", value, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOGreaterThan(String value) {
            addCriterion("TIPO_DOCUMENTO >", value, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOGreaterThanOrEqualTo(String value) {
            addCriterion("TIPO_DOCUMENTO >=", value, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOLessThan(String value) {
            addCriterion("TIPO_DOCUMENTO <", value, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOLessThanOrEqualTo(String value) {
            addCriterion("TIPO_DOCUMENTO <=", value, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOLike(String value) {
            addCriterion("TIPO_DOCUMENTO like", value, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTONotLike(String value) {
            addCriterion("TIPO_DOCUMENTO not like", value, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOIn(List<String> values) {
            addCriterion("TIPO_DOCUMENTO in", values, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTONotIn(List<String> values) {
            addCriterion("TIPO_DOCUMENTO not in", values, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTOBetween(String value1, String value2) {
            addCriterion("TIPO_DOCUMENTO between", value1, value2, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andTIPO_DOCUMENTONotBetween(String value1, String value2) {
            addCriterion("TIPO_DOCUMENTO not between", value1, value2, "TIPO_DOCUMENTO");
            return (Criteria) this;
        }

        public Criteria andAGENTEIsNull() {
            addCriterion("AGENTE is null");
            return (Criteria) this;
        }

        public Criteria andAGENTEIsNotNull() {
            addCriterion("AGENTE is not null");
            return (Criteria) this;
        }

        public Criteria andAGENTEEqualTo(String value) {
            addCriterion("AGENTE =", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTENotEqualTo(String value) {
            addCriterion("AGENTE <>", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTEGreaterThan(String value) {
            addCriterion("AGENTE >", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTEGreaterThanOrEqualTo(String value) {
            addCriterion("AGENTE >=", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTELessThan(String value) {
            addCriterion("AGENTE <", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTELessThanOrEqualTo(String value) {
            addCriterion("AGENTE <=", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTELike(String value) {
            addCriterion("AGENTE like", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTENotLike(String value) {
            addCriterion("AGENTE not like", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTEIn(List<String> values) {
            addCriterion("AGENTE in", values, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTENotIn(List<String> values) {
            addCriterion("AGENTE not in", values, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTEBetween(String value1, String value2) {
            addCriterion("AGENTE between", value1, value2, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTENotBetween(String value1, String value2) {
            addCriterion("AGENTE not between", value1, value2, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andANOIsNull() {
            addCriterion("ANO is null");
            return (Criteria) this;
        }

        public Criteria andANOIsNotNull() {
            addCriterion("ANO is not null");
            return (Criteria) this;
        }

        public Criteria andANOEqualTo(String value) {
            addCriterion("ANO =", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANONotEqualTo(String value) {
            addCriterion("ANO <>", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOGreaterThan(String value) {
            addCriterion("ANO >", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOGreaterThanOrEqualTo(String value) {
            addCriterion("ANO >=", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOLessThan(String value) {
            addCriterion("ANO <", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOLessThanOrEqualTo(String value) {
            addCriterion("ANO <=", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOLike(String value) {
            addCriterion("ANO like", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANONotLike(String value) {
            addCriterion("ANO not like", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOIn(List<String> values) {
            addCriterion("ANO in", values, "ANO");
            return (Criteria) this;
        }

        public Criteria andANONotIn(List<String> values) {
            addCriterion("ANO not in", values, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOBetween(String value1, String value2) {
            addCriterion("ANO between", value1, value2, "ANO");
            return (Criteria) this;
        }

        public Criteria andANONotBetween(String value1, String value2) {
            addCriterion("ANO not between", value1, value2, "ANO");
            return (Criteria) this;
        }

        public Criteria andMESIsNull() {
            addCriterion("MES is null");
            return (Criteria) this;
        }

        public Criteria andMESIsNotNull() {
            addCriterion("MES is not null");
            return (Criteria) this;
        }

        public Criteria andMESEqualTo(String value) {
            addCriterion("MES =", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESNotEqualTo(String value) {
            addCriterion("MES <>", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESGreaterThan(String value) {
            addCriterion("MES >", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESGreaterThanOrEqualTo(String value) {
            addCriterion("MES >=", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESLessThan(String value) {
            addCriterion("MES <", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESLessThanOrEqualTo(String value) {
            addCriterion("MES <=", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESLike(String value) {
            addCriterion("MES like", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESNotLike(String value) {
            addCriterion("MES not like", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESIn(List<String> values) {
            addCriterion("MES in", values, "MES");
            return (Criteria) this;
        }

        public Criteria andMESNotIn(List<String> values) {
            addCriterion("MES not in", values, "MES");
            return (Criteria) this;
        }

        public Criteria andMESBetween(String value1, String value2) {
            addCriterion("MES between", value1, value2, "MES");
            return (Criteria) this;
        }

        public Criteria andMESNotBetween(String value1, String value2) {
            addCriterion("MES not between", value1, value2, "MES");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEIsNull() {
            addCriterion("SIT_COMPROBANTE is null");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEIsNotNull() {
            addCriterion("SIT_COMPROBANTE is not null");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEEqualTo(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE =", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTENotEqualTo(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE <>", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEGreaterThan(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE >", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE >=", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTELessThan(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE <", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTELessThanOrEqualTo(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE <=", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEIn(List<BigDecimal> values) {
            addCriterion("SIT_COMPROBANTE in", values, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTENotIn(List<BigDecimal> values) {
            addCriterion("SIT_COMPROBANTE not in", values, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SIT_COMPROBANTE between", value1, value2, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTENotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SIT_COMPROBANTE not between", value1, value2, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEIsNull() {
            addCriterion("NUMERO_CLIENTE is null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEIsNotNull() {
            addCriterion("NUMERO_CLIENTE is not null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEEqualTo(String value) {
            addCriterion("NUMERO_CLIENTE =", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTENotEqualTo(String value) {
            addCriterion("NUMERO_CLIENTE <>", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEGreaterThan(String value) {
            addCriterion("NUMERO_CLIENTE >", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEGreaterThanOrEqualTo(String value) {
            addCriterion("NUMERO_CLIENTE >=", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTELessThan(String value) {
            addCriterion("NUMERO_CLIENTE <", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTELessThanOrEqualTo(String value) {
            addCriterion("NUMERO_CLIENTE <=", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTELike(String value) {
            addCriterion("NUMERO_CLIENTE like", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTENotLike(String value) {
            addCriterion("NUMERO_CLIENTE not like", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEIn(List<String> values) {
            addCriterion("NUMERO_CLIENTE in", values, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTENotIn(List<String> values) {
            addCriterion("NUMERO_CLIENTE not in", values, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEBetween(String value1, String value2) {
            addCriterion("NUMERO_CLIENTE between", value1, value2, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTENotBetween(String value1, String value2) {
            addCriterion("NUMERO_CLIENTE not between", value1, value2, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRIsNull() {
            addCriterion("IMPORTE_ISR is null");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRIsNotNull() {
            addCriterion("IMPORTE_ISR is not null");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISREqualTo(Double value) {
            addCriterion("IMPORTE_ISR =", value, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRNotEqualTo(Double value) {
            addCriterion("IMPORTE_ISR <>", value, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRGreaterThan(Double value) {
            addCriterion("IMPORTE_ISR >", value, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRGreaterThanOrEqualTo(Double value) {
            addCriterion("IMPORTE_ISR >=", value, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRLessThan(Double value) {
            addCriterion("IMPORTE_ISR <", value, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRLessThanOrEqualTo(Double value) {
            addCriterion("IMPORTE_ISR <=", value, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRIn(List<Double> values) {
            addCriterion("IMPORTE_ISR in", values, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRNotIn(List<Double> values) {
            addCriterion("IMPORTE_ISR not in", values, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRBetween(Double value1, Double value2) {
            addCriterion("IMPORTE_ISR between", value1, value2, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_ISRNotBetween(Double value1, Double value2) {
            addCriterion("IMPORTE_ISR not between", value1, value2, "IMPORTE_ISR");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETIsNull() {
            addCriterion("IMPORTE_RET is null");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETIsNotNull() {
            addCriterion("IMPORTE_RET is not null");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETEqualTo(Double value) {
            addCriterion("IMPORTE_RET =", value, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETNotEqualTo(Double value) {
            addCriterion("IMPORTE_RET <>", value, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETGreaterThan(Double value) {
            addCriterion("IMPORTE_RET >", value, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETGreaterThanOrEqualTo(Double value) {
            addCriterion("IMPORTE_RET >=", value, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETLessThan(Double value) {
            addCriterion("IMPORTE_RET <", value, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETLessThanOrEqualTo(Double value) {
            addCriterion("IMPORTE_RET <=", value, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETIn(List<Double> values) {
            addCriterion("IMPORTE_RET in", values, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETNotIn(List<Double> values) {
            addCriterion("IMPORTE_RET not in", values, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETBetween(Double value1, Double value2) {
            addCriterion("IMPORTE_RET between", value1, value2, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andIMPORTE_RETNotBetween(Double value1, Double value2) {
            addCriterion("IMPORTE_RET not between", value1, value2, "IMPORTE_RET");
            return (Criteria) this;
        }

        public Criteria andPOLIZAIsNull() {
            addCriterion("POLIZA is null");
            return (Criteria) this;
        }

        public Criteria andPOLIZAIsNotNull() {
            addCriterion("POLIZA is not null");
            return (Criteria) this;
        }

        public Criteria andPOLIZAEqualTo(String value) {
            addCriterion("POLIZA =", value, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZANotEqualTo(String value) {
            addCriterion("POLIZA <>", value, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZAGreaterThan(String value) {
            addCriterion("POLIZA >", value, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZAGreaterThanOrEqualTo(String value) {
            addCriterion("POLIZA >=", value, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZALessThan(String value) {
            addCriterion("POLIZA <", value, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZALessThanOrEqualTo(String value) {
            addCriterion("POLIZA <=", value, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZALike(String value) {
            addCriterion("POLIZA like", value, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZANotLike(String value) {
            addCriterion("POLIZA not like", value, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZAIn(List<String> values) {
            addCriterion("POLIZA in", values, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZANotIn(List<String> values) {
            addCriterion("POLIZA not in", values, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZABetween(String value1, String value2) {
            addCriterion("POLIZA between", value1, value2, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andPOLIZANotBetween(String value1, String value2) {
            addCriterion("POLIZA not between", value1, value2, "POLIZA");
            return (Criteria) this;
        }

        public Criteria andFECHAIsNull() {
            addCriterion("FECHA is null");
            return (Criteria) this;
        }

        public Criteria andFECHAIsNotNull() {
            addCriterion("FECHA is not null");
            return (Criteria) this;
        }

        public Criteria andFECHAEqualTo(Date value) {
            addCriterion("FECHA =", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHANotEqualTo(Date value) {
            addCriterion("FECHA <>", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHAGreaterThan(Date value) {
            addCriterion("FECHA >", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHAGreaterThanOrEqualTo(Date value) {
            addCriterion("FECHA >=", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHALessThan(Date value) {
            addCriterion("FECHA <", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHALessThanOrEqualTo(Date value) {
            addCriterion("FECHA <=", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHAIn(List<Date> values) {
            addCriterion("FECHA in", values, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHANotIn(List<Date> values) {
            addCriterion("FECHA not in", values, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHABetween(Date value1, Date value2) {
            addCriterion("FECHA between", value1, value2, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHANotBetween(Date value1, Date value2) {
            addCriterion("FECHA not between", value1, value2, "FECHA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURAIsNull() {
            addCriterion("NUMERO_FACTURA is null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURAIsNotNull() {
            addCriterion("NUMERO_FACTURA is not null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURAEqualTo(String value) {
            addCriterion("NUMERO_FACTURA =", value, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURANotEqualTo(String value) {
            addCriterion("NUMERO_FACTURA <>", value, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURAGreaterThan(String value) {
            addCriterion("NUMERO_FACTURA >", value, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURAGreaterThanOrEqualTo(String value) {
            addCriterion("NUMERO_FACTURA >=", value, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURALessThan(String value) {
            addCriterion("NUMERO_FACTURA <", value, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURALessThanOrEqualTo(String value) {
            addCriterion("NUMERO_FACTURA <=", value, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURALike(String value) {
            addCriterion("NUMERO_FACTURA like", value, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURANotLike(String value) {
            addCriterion("NUMERO_FACTURA not like", value, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURAIn(List<String> values) {
            addCriterion("NUMERO_FACTURA in", values, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURANotIn(List<String> values) {
            addCriterion("NUMERO_FACTURA not in", values, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURABetween(String value1, String value2) {
            addCriterion("NUMERO_FACTURA between", value1, value2, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andNUMERO_FACTURANotBetween(String value1, String value2) {
            addCriterion("NUMERO_FACTURA not between", value1, value2, "NUMERO_FACTURA");
            return (Criteria) this;
        }

        public Criteria andSERIEIsNull() {
            addCriterion("SERIE is null");
            return (Criteria) this;
        }

        public Criteria andSERIEIsNotNull() {
            addCriterion("SERIE is not null");
            return (Criteria) this;
        }

        public Criteria andSERIEEqualTo(String value) {
            addCriterion("SERIE =", value, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIENotEqualTo(String value) {
            addCriterion("SERIE <>", value, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIEGreaterThan(String value) {
            addCriterion("SERIE >", value, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIEGreaterThanOrEqualTo(String value) {
            addCriterion("SERIE >=", value, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIELessThan(String value) {
            addCriterion("SERIE <", value, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIELessThanOrEqualTo(String value) {
            addCriterion("SERIE <=", value, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIELike(String value) {
            addCriterion("SERIE like", value, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIENotLike(String value) {
            addCriterion("SERIE not like", value, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIEIn(List<String> values) {
            addCriterion("SERIE in", values, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIENotIn(List<String> values) {
            addCriterion("SERIE not in", values, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIEBetween(String value1, String value2) {
            addCriterion("SERIE between", value1, value2, "SERIE");
            return (Criteria) this;
        }

        public Criteria andSERIENotBetween(String value1, String value2) {
            addCriterion("SERIE not between", value1, value2, "SERIE");
            return (Criteria) this;
        }

        public Criteria andFOLIOIsNull() {
            addCriterion("FOLIO is null");
            return (Criteria) this;
        }

        public Criteria andFOLIOIsNotNull() {
            addCriterion("FOLIO is not null");
            return (Criteria) this;
        }

        public Criteria andFOLIOEqualTo(String value) {
            addCriterion("FOLIO =", value, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIONotEqualTo(String value) {
            addCriterion("FOLIO <>", value, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIOGreaterThan(String value) {
            addCriterion("FOLIO >", value, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIOGreaterThanOrEqualTo(String value) {
            addCriterion("FOLIO >=", value, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIOLessThan(String value) {
            addCriterion("FOLIO <", value, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIOLessThanOrEqualTo(String value) {
            addCriterion("FOLIO <=", value, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIOLike(String value) {
            addCriterion("FOLIO like", value, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIONotLike(String value) {
            addCriterion("FOLIO not like", value, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIOIn(List<String> values) {
            addCriterion("FOLIO in", values, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIONotIn(List<String> values) {
            addCriterion("FOLIO not in", values, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIOBetween(String value1, String value2) {
            addCriterion("FOLIO between", value1, value2, "FOLIO");
            return (Criteria) this;
        }

        public Criteria andFOLIONotBetween(String value1, String value2) {
            addCriterion("FOLIO not between", value1, value2, "FOLIO");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 23 01:38:48 CDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}