package mx.com.ebs.inter.data.model.facbanco;

import java.math.BigDecimal;
import java.util.Date;

public class Invoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.NCLAVE_SUCURSAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal NCLAVE_SUCURSAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.LUGAR_EXPEDICION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String LUGAR_EXPEDICION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.FECHA_EMISION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FECHA_EMISION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.HORA_EMISION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String HORA_EMISION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.IMPORTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double IMPORTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.IMPORTE_IVA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double IMPORTE_IVA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.IMPORTE_TOTAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double IMPORTE_TOTAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.BANCO1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String BANCO1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.CUENTA1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String CUENTA1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.REFERENCIA1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal REFERENCIA1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.FECHA_ENTREGA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FECHA_ENTREGA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.COMENTARIOS
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String COMENTARIOS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.RAZON_SOCIAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String RAZON_SOCIAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.CALLE_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String CALLE_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.NUMERO_EXTERIOR_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String NUMERO_EXTERIOR_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.NUMERO_INTERIOR_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String NUMERO_INTERIOR_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.COLONIA_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String COLONIA_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.CIUDAD_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String CIUDAD_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.MUNICIPIO_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String MUNICIPIO_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.ESTADO_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String ESTADO_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.PAIS_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PAIS_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.CODI_POSTAL_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String CODI_POSTAL_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.RESPONSABLE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String RESPONSABLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.CALLE_ENTREGA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String CALLE_ENTREGA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.TELEFONO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String TELEFONO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.ESTADO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String ESTADO_DOCUMENTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.NUMERO_FACTURA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String NUMERO_FACTURA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.FLAG
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal FLAG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.SERIE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String SERIE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.FOLIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String FOLIO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.FECHA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FECHA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.NO_APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal NO_APROBACION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.STATUS_DOC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String STATUS_DOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.HORA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String HORA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.TASA_IMPUESTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal TASA_IMPUESTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal APROBACION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.RFC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String RFC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.SERIE_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String SERIE_ERP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.FOLIO_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String FOLIO_ERP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.TOTALML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double TOTALML;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.TIPO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String TIPO_DOCUMENTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.NUMERO_CLIENTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String NUMERO_CLIENTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.MONEDA_DOC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String MONEDA_DOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.FECHA_CANCELACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FECHA_CANCELACION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.STATUS
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.STATUS_ENVIOI
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal STATUS_ENVIOI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.STATUS_ENVIOM
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal STATUS_ENVIOM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.STATUS_ENVIOF
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal STATUS_ENVIOF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.DESCRIPCION_PRODUCTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String DESCRIPCION_PRODUCTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.VTIPO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String VTIPO_DOCUMENTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.NNUMERO_PEDIDO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal NNUMERO_PEDIDO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.TIPO_CAMBIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double TIPO_CAMBIO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.STATUS_PRINT
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal STATUS_PRINT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.ORIGEN
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private BigDecimal ORIGEN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.PLANTILLA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PLANTILLA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.POLIZA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String POLIZA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.ID_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String ID_DOCUMENTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.INVOICE.FECHA_CONSULTA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FECHA_CONSULTA;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.NCLAVE_SUCURSAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.NCLAVE_SUCURSAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getNCLAVE_SUCURSAL() {
        return NCLAVE_SUCURSAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.NCLAVE_SUCURSAL
     *
     * @param NCLAVE_SUCURSAL the value for M_INTERACCIONES.INVOICE.NCLAVE_SUCURSAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNCLAVE_SUCURSAL(BigDecimal NCLAVE_SUCURSAL) {
        this.NCLAVE_SUCURSAL = NCLAVE_SUCURSAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.LUGAR_EXPEDICION
     *
     * @return the value of M_INTERACCIONES.INVOICE.LUGAR_EXPEDICION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getLUGAR_EXPEDICION() {
        return LUGAR_EXPEDICION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.LUGAR_EXPEDICION
     *
     * @param LUGAR_EXPEDICION the value for M_INTERACCIONES.INVOICE.LUGAR_EXPEDICION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setLUGAR_EXPEDICION(String LUGAR_EXPEDICION) {
        this.LUGAR_EXPEDICION = LUGAR_EXPEDICION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.FECHA_EMISION
     *
     * @return the value of M_INTERACCIONES.INVOICE.FECHA_EMISION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFECHA_EMISION() {
        return FECHA_EMISION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.FECHA_EMISION
     *
     * @param FECHA_EMISION the value for M_INTERACCIONES.INVOICE.FECHA_EMISION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFECHA_EMISION(Date FECHA_EMISION) {
        this.FECHA_EMISION = FECHA_EMISION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.HORA_EMISION
     *
     * @return the value of M_INTERACCIONES.INVOICE.HORA_EMISION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getHORA_EMISION() {
        return HORA_EMISION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.HORA_EMISION
     *
     * @param HORA_EMISION the value for M_INTERACCIONES.INVOICE.HORA_EMISION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setHORA_EMISION(String HORA_EMISION) {
        this.HORA_EMISION = HORA_EMISION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.IMPORTE
     *
     * @return the value of M_INTERACCIONES.INVOICE.IMPORTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getIMPORTE() {
        return IMPORTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.IMPORTE
     *
     * @param IMPORTE the value for M_INTERACCIONES.INVOICE.IMPORTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setIMPORTE(Double IMPORTE) {
        this.IMPORTE = IMPORTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.IMPORTE_IVA
     *
     * @return the value of M_INTERACCIONES.INVOICE.IMPORTE_IVA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getIMPORTE_IVA() {
        return IMPORTE_IVA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.IMPORTE_IVA
     *
     * @param IMPORTE_IVA the value for M_INTERACCIONES.INVOICE.IMPORTE_IVA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setIMPORTE_IVA(Double IMPORTE_IVA) {
        this.IMPORTE_IVA = IMPORTE_IVA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.IMPORTE_TOTAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.IMPORTE_TOTAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getIMPORTE_TOTAL() {
        return IMPORTE_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.IMPORTE_TOTAL
     *
     * @param IMPORTE_TOTAL the value for M_INTERACCIONES.INVOICE.IMPORTE_TOTAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setIMPORTE_TOTAL(Double IMPORTE_TOTAL) {
        this.IMPORTE_TOTAL = IMPORTE_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.BANCO1
     *
     * @return the value of M_INTERACCIONES.INVOICE.BANCO1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getBANCO1() {
        return BANCO1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.BANCO1
     *
     * @param BANCO1 the value for M_INTERACCIONES.INVOICE.BANCO1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setBANCO1(String BANCO1) {
        this.BANCO1 = BANCO1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.CUENTA1
     *
     * @return the value of M_INTERACCIONES.INVOICE.CUENTA1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getCUENTA1() {
        return CUENTA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.CUENTA1
     *
     * @param CUENTA1 the value for M_INTERACCIONES.INVOICE.CUENTA1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setCUENTA1(String CUENTA1) {
        this.CUENTA1 = CUENTA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.REFERENCIA1
     *
     * @return the value of M_INTERACCIONES.INVOICE.REFERENCIA1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getREFERENCIA1() {
        return REFERENCIA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.REFERENCIA1
     *
     * @param REFERENCIA1 the value for M_INTERACCIONES.INVOICE.REFERENCIA1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setREFERENCIA1(BigDecimal REFERENCIA1) {
        this.REFERENCIA1 = REFERENCIA1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.FECHA_ENTREGA
     *
     * @return the value of M_INTERACCIONES.INVOICE.FECHA_ENTREGA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFECHA_ENTREGA() {
        return FECHA_ENTREGA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.FECHA_ENTREGA
     *
     * @param FECHA_ENTREGA the value for M_INTERACCIONES.INVOICE.FECHA_ENTREGA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFECHA_ENTREGA(Date FECHA_ENTREGA) {
        this.FECHA_ENTREGA = FECHA_ENTREGA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.COMENTARIOS
     *
     * @return the value of M_INTERACCIONES.INVOICE.COMENTARIOS
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getCOMENTARIOS() {
        return COMENTARIOS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.COMENTARIOS
     *
     * @param COMENTARIOS the value for M_INTERACCIONES.INVOICE.COMENTARIOS
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setCOMENTARIOS(String COMENTARIOS) {
        this.COMENTARIOS = COMENTARIOS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.RAZON_SOCIAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.RAZON_SOCIAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getRAZON_SOCIAL() {
        return RAZON_SOCIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.RAZON_SOCIAL
     *
     * @param RAZON_SOCIAL the value for M_INTERACCIONES.INVOICE.RAZON_SOCIAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setRAZON_SOCIAL(String RAZON_SOCIAL) {
        this.RAZON_SOCIAL = RAZON_SOCIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.CALLE_FISCAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.CALLE_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getCALLE_FISCAL() {
        return CALLE_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.CALLE_FISCAL
     *
     * @param CALLE_FISCAL the value for M_INTERACCIONES.INVOICE.CALLE_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setCALLE_FISCAL(String CALLE_FISCAL) {
        this.CALLE_FISCAL = CALLE_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.NUMERO_EXTERIOR_FISCAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.NUMERO_EXTERIOR_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getNUMERO_EXTERIOR_FISCAL() {
        return NUMERO_EXTERIOR_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.NUMERO_EXTERIOR_FISCAL
     *
     * @param NUMERO_EXTERIOR_FISCAL the value for M_INTERACCIONES.INVOICE.NUMERO_EXTERIOR_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNUMERO_EXTERIOR_FISCAL(String NUMERO_EXTERIOR_FISCAL) {
        this.NUMERO_EXTERIOR_FISCAL = NUMERO_EXTERIOR_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.NUMERO_INTERIOR_FISCAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.NUMERO_INTERIOR_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getNUMERO_INTERIOR_FISCAL() {
        return NUMERO_INTERIOR_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.NUMERO_INTERIOR_FISCAL
     *
     * @param NUMERO_INTERIOR_FISCAL the value for M_INTERACCIONES.INVOICE.NUMERO_INTERIOR_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNUMERO_INTERIOR_FISCAL(String NUMERO_INTERIOR_FISCAL) {
        this.NUMERO_INTERIOR_FISCAL = NUMERO_INTERIOR_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.COLONIA_FISCAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.COLONIA_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getCOLONIA_FISCAL() {
        return COLONIA_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.COLONIA_FISCAL
     *
     * @param COLONIA_FISCAL the value for M_INTERACCIONES.INVOICE.COLONIA_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setCOLONIA_FISCAL(String COLONIA_FISCAL) {
        this.COLONIA_FISCAL = COLONIA_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.CIUDAD_FISCAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.CIUDAD_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getCIUDAD_FISCAL() {
        return CIUDAD_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.CIUDAD_FISCAL
     *
     * @param CIUDAD_FISCAL the value for M_INTERACCIONES.INVOICE.CIUDAD_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setCIUDAD_FISCAL(String CIUDAD_FISCAL) {
        this.CIUDAD_FISCAL = CIUDAD_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.MUNICIPIO_FISCAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.MUNICIPIO_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getMUNICIPIO_FISCAL() {
        return MUNICIPIO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.MUNICIPIO_FISCAL
     *
     * @param MUNICIPIO_FISCAL the value for M_INTERACCIONES.INVOICE.MUNICIPIO_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setMUNICIPIO_FISCAL(String MUNICIPIO_FISCAL) {
        this.MUNICIPIO_FISCAL = MUNICIPIO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.ESTADO_FISCAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.ESTADO_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getESTADO_FISCAL() {
        return ESTADO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.ESTADO_FISCAL
     *
     * @param ESTADO_FISCAL the value for M_INTERACCIONES.INVOICE.ESTADO_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setESTADO_FISCAL(String ESTADO_FISCAL) {
        this.ESTADO_FISCAL = ESTADO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.PAIS_FISCAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.PAIS_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPAIS_FISCAL() {
        return PAIS_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.PAIS_FISCAL
     *
     * @param PAIS_FISCAL the value for M_INTERACCIONES.INVOICE.PAIS_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPAIS_FISCAL(String PAIS_FISCAL) {
        this.PAIS_FISCAL = PAIS_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.CODI_POSTAL_FISCAL
     *
     * @return the value of M_INTERACCIONES.INVOICE.CODI_POSTAL_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getCODI_POSTAL_FISCAL() {
        return CODI_POSTAL_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.CODI_POSTAL_FISCAL
     *
     * @param CODI_POSTAL_FISCAL the value for M_INTERACCIONES.INVOICE.CODI_POSTAL_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setCODI_POSTAL_FISCAL(String CODI_POSTAL_FISCAL) {
        this.CODI_POSTAL_FISCAL = CODI_POSTAL_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.RESPONSABLE
     *
     * @return the value of M_INTERACCIONES.INVOICE.RESPONSABLE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getRESPONSABLE() {
        return RESPONSABLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.RESPONSABLE
     *
     * @param RESPONSABLE the value for M_INTERACCIONES.INVOICE.RESPONSABLE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setRESPONSABLE(String RESPONSABLE) {
        this.RESPONSABLE = RESPONSABLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.CALLE_ENTREGA
     *
     * @return the value of M_INTERACCIONES.INVOICE.CALLE_ENTREGA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getCALLE_ENTREGA() {
        return CALLE_ENTREGA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.CALLE_ENTREGA
     *
     * @param CALLE_ENTREGA the value for M_INTERACCIONES.INVOICE.CALLE_ENTREGA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setCALLE_ENTREGA(String CALLE_ENTREGA) {
        this.CALLE_ENTREGA = CALLE_ENTREGA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.TELEFONO
     *
     * @return the value of M_INTERACCIONES.INVOICE.TELEFONO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getTELEFONO() {
        return TELEFONO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.TELEFONO
     *
     * @param TELEFONO the value for M_INTERACCIONES.INVOICE.TELEFONO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTELEFONO(String TELEFONO) {
        this.TELEFONO = TELEFONO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.ESTADO_DOCUMENTO
     *
     * @return the value of M_INTERACCIONES.INVOICE.ESTADO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getESTADO_DOCUMENTO() {
        return ESTADO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.ESTADO_DOCUMENTO
     *
     * @param ESTADO_DOCUMENTO the value for M_INTERACCIONES.INVOICE.ESTADO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setESTADO_DOCUMENTO(String ESTADO_DOCUMENTO) {
        this.ESTADO_DOCUMENTO = ESTADO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.NUMERO_FACTURA
     *
     * @return the value of M_INTERACCIONES.INVOICE.NUMERO_FACTURA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getNUMERO_FACTURA() {
        return NUMERO_FACTURA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.NUMERO_FACTURA
     *
     * @param NUMERO_FACTURA the value for M_INTERACCIONES.INVOICE.NUMERO_FACTURA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNUMERO_FACTURA(String NUMERO_FACTURA) {
        this.NUMERO_FACTURA = NUMERO_FACTURA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.FLAG
     *
     * @return the value of M_INTERACCIONES.INVOICE.FLAG
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getFLAG() {
        return FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.FLAG
     *
     * @param FLAG the value for M_INTERACCIONES.INVOICE.FLAG
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFLAG(BigDecimal FLAG) {
        this.FLAG = FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.SERIE
     *
     * @return the value of M_INTERACCIONES.INVOICE.SERIE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getSERIE() {
        return SERIE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.SERIE
     *
     * @param SERIE the value for M_INTERACCIONES.INVOICE.SERIE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSERIE(String SERIE) {
        this.SERIE = SERIE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.FOLIO
     *
     * @return the value of M_INTERACCIONES.INVOICE.FOLIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getFOLIO() {
        return FOLIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.FOLIO
     *
     * @param FOLIO the value for M_INTERACCIONES.INVOICE.FOLIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFOLIO(String FOLIO) {
        this.FOLIO = FOLIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.FECHA
     *
     * @return the value of M_INTERACCIONES.INVOICE.FECHA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFECHA() {
        return FECHA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.FECHA
     *
     * @param FECHA the value for M_INTERACCIONES.INVOICE.FECHA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFECHA(Date FECHA) {
        this.FECHA = FECHA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.NO_APROBACION
     *
     * @return the value of M_INTERACCIONES.INVOICE.NO_APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getNO_APROBACION() {
        return NO_APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.NO_APROBACION
     *
     * @param NO_APROBACION the value for M_INTERACCIONES.INVOICE.NO_APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNO_APROBACION(BigDecimal NO_APROBACION) {
        this.NO_APROBACION = NO_APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.STATUS_DOC
     *
     * @return the value of M_INTERACCIONES.INVOICE.STATUS_DOC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getSTATUS_DOC() {
        return STATUS_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.STATUS_DOC
     *
     * @param STATUS_DOC the value for M_INTERACCIONES.INVOICE.STATUS_DOC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSTATUS_DOC(String STATUS_DOC) {
        this.STATUS_DOC = STATUS_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.HORA
     *
     * @return the value of M_INTERACCIONES.INVOICE.HORA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getHORA() {
        return HORA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.HORA
     *
     * @param HORA the value for M_INTERACCIONES.INVOICE.HORA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setHORA(String HORA) {
        this.HORA = HORA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.TASA_IMPUESTO
     *
     * @return the value of M_INTERACCIONES.INVOICE.TASA_IMPUESTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getTASA_IMPUESTO() {
        return TASA_IMPUESTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.TASA_IMPUESTO
     *
     * @param TASA_IMPUESTO the value for M_INTERACCIONES.INVOICE.TASA_IMPUESTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTASA_IMPUESTO(BigDecimal TASA_IMPUESTO) {
        this.TASA_IMPUESTO = TASA_IMPUESTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.APROBACION
     *
     * @return the value of M_INTERACCIONES.INVOICE.APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getAPROBACION() {
        return APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.APROBACION
     *
     * @param APROBACION the value for M_INTERACCIONES.INVOICE.APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setAPROBACION(BigDecimal APROBACION) {
        this.APROBACION = APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.RFC
     *
     * @return the value of M_INTERACCIONES.INVOICE.RFC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getRFC() {
        return RFC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.RFC
     *
     * @param RFC the value for M_INTERACCIONES.INVOICE.RFC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setRFC(String RFC) {
        this.RFC = RFC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.SERIE_ERP
     *
     * @return the value of M_INTERACCIONES.INVOICE.SERIE_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getSERIE_ERP() {
        return SERIE_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.SERIE_ERP
     *
     * @param SERIE_ERP the value for M_INTERACCIONES.INVOICE.SERIE_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSERIE_ERP(String SERIE_ERP) {
        this.SERIE_ERP = SERIE_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.FOLIO_ERP
     *
     * @return the value of M_INTERACCIONES.INVOICE.FOLIO_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getFOLIO_ERP() {
        return FOLIO_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.FOLIO_ERP
     *
     * @param FOLIO_ERP the value for M_INTERACCIONES.INVOICE.FOLIO_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFOLIO_ERP(String FOLIO_ERP) {
        this.FOLIO_ERP = FOLIO_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.TOTALML
     *
     * @return the value of M_INTERACCIONES.INVOICE.TOTALML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getTOTALML() {
        return TOTALML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.TOTALML
     *
     * @param TOTALML the value for M_INTERACCIONES.INVOICE.TOTALML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTOTALML(Double TOTALML) {
        this.TOTALML = TOTALML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.TIPO_DOCUMENTO
     *
     * @return the value of M_INTERACCIONES.INVOICE.TIPO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getTIPO_DOCUMENTO() {
        return TIPO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.TIPO_DOCUMENTO
     *
     * @param TIPO_DOCUMENTO the value for M_INTERACCIONES.INVOICE.TIPO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTIPO_DOCUMENTO(String TIPO_DOCUMENTO) {
        this.TIPO_DOCUMENTO = TIPO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.NUMERO_CLIENTE
     *
     * @return the value of M_INTERACCIONES.INVOICE.NUMERO_CLIENTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getNUMERO_CLIENTE() {
        return NUMERO_CLIENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.NUMERO_CLIENTE
     *
     * @param NUMERO_CLIENTE the value for M_INTERACCIONES.INVOICE.NUMERO_CLIENTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNUMERO_CLIENTE(String NUMERO_CLIENTE) {
        this.NUMERO_CLIENTE = NUMERO_CLIENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.MONEDA_DOC
     *
     * @return the value of M_INTERACCIONES.INVOICE.MONEDA_DOC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getMONEDA_DOC() {
        return MONEDA_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.MONEDA_DOC
     *
     * @param MONEDA_DOC the value for M_INTERACCIONES.INVOICE.MONEDA_DOC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setMONEDA_DOC(String MONEDA_DOC) {
        this.MONEDA_DOC = MONEDA_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.FECHA_CANCELACION
     *
     * @return the value of M_INTERACCIONES.INVOICE.FECHA_CANCELACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFECHA_CANCELACION() {
        return FECHA_CANCELACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.FECHA_CANCELACION
     *
     * @param FECHA_CANCELACION the value for M_INTERACCIONES.INVOICE.FECHA_CANCELACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFECHA_CANCELACION(Date FECHA_CANCELACION) {
        this.FECHA_CANCELACION = FECHA_CANCELACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.STATUS
     *
     * @return the value of M_INTERACCIONES.INVOICE.STATUS
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.STATUS
     *
     * @param STATUS the value for M_INTERACCIONES.INVOICE.STATUS
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSTATUS(BigDecimal STATUS) {
        this.STATUS = STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.STATUS_ENVIOI
     *
     * @return the value of M_INTERACCIONES.INVOICE.STATUS_ENVIOI
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getSTATUS_ENVIOI() {
        return STATUS_ENVIOI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.STATUS_ENVIOI
     *
     * @param STATUS_ENVIOI the value for M_INTERACCIONES.INVOICE.STATUS_ENVIOI
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSTATUS_ENVIOI(BigDecimal STATUS_ENVIOI) {
        this.STATUS_ENVIOI = STATUS_ENVIOI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.STATUS_ENVIOM
     *
     * @return the value of M_INTERACCIONES.INVOICE.STATUS_ENVIOM
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getSTATUS_ENVIOM() {
        return STATUS_ENVIOM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.STATUS_ENVIOM
     *
     * @param STATUS_ENVIOM the value for M_INTERACCIONES.INVOICE.STATUS_ENVIOM
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSTATUS_ENVIOM(BigDecimal STATUS_ENVIOM) {
        this.STATUS_ENVIOM = STATUS_ENVIOM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.STATUS_ENVIOF
     *
     * @return the value of M_INTERACCIONES.INVOICE.STATUS_ENVIOF
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getSTATUS_ENVIOF() {
        return STATUS_ENVIOF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.STATUS_ENVIOF
     *
     * @param STATUS_ENVIOF the value for M_INTERACCIONES.INVOICE.STATUS_ENVIOF
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSTATUS_ENVIOF(BigDecimal STATUS_ENVIOF) {
        this.STATUS_ENVIOF = STATUS_ENVIOF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.DESCRIPCION_PRODUCTO
     *
     * @return the value of M_INTERACCIONES.INVOICE.DESCRIPCION_PRODUCTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getDESCRIPCION_PRODUCTO() {
        return DESCRIPCION_PRODUCTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.DESCRIPCION_PRODUCTO
     *
     * @param DESCRIPCION_PRODUCTO the value for M_INTERACCIONES.INVOICE.DESCRIPCION_PRODUCTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDESCRIPCION_PRODUCTO(String DESCRIPCION_PRODUCTO) {
        this.DESCRIPCION_PRODUCTO = DESCRIPCION_PRODUCTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.VTIPO_DOCUMENTO
     *
     * @return the value of M_INTERACCIONES.INVOICE.VTIPO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getVTIPO_DOCUMENTO() {
        return VTIPO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.VTIPO_DOCUMENTO
     *
     * @param VTIPO_DOCUMENTO the value for M_INTERACCIONES.INVOICE.VTIPO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setVTIPO_DOCUMENTO(String VTIPO_DOCUMENTO) {
        this.VTIPO_DOCUMENTO = VTIPO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.NNUMERO_PEDIDO
     *
     * @return the value of M_INTERACCIONES.INVOICE.NNUMERO_PEDIDO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getNNUMERO_PEDIDO() {
        return NNUMERO_PEDIDO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.NNUMERO_PEDIDO
     *
     * @param NNUMERO_PEDIDO the value for M_INTERACCIONES.INVOICE.NNUMERO_PEDIDO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNNUMERO_PEDIDO(BigDecimal NNUMERO_PEDIDO) {
        this.NNUMERO_PEDIDO = NNUMERO_PEDIDO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.TIPO_CAMBIO
     *
     * @return the value of M_INTERACCIONES.INVOICE.TIPO_CAMBIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getTIPO_CAMBIO() {
        return TIPO_CAMBIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.TIPO_CAMBIO
     *
     * @param TIPO_CAMBIO the value for M_INTERACCIONES.INVOICE.TIPO_CAMBIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTIPO_CAMBIO(Double TIPO_CAMBIO) {
        this.TIPO_CAMBIO = TIPO_CAMBIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.STATUS_PRINT
     *
     * @return the value of M_INTERACCIONES.INVOICE.STATUS_PRINT
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getSTATUS_PRINT() {
        return STATUS_PRINT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.STATUS_PRINT
     *
     * @param STATUS_PRINT the value for M_INTERACCIONES.INVOICE.STATUS_PRINT
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSTATUS_PRINT(BigDecimal STATUS_PRINT) {
        this.STATUS_PRINT = STATUS_PRINT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.ORIGEN
     *
     * @return the value of M_INTERACCIONES.INVOICE.ORIGEN
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public BigDecimal getORIGEN() {
        return ORIGEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.ORIGEN
     *
     * @param ORIGEN the value for M_INTERACCIONES.INVOICE.ORIGEN
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setORIGEN(BigDecimal ORIGEN) {
        this.ORIGEN = ORIGEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.PLANTILLA
     *
     * @return the value of M_INTERACCIONES.INVOICE.PLANTILLA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPLANTILLA() {
        return PLANTILLA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.PLANTILLA
     *
     * @param PLANTILLA the value for M_INTERACCIONES.INVOICE.PLANTILLA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPLANTILLA(String PLANTILLA) {
        this.PLANTILLA = PLANTILLA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.POLIZA
     *
     * @return the value of M_INTERACCIONES.INVOICE.POLIZA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPOLIZA() {
        return POLIZA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.POLIZA
     *
     * @param POLIZA the value for M_INTERACCIONES.INVOICE.POLIZA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPOLIZA(String POLIZA) {
        this.POLIZA = POLIZA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.ID_DOCUMENTO
     *
     * @return the value of M_INTERACCIONES.INVOICE.ID_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getID_DOCUMENTO() {
        return ID_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.ID_DOCUMENTO
     *
     * @param ID_DOCUMENTO the value for M_INTERACCIONES.INVOICE.ID_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setID_DOCUMENTO(String ID_DOCUMENTO) {
        this.ID_DOCUMENTO = ID_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.INVOICE.FECHA_CONSULTA
     *
     * @return the value of M_INTERACCIONES.INVOICE.FECHA_CONSULTA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFECHA_CONSULTA() {
        return FECHA_CONSULTA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.INVOICE.FECHA_CONSULTA
     *
     * @param FECHA_CONSULTA the value for M_INTERACCIONES.INVOICE.FECHA_CONSULTA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFECHA_CONSULTA(Date FECHA_CONSULTA) {
        this.FECHA_CONSULTA = FECHA_CONSULTA;
    }
}