package mx.com.ebs.inter.data.model.facbanco;

import java.util.Date;

public class MCfd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.ANO_APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long ANO_APROBACION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.ESTADO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long ESTADO_DOCUMENTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.ESTATUS_DOC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long ESTATUS_DOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.ESTATUS_ENT
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long ESTATUS_ENT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.ESTATUS_FTP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long ESTATUS_FTP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.ESTATUS_MAIL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long ESTATUS_MAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.ESTATUS_PRINT
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long ESTATUS_PRINT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.FACTURA_ORIGEN
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String FACTURA_ORIGEN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.FECHA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FECHA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.FECHA_CANCELACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FECHA_CANCELACION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.FECHA_ORIGEN
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FECHA_ORIGEN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.FOLIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double FOLIO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.FOLIO_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String FOLIO_ERP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.FORMA_PAGO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long FORMA_PAGO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.IVA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double IVA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.IVA_ML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double IVA_ML;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.MONEDA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String MONEDA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.NO_APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long NO_APROBACION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.NUMERO_CLIENTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String NUMERO_CLIENTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.NUMERO_FACTURA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String NUMERO_FACTURA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.PARCIALIDAD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long PARCIALIDAD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.RAZON_SOCIAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String RAZON_SOCIAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.RFC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String RFC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.SERIE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String SERIE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.SERIE_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String SERIE_ERP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.SISTEMA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long SISTEMA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.SUBTOTAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double SUBTOTAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.SUBTOTAL_ML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double SUBTOTAL_ML;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.SUCURSAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long SUCURSAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.TABLA_XML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String TABLA_XML;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.TIPO_CAMBIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double TIPO_CAMBIO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.TIPO_COMPROBANTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long TIPO_COMPROBANTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.TIPO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String TIPO_DOCUMENTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.TIPO_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long TIPO_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.TOTAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double TOTAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.TOTAL_ML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double TOTAL_ML;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.UNO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String UNO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.UUID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String UUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.EMPRESA_ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long EMPRESA_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_CFD.PLANTILLA_ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long PLANTILLA_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.ID
     *
     * @return the value of M_INTERACCIONES.M_CFD.ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.ID
     *
     * @param ID the value for M_INTERACCIONES.M_CFD.ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.ANO_APROBACION
     *
     * @return the value of M_INTERACCIONES.M_CFD.ANO_APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getANO_APROBACION() {
        return ANO_APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.ANO_APROBACION
     *
     * @param ANO_APROBACION the value for M_INTERACCIONES.M_CFD.ANO_APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setANO_APROBACION(Long ANO_APROBACION) {
        this.ANO_APROBACION = ANO_APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.ESTADO_DOCUMENTO
     *
     * @return the value of M_INTERACCIONES.M_CFD.ESTADO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getESTADO_DOCUMENTO() {
        return ESTADO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.ESTADO_DOCUMENTO
     *
     * @param ESTADO_DOCUMENTO the value for M_INTERACCIONES.M_CFD.ESTADO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setESTADO_DOCUMENTO(Long ESTADO_DOCUMENTO) {
        this.ESTADO_DOCUMENTO = ESTADO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_DOC
     *
     * @return the value of M_INTERACCIONES.M_CFD.ESTATUS_DOC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getESTATUS_DOC() {
        return ESTATUS_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_DOC
     *
     * @param ESTATUS_DOC the value for M_INTERACCIONES.M_CFD.ESTATUS_DOC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setESTATUS_DOC(Long ESTATUS_DOC) {
        this.ESTATUS_DOC = ESTATUS_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_ENT
     *
     * @return the value of M_INTERACCIONES.M_CFD.ESTATUS_ENT
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getESTATUS_ENT() {
        return ESTATUS_ENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_ENT
     *
     * @param ESTATUS_ENT the value for M_INTERACCIONES.M_CFD.ESTATUS_ENT
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setESTATUS_ENT(Long ESTATUS_ENT) {
        this.ESTATUS_ENT = ESTATUS_ENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_FTP
     *
     * @return the value of M_INTERACCIONES.M_CFD.ESTATUS_FTP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getESTATUS_FTP() {
        return ESTATUS_FTP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_FTP
     *
     * @param ESTATUS_FTP the value for M_INTERACCIONES.M_CFD.ESTATUS_FTP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setESTATUS_FTP(Long ESTATUS_FTP) {
        this.ESTATUS_FTP = ESTATUS_FTP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_MAIL
     *
     * @return the value of M_INTERACCIONES.M_CFD.ESTATUS_MAIL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getESTATUS_MAIL() {
        return ESTATUS_MAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_MAIL
     *
     * @param ESTATUS_MAIL the value for M_INTERACCIONES.M_CFD.ESTATUS_MAIL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setESTATUS_MAIL(Long ESTATUS_MAIL) {
        this.ESTATUS_MAIL = ESTATUS_MAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_PRINT
     *
     * @return the value of M_INTERACCIONES.M_CFD.ESTATUS_PRINT
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getESTATUS_PRINT() {
        return ESTATUS_PRINT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.ESTATUS_PRINT
     *
     * @param ESTATUS_PRINT the value for M_INTERACCIONES.M_CFD.ESTATUS_PRINT
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setESTATUS_PRINT(Long ESTATUS_PRINT) {
        this.ESTATUS_PRINT = ESTATUS_PRINT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.FACTURA_ORIGEN
     *
     * @return the value of M_INTERACCIONES.M_CFD.FACTURA_ORIGEN
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getFACTURA_ORIGEN() {
        return FACTURA_ORIGEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.FACTURA_ORIGEN
     *
     * @param FACTURA_ORIGEN the value for M_INTERACCIONES.M_CFD.FACTURA_ORIGEN
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFACTURA_ORIGEN(String FACTURA_ORIGEN) {
        this.FACTURA_ORIGEN = FACTURA_ORIGEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.FECHA
     *
     * @return the value of M_INTERACCIONES.M_CFD.FECHA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFECHA() {
        return FECHA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.FECHA
     *
     * @param FECHA the value for M_INTERACCIONES.M_CFD.FECHA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFECHA(Date FECHA) {
        this.FECHA = FECHA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.FECHA_CANCELACION
     *
     * @return the value of M_INTERACCIONES.M_CFD.FECHA_CANCELACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFECHA_CANCELACION() {
        return FECHA_CANCELACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.FECHA_CANCELACION
     *
     * @param FECHA_CANCELACION the value for M_INTERACCIONES.M_CFD.FECHA_CANCELACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFECHA_CANCELACION(Date FECHA_CANCELACION) {
        this.FECHA_CANCELACION = FECHA_CANCELACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.FECHA_ORIGEN
     *
     * @return the value of M_INTERACCIONES.M_CFD.FECHA_ORIGEN
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFECHA_ORIGEN() {
        return FECHA_ORIGEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.FECHA_ORIGEN
     *
     * @param FECHA_ORIGEN the value for M_INTERACCIONES.M_CFD.FECHA_ORIGEN
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFECHA_ORIGEN(Date FECHA_ORIGEN) {
        this.FECHA_ORIGEN = FECHA_ORIGEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.FOLIO
     *
     * @return the value of M_INTERACCIONES.M_CFD.FOLIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getFOLIO() {
        return FOLIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.FOLIO
     *
     * @param FOLIO the value for M_INTERACCIONES.M_CFD.FOLIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFOLIO(Double FOLIO) {
        this.FOLIO = FOLIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.FOLIO_ERP
     *
     * @return the value of M_INTERACCIONES.M_CFD.FOLIO_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getFOLIO_ERP() {
        return FOLIO_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.FOLIO_ERP
     *
     * @param FOLIO_ERP the value for M_INTERACCIONES.M_CFD.FOLIO_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFOLIO_ERP(String FOLIO_ERP) {
        this.FOLIO_ERP = FOLIO_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.FORMA_PAGO
     *
     * @return the value of M_INTERACCIONES.M_CFD.FORMA_PAGO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getFORMA_PAGO() {
        return FORMA_PAGO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.FORMA_PAGO
     *
     * @param FORMA_PAGO the value for M_INTERACCIONES.M_CFD.FORMA_PAGO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFORMA_PAGO(Long FORMA_PAGO) {
        this.FORMA_PAGO = FORMA_PAGO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.IVA
     *
     * @return the value of M_INTERACCIONES.M_CFD.IVA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getIVA() {
        return IVA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.IVA
     *
     * @param IVA the value for M_INTERACCIONES.M_CFD.IVA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setIVA(Double IVA) {
        this.IVA = IVA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.IVA_ML
     *
     * @return the value of M_INTERACCIONES.M_CFD.IVA_ML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getIVA_ML() {
        return IVA_ML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.IVA_ML
     *
     * @param IVA_ML the value for M_INTERACCIONES.M_CFD.IVA_ML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setIVA_ML(Double IVA_ML) {
        this.IVA_ML = IVA_ML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.MONEDA
     *
     * @return the value of M_INTERACCIONES.M_CFD.MONEDA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getMONEDA() {
        return MONEDA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.MONEDA
     *
     * @param MONEDA the value for M_INTERACCIONES.M_CFD.MONEDA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setMONEDA(String MONEDA) {
        this.MONEDA = MONEDA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.NO_APROBACION
     *
     * @return the value of M_INTERACCIONES.M_CFD.NO_APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getNO_APROBACION() {
        return NO_APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.NO_APROBACION
     *
     * @param NO_APROBACION the value for M_INTERACCIONES.M_CFD.NO_APROBACION
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNO_APROBACION(Long NO_APROBACION) {
        this.NO_APROBACION = NO_APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.NUMERO_CLIENTE
     *
     * @return the value of M_INTERACCIONES.M_CFD.NUMERO_CLIENTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getNUMERO_CLIENTE() {
        return NUMERO_CLIENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.NUMERO_CLIENTE
     *
     * @param NUMERO_CLIENTE the value for M_INTERACCIONES.M_CFD.NUMERO_CLIENTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNUMERO_CLIENTE(String NUMERO_CLIENTE) {
        this.NUMERO_CLIENTE = NUMERO_CLIENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.NUMERO_FACTURA
     *
     * @return the value of M_INTERACCIONES.M_CFD.NUMERO_FACTURA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getNUMERO_FACTURA() {
        return NUMERO_FACTURA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.NUMERO_FACTURA
     *
     * @param NUMERO_FACTURA the value for M_INTERACCIONES.M_CFD.NUMERO_FACTURA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setNUMERO_FACTURA(String NUMERO_FACTURA) {
        this.NUMERO_FACTURA = NUMERO_FACTURA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.PARCIALIDAD
     *
     * @return the value of M_INTERACCIONES.M_CFD.PARCIALIDAD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getPARCIALIDAD() {
        return PARCIALIDAD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.PARCIALIDAD
     *
     * @param PARCIALIDAD the value for M_INTERACCIONES.M_CFD.PARCIALIDAD
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARCIALIDAD(Long PARCIALIDAD) {
        this.PARCIALIDAD = PARCIALIDAD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.RAZON_SOCIAL
     *
     * @return the value of M_INTERACCIONES.M_CFD.RAZON_SOCIAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getRAZON_SOCIAL() {
        return RAZON_SOCIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.RAZON_SOCIAL
     *
     * @param RAZON_SOCIAL the value for M_INTERACCIONES.M_CFD.RAZON_SOCIAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setRAZON_SOCIAL(String RAZON_SOCIAL) {
        this.RAZON_SOCIAL = RAZON_SOCIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.RFC
     *
     * @return the value of M_INTERACCIONES.M_CFD.RFC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getRFC() {
        return RFC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.RFC
     *
     * @param RFC the value for M_INTERACCIONES.M_CFD.RFC
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setRFC(String RFC) {
        this.RFC = RFC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.SERIE
     *
     * @return the value of M_INTERACCIONES.M_CFD.SERIE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getSERIE() {
        return SERIE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.SERIE
     *
     * @param SERIE the value for M_INTERACCIONES.M_CFD.SERIE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSERIE(String SERIE) {
        this.SERIE = SERIE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.SERIE_ERP
     *
     * @return the value of M_INTERACCIONES.M_CFD.SERIE_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getSERIE_ERP() {
        return SERIE_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.SERIE_ERP
     *
     * @param SERIE_ERP the value for M_INTERACCIONES.M_CFD.SERIE_ERP
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSERIE_ERP(String SERIE_ERP) {
        this.SERIE_ERP = SERIE_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.SISTEMA
     *
     * @return the value of M_INTERACCIONES.M_CFD.SISTEMA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getSISTEMA() {
        return SISTEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.SISTEMA
     *
     * @param SISTEMA the value for M_INTERACCIONES.M_CFD.SISTEMA
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSISTEMA(Long SISTEMA) {
        this.SISTEMA = SISTEMA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.SUBTOTAL
     *
     * @return the value of M_INTERACCIONES.M_CFD.SUBTOTAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getSUBTOTAL() {
        return SUBTOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.SUBTOTAL
     *
     * @param SUBTOTAL the value for M_INTERACCIONES.M_CFD.SUBTOTAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSUBTOTAL(Double SUBTOTAL) {
        this.SUBTOTAL = SUBTOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.SUBTOTAL_ML
     *
     * @return the value of M_INTERACCIONES.M_CFD.SUBTOTAL_ML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getSUBTOTAL_ML() {
        return SUBTOTAL_ML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.SUBTOTAL_ML
     *
     * @param SUBTOTAL_ML the value for M_INTERACCIONES.M_CFD.SUBTOTAL_ML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSUBTOTAL_ML(Double SUBTOTAL_ML) {
        this.SUBTOTAL_ML = SUBTOTAL_ML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.SUCURSAL
     *
     * @return the value of M_INTERACCIONES.M_CFD.SUCURSAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getSUCURSAL() {
        return SUCURSAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.SUCURSAL
     *
     * @param SUCURSAL the value for M_INTERACCIONES.M_CFD.SUCURSAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setSUCURSAL(Long SUCURSAL) {
        this.SUCURSAL = SUCURSAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.TABLA_XML
     *
     * @return the value of M_INTERACCIONES.M_CFD.TABLA_XML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getTABLA_XML() {
        return TABLA_XML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.TABLA_XML
     *
     * @param TABLA_XML the value for M_INTERACCIONES.M_CFD.TABLA_XML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTABLA_XML(String TABLA_XML) {
        this.TABLA_XML = TABLA_XML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.TIPO_CAMBIO
     *
     * @return the value of M_INTERACCIONES.M_CFD.TIPO_CAMBIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getTIPO_CAMBIO() {
        return TIPO_CAMBIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.TIPO_CAMBIO
     *
     * @param TIPO_CAMBIO the value for M_INTERACCIONES.M_CFD.TIPO_CAMBIO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTIPO_CAMBIO(Double TIPO_CAMBIO) {
        this.TIPO_CAMBIO = TIPO_CAMBIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.TIPO_COMPROBANTE
     *
     * @return the value of M_INTERACCIONES.M_CFD.TIPO_COMPROBANTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getTIPO_COMPROBANTE() {
        return TIPO_COMPROBANTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.TIPO_COMPROBANTE
     *
     * @param TIPO_COMPROBANTE the value for M_INTERACCIONES.M_CFD.TIPO_COMPROBANTE
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTIPO_COMPROBANTE(Long TIPO_COMPROBANTE) {
        this.TIPO_COMPROBANTE = TIPO_COMPROBANTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.TIPO_DOCUMENTO
     *
     * @return the value of M_INTERACCIONES.M_CFD.TIPO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getTIPO_DOCUMENTO() {
        return TIPO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.TIPO_DOCUMENTO
     *
     * @param TIPO_DOCUMENTO the value for M_INTERACCIONES.M_CFD.TIPO_DOCUMENTO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTIPO_DOCUMENTO(String TIPO_DOCUMENTO) {
        this.TIPO_DOCUMENTO = TIPO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.TIPO_FISCAL
     *
     * @return the value of M_INTERACCIONES.M_CFD.TIPO_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getTIPO_FISCAL() {
        return TIPO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.TIPO_FISCAL
     *
     * @param TIPO_FISCAL the value for M_INTERACCIONES.M_CFD.TIPO_FISCAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTIPO_FISCAL(Long TIPO_FISCAL) {
        this.TIPO_FISCAL = TIPO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.TOTAL
     *
     * @return the value of M_INTERACCIONES.M_CFD.TOTAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getTOTAL() {
        return TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.TOTAL
     *
     * @param TOTAL the value for M_INTERACCIONES.M_CFD.TOTAL
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTOTAL(Double TOTAL) {
        this.TOTAL = TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.TOTAL_ML
     *
     * @return the value of M_INTERACCIONES.M_CFD.TOTAL_ML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getTOTAL_ML() {
        return TOTAL_ML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.TOTAL_ML
     *
     * @param TOTAL_ML the value for M_INTERACCIONES.M_CFD.TOTAL_ML
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setTOTAL_ML(Double TOTAL_ML) {
        this.TOTAL_ML = TOTAL_ML;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.UNO
     *
     * @return the value of M_INTERACCIONES.M_CFD.UNO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getUNO() {
        return UNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.UNO
     *
     * @param UNO the value for M_INTERACCIONES.M_CFD.UNO
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setUNO(String UNO) {
        this.UNO = UNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.UUID
     *
     * @return the value of M_INTERACCIONES.M_CFD.UUID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getUUID() {
        return UUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.UUID
     *
     * @param UUID the value for M_INTERACCIONES.M_CFD.UUID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setUUID(String UUID) {
        this.UUID = UUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.EMPRESA_ID
     *
     * @return the value of M_INTERACCIONES.M_CFD.EMPRESA_ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getEMPRESA_ID() {
        return EMPRESA_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.EMPRESA_ID
     *
     * @param EMPRESA_ID the value for M_INTERACCIONES.M_CFD.EMPRESA_ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setEMPRESA_ID(Long EMPRESA_ID) {
        this.EMPRESA_ID = EMPRESA_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_CFD.PLANTILLA_ID
     *
     * @return the value of M_INTERACCIONES.M_CFD.PLANTILLA_ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getPLANTILLA_ID() {
        return PLANTILLA_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_CFD.PLANTILLA_ID
     *
     * @param PLANTILLA_ID the value for M_INTERACCIONES.M_CFD.PLANTILLA_ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPLANTILLA_ID(Long PLANTILLA_ID) {
        this.PLANTILLA_ID = PLANTILLA_ID;
    }

    private MOtro mOtro;

    public MOtro getmOtro() {
        return mOtro;
    }

    public void setmOtro(MOtro mOtro) {
        this.mOtro = mOtro;
    }
}
