package mx.com.ebs.inter.data.model.facbanco;

public class MEmpresa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_EMPRESA.ID
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_EMPRESA.RAZON_SOCIAL
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    private String RAZON_SOCIAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_EMPRESA.RFC_ORIGEN
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    private String RFC_ORIGEN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_EMPRESA.DIRECCION_ID
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    private Long DIRECCION_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_EMPRESA.LICENCIA
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    private byte[] LICENCIA;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_EMPRESA.ID
     *
     * @return the value of M_INTERACCIONES.M_EMPRESA.ID
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_EMPRESA.ID
     *
     * @param ID the value for M_INTERACCIONES.M_EMPRESA.ID
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_EMPRESA.RAZON_SOCIAL
     *
     * @return the value of M_INTERACCIONES.M_EMPRESA.RAZON_SOCIAL
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public String getRAZON_SOCIAL() {
        return RAZON_SOCIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_EMPRESA.RAZON_SOCIAL
     *
     * @param RAZON_SOCIAL the value for M_INTERACCIONES.M_EMPRESA.RAZON_SOCIAL
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public void setRAZON_SOCIAL(String RAZON_SOCIAL) {
        this.RAZON_SOCIAL = RAZON_SOCIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_EMPRESA.RFC_ORIGEN
     *
     * @return the value of M_INTERACCIONES.M_EMPRESA.RFC_ORIGEN
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public String getRFC_ORIGEN() {
        return RFC_ORIGEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_EMPRESA.RFC_ORIGEN
     *
     * @param RFC_ORIGEN the value for M_INTERACCIONES.M_EMPRESA.RFC_ORIGEN
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public void setRFC_ORIGEN(String RFC_ORIGEN) {
        this.RFC_ORIGEN = RFC_ORIGEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_EMPRESA.DIRECCION_ID
     *
     * @return the value of M_INTERACCIONES.M_EMPRESA.DIRECCION_ID
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public Long getDIRECCION_ID() {
        return DIRECCION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_EMPRESA.DIRECCION_ID
     *
     * @param DIRECCION_ID the value for M_INTERACCIONES.M_EMPRESA.DIRECCION_ID
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public void setDIRECCION_ID(Long DIRECCION_ID) {
        this.DIRECCION_ID = DIRECCION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_EMPRESA.LICENCIA
     *
     * @return the value of M_INTERACCIONES.M_EMPRESA.LICENCIA
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public byte[] getLICENCIA() {
        return LICENCIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_EMPRESA.LICENCIA
     *
     * @param LICENCIA the value for M_INTERACCIONES.M_EMPRESA.LICENCIA
     *
     * @mbggenerated Wed Aug 12 17:19:54 CDT 2015
     */
    public void setLICENCIA(byte[] LICENCIA) {
        this.LICENCIA = LICENCIA;
    }
}