package mx.com.ebs.inter.data.model.facbanco;

import java.util.Date;

public class MOtro {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM0
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM10
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM11
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM12
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM13
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM14
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM2
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM3
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM4
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM5
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM6
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM7
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM8
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.DPARAM9
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Double DPARAM9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM0
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM2
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM3
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM4
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM5
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM6
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM7
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM8
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.FPARAM9
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Date FPARAM9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM0
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM10
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM11
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM12
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM13
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM14
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM15
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM16
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM17
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM18
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM19
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM2
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM3
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM4
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM5
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM6
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM7
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM8
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.PARAM9
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private String PARAM9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_INTERACCIONES.M_OTRO.CFD_ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    private Long CFD_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.ID
     *
     * @return the value of M_INTERACCIONES.M_OTRO.ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.ID
     *
     * @param ID the value for M_INTERACCIONES.M_OTRO.ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM0
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM0
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM0() {
        return DPARAM0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM0
     *
     * @param DPARAM0 the value for M_INTERACCIONES.M_OTRO.DPARAM0
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM0(Double DPARAM0) {
        this.DPARAM0 = DPARAM0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM1
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM1() {
        return DPARAM1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM1
     *
     * @param DPARAM1 the value for M_INTERACCIONES.M_OTRO.DPARAM1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM1(Double DPARAM1) {
        this.DPARAM1 = DPARAM1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM10
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM10
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM10() {
        return DPARAM10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM10
     *
     * @param DPARAM10 the value for M_INTERACCIONES.M_OTRO.DPARAM10
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM10(Double DPARAM10) {
        this.DPARAM10 = DPARAM10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM11
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM11
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM11() {
        return DPARAM11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM11
     *
     * @param DPARAM11 the value for M_INTERACCIONES.M_OTRO.DPARAM11
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM11(Double DPARAM11) {
        this.DPARAM11 = DPARAM11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM12
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM12
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM12() {
        return DPARAM12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM12
     *
     * @param DPARAM12 the value for M_INTERACCIONES.M_OTRO.DPARAM12
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM12(Double DPARAM12) {
        this.DPARAM12 = DPARAM12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM13
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM13
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM13() {
        return DPARAM13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM13
     *
     * @param DPARAM13 the value for M_INTERACCIONES.M_OTRO.DPARAM13
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM13(Double DPARAM13) {
        this.DPARAM13 = DPARAM13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM14
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM14
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM14() {
        return DPARAM14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM14
     *
     * @param DPARAM14 the value for M_INTERACCIONES.M_OTRO.DPARAM14
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM14(Double DPARAM14) {
        this.DPARAM14 = DPARAM14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM2
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM2
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM2() {
        return DPARAM2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM2
     *
     * @param DPARAM2 the value for M_INTERACCIONES.M_OTRO.DPARAM2
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM2(Double DPARAM2) {
        this.DPARAM2 = DPARAM2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM3
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM3
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM3() {
        return DPARAM3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM3
     *
     * @param DPARAM3 the value for M_INTERACCIONES.M_OTRO.DPARAM3
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM3(Double DPARAM3) {
        this.DPARAM3 = DPARAM3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM4
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM4
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM4() {
        return DPARAM4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM4
     *
     * @param DPARAM4 the value for M_INTERACCIONES.M_OTRO.DPARAM4
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM4(Double DPARAM4) {
        this.DPARAM4 = DPARAM4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM5
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM5
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM5() {
        return DPARAM5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM5
     *
     * @param DPARAM5 the value for M_INTERACCIONES.M_OTRO.DPARAM5
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM5(Double DPARAM5) {
        this.DPARAM5 = DPARAM5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM6
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM6
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM6() {
        return DPARAM6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM6
     *
     * @param DPARAM6 the value for M_INTERACCIONES.M_OTRO.DPARAM6
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM6(Double DPARAM6) {
        this.DPARAM6 = DPARAM6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM7
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM7
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM7() {
        return DPARAM7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM7
     *
     * @param DPARAM7 the value for M_INTERACCIONES.M_OTRO.DPARAM7
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM7(Double DPARAM7) {
        this.DPARAM7 = DPARAM7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM8
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM8
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM8() {
        return DPARAM8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM8
     *
     * @param DPARAM8 the value for M_INTERACCIONES.M_OTRO.DPARAM8
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM8(Double DPARAM8) {
        this.DPARAM8 = DPARAM8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.DPARAM9
     *
     * @return the value of M_INTERACCIONES.M_OTRO.DPARAM9
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Double getDPARAM9() {
        return DPARAM9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.DPARAM9
     *
     * @param DPARAM9 the value for M_INTERACCIONES.M_OTRO.DPARAM9
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setDPARAM9(Double DPARAM9) {
        this.DPARAM9 = DPARAM9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM0
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM0
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM0() {
        return FPARAM0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM0
     *
     * @param FPARAM0 the value for M_INTERACCIONES.M_OTRO.FPARAM0
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM0(Date FPARAM0) {
        this.FPARAM0 = FPARAM0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM1
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM1() {
        return FPARAM1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM1
     *
     * @param FPARAM1 the value for M_INTERACCIONES.M_OTRO.FPARAM1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM1(Date FPARAM1) {
        this.FPARAM1 = FPARAM1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM2
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM2
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM2() {
        return FPARAM2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM2
     *
     * @param FPARAM2 the value for M_INTERACCIONES.M_OTRO.FPARAM2
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM2(Date FPARAM2) {
        this.FPARAM2 = FPARAM2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM3
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM3
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM3() {
        return FPARAM3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM3
     *
     * @param FPARAM3 the value for M_INTERACCIONES.M_OTRO.FPARAM3
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM3(Date FPARAM3) {
        this.FPARAM3 = FPARAM3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM4
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM4
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM4() {
        return FPARAM4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM4
     *
     * @param FPARAM4 the value for M_INTERACCIONES.M_OTRO.FPARAM4
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM4(Date FPARAM4) {
        this.FPARAM4 = FPARAM4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM5
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM5
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM5() {
        return FPARAM5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM5
     *
     * @param FPARAM5 the value for M_INTERACCIONES.M_OTRO.FPARAM5
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM5(Date FPARAM5) {
        this.FPARAM5 = FPARAM5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM6
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM6
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM6() {
        return FPARAM6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM6
     *
     * @param FPARAM6 the value for M_INTERACCIONES.M_OTRO.FPARAM6
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM6(Date FPARAM6) {
        this.FPARAM6 = FPARAM6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM7
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM7
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM7() {
        return FPARAM7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM7
     *
     * @param FPARAM7 the value for M_INTERACCIONES.M_OTRO.FPARAM7
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM7(Date FPARAM7) {
        this.FPARAM7 = FPARAM7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM8
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM8
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM8() {
        return FPARAM8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM8
     *
     * @param FPARAM8 the value for M_INTERACCIONES.M_OTRO.FPARAM8
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM8(Date FPARAM8) {
        this.FPARAM8 = FPARAM8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.FPARAM9
     *
     * @return the value of M_INTERACCIONES.M_OTRO.FPARAM9
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Date getFPARAM9() {
        return FPARAM9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.FPARAM9
     *
     * @param FPARAM9 the value for M_INTERACCIONES.M_OTRO.FPARAM9
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setFPARAM9(Date FPARAM9) {
        this.FPARAM9 = FPARAM9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM0
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM0
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM0() {
        return PARAM0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM0
     *
     * @param PARAM0 the value for M_INTERACCIONES.M_OTRO.PARAM0
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM0(String PARAM0) {
        this.PARAM0 = PARAM0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM1
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM1() {
        return PARAM1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM1
     *
     * @param PARAM1 the value for M_INTERACCIONES.M_OTRO.PARAM1
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM1(String PARAM1) {
        this.PARAM1 = PARAM1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM10
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM10
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM10() {
        return PARAM10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM10
     *
     * @param PARAM10 the value for M_INTERACCIONES.M_OTRO.PARAM10
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM10(String PARAM10) {
        this.PARAM10 = PARAM10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM11
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM11
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM11() {
        return PARAM11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM11
     *
     * @param PARAM11 the value for M_INTERACCIONES.M_OTRO.PARAM11
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM11(String PARAM11) {
        this.PARAM11 = PARAM11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM12
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM12
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM12() {
        return PARAM12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM12
     *
     * @param PARAM12 the value for M_INTERACCIONES.M_OTRO.PARAM12
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM12(String PARAM12) {
        this.PARAM12 = PARAM12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM13
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM13
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM13() {
        return PARAM13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM13
     *
     * @param PARAM13 the value for M_INTERACCIONES.M_OTRO.PARAM13
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM13(String PARAM13) {
        this.PARAM13 = PARAM13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM14
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM14
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM14() {
        return PARAM14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM14
     *
     * @param PARAM14 the value for M_INTERACCIONES.M_OTRO.PARAM14
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM14(String PARAM14) {
        this.PARAM14 = PARAM14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM15
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM15
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM15() {
        return PARAM15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM15
     *
     * @param PARAM15 the value for M_INTERACCIONES.M_OTRO.PARAM15
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM15(String PARAM15) {
        this.PARAM15 = PARAM15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM16
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM16
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM16() {
        return PARAM16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM16
     *
     * @param PARAM16 the value for M_INTERACCIONES.M_OTRO.PARAM16
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM16(String PARAM16) {
        this.PARAM16 = PARAM16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM17
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM17
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM17() {
        return PARAM17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM17
     *
     * @param PARAM17 the value for M_INTERACCIONES.M_OTRO.PARAM17
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM17(String PARAM17) {
        this.PARAM17 = PARAM17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM18
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM18
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM18() {
        return PARAM18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM18
     *
     * @param PARAM18 the value for M_INTERACCIONES.M_OTRO.PARAM18
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM18(String PARAM18) {
        this.PARAM18 = PARAM18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM19
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM19
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM19() {
        return PARAM19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM19
     *
     * @param PARAM19 the value for M_INTERACCIONES.M_OTRO.PARAM19
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM19(String PARAM19) {
        this.PARAM19 = PARAM19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM2
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM2
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM2() {
        return PARAM2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM2
     *
     * @param PARAM2 the value for M_INTERACCIONES.M_OTRO.PARAM2
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM2(String PARAM2) {
        this.PARAM2 = PARAM2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM3
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM3
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM3() {
        return PARAM3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM3
     *
     * @param PARAM3 the value for M_INTERACCIONES.M_OTRO.PARAM3
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM3(String PARAM3) {
        this.PARAM3 = PARAM3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM4
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM4
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM4() {
        return PARAM4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM4
     *
     * @param PARAM4 the value for M_INTERACCIONES.M_OTRO.PARAM4
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM4(String PARAM4) {
        this.PARAM4 = PARAM4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM5
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM5
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM5() {
        return PARAM5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM5
     *
     * @param PARAM5 the value for M_INTERACCIONES.M_OTRO.PARAM5
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM5(String PARAM5) {
        this.PARAM5 = PARAM5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM6
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM6
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM6() {
        return PARAM6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM6
     *
     * @param PARAM6 the value for M_INTERACCIONES.M_OTRO.PARAM6
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM6(String PARAM6) {
        this.PARAM6 = PARAM6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM7
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM7
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM7() {
        return PARAM7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM7
     *
     * @param PARAM7 the value for M_INTERACCIONES.M_OTRO.PARAM7
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM7(String PARAM7) {
        this.PARAM7 = PARAM7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM8
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM8
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM8() {
        return PARAM8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM8
     *
     * @param PARAM8 the value for M_INTERACCIONES.M_OTRO.PARAM8
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM8(String PARAM8) {
        this.PARAM8 = PARAM8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.PARAM9
     *
     * @return the value of M_INTERACCIONES.M_OTRO.PARAM9
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public String getPARAM9() {
        return PARAM9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.PARAM9
     *
     * @param PARAM9 the value for M_INTERACCIONES.M_OTRO.PARAM9
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setPARAM9(String PARAM9) {
        this.PARAM9 = PARAM9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_INTERACCIONES.M_OTRO.CFD_ID
     *
     * @return the value of M_INTERACCIONES.M_OTRO.CFD_ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public Long getCFD_ID() {
        return CFD_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_INTERACCIONES.M_OTRO.CFD_ID
     *
     * @param CFD_ID the value for M_INTERACCIONES.M_OTRO.CFD_ID
     *
     * @mbggenerated Mon Jun 15 01:02:36 CDT 2015
     */
    public void setCFD_ID(Long CFD_ID) {
        this.CFD_ID = CFD_ID;
    }
}