package mx.com.ebs.inter.data.dao.agt;

import java.util.List;

import mx.com.ebs.inter.data.bo.LoginBo;
import mx.com.ebs.inter.data.model.RecAcceso;
import mx.com.ebs.inter.data.model.RecAccesoExample;
import org.apache.ibatis.annotations.Param;

public interface RecAccesoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int countByExample(RecAccesoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int deleteByExample(RecAccesoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int insert(RecAcceso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int insertSelective(RecAcceso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    List<RecAcceso> selectByExample(RecAccesoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int updateByExampleSelective(@Param("record") RecAcceso record, @Param("example") RecAccesoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int updateByExample(@Param("record") RecAcceso record, @Param("example") RecAccesoExample example);

    /**
     * Look for the user specified in order to create a session
     */
    RecAcceso findRecAccesoUserPass( LoginBo loginBo );

    int updateIntentos(@Param("record") RecAcceso record);

    int updateStatus(@Param("ebsUserId") String ebsUserId);

}