package mx.com.ebs.inter.data.model;

import mx.com.ebs.inter.util.Variables;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProcAgtFelEnvioExample extends PaginatedResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public ProcAgtFelEnvioExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        private int resultLimitRows = Variables.DEFAULT_SIZE_RESULT;

        public int getResultLimitRows() {
            return resultLimitRows;
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTimeStamp(String condition, Timestamp value1, Timestamp value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, value1, value2, property);
        }

        public Criteria andANIO_MES_DIAIsNull() {
            addCriterion("ANIO_MES_DIA is null");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIAIsNotNull() {
            addCriterion("ANIO_MES_DIA is not null");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIAEqualTo(Integer value) {
            addCriterion("ANIO_MES_DIA =", value, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIANotEqualTo(Integer value) {
            addCriterion("ANIO_MES_DIA <>", value, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIAGreaterThan(Integer value) {
            addCriterion("ANIO_MES_DIA >", value, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIAGreaterThanOrEqualTo(Integer value) {
            addCriterion("ANIO_MES_DIA >=", value, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIALessThan(Integer value) {
            addCriterion("ANIO_MES_DIA <", value, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIALessThanOrEqualTo(Integer value) {
            addCriterion("ANIO_MES_DIA <=", value, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIAIn(List<Integer> values) {
            addCriterion("ANIO_MES_DIA in", values, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIANotIn(List<Integer> values) {
            addCriterion("ANIO_MES_DIA not in", values, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIABetween(Integer value1, Integer value2) {
            addCriterion("ANIO_MES_DIA between", value1, value2, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANIO_MES_DIANotBetween(Integer value1, Integer value2) {
            addCriterion("ANIO_MES_DIA not between", value1, value2, "ANIO_MES_DIA");
            return (Criteria) this;
        }

        public Criteria andANO_MESIsNull() {
            addCriterion("ANO_MES is null");
            return (Criteria) this;
        }

        public Criteria andANO_MESIsNotNull() {
            addCriterion("ANO_MES is not null");
            return (Criteria) this;
        }

        public Criteria andANO_MESEqualTo(Integer value) {
            addCriterion("ANO_MES =", value, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andANO_MESNotEqualTo(Integer value) {
            addCriterion("ANO_MES <>", value, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andANO_MESGreaterThan(Integer value) {
            addCriterion("ANO_MES >", value, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andANO_MESGreaterThanOrEqualTo(Integer value) {
            addCriterion("ANO_MES >=", value, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andANO_MESLessThan(Integer value) {
            addCriterion("ANO_MES <", value, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andANO_MESLessThanOrEqualTo(Integer value) {
            addCriterion("ANO_MES <=", value, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andANO_MESIn(List<Integer> values) {
            addCriterion("ANO_MES in", values, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andANO_MESNotIn(List<Integer> values) {
            addCriterion("ANO_MES not in", values, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andANO_MESBetween(Integer value1, Integer value2) {
            addCriterion("ANO_MES between", value1, value2, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andANO_MESNotBetween(Integer value1, Integer value2) {
            addCriterion("ANO_MES not between", value1, value2, "ANO_MES");
            return (Criteria) this;
        }

        public Criteria andID_AGENTEIsNull() {
            addCriterion("ID_AGENTE is null");
            return (Criteria) this;
        }

        public Criteria andID_AGENTEIsNotNull() {
            addCriterion("ID_AGENTE is not null");
            return (Criteria) this;
        }

        public Criteria andID_AGENTEEqualTo(Integer value) {
            addCriterion("ID_AGENTE =", value, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_AGENTENotEqualTo(Integer value) {
            addCriterion("ID_AGENTE <>", value, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_AGENTEGreaterThan(Integer value) {
            addCriterion("ID_AGENTE >", value, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_AGENTEGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_AGENTE >=", value, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_AGENTELessThan(Integer value) {
            addCriterion("ID_AGENTE <", value, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_AGENTELessThanOrEqualTo(Integer value) {
            addCriterion("ID_AGENTE <=", value, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_AGENTEIn(List<Integer> values) {
            addCriterion("ID_AGENTE in", values, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_AGENTENotIn(List<Integer> values) {
            addCriterion("ID_AGENTE not in", values, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_AGENTEBetween(Integer value1, Integer value2) {
            addCriterion("ID_AGENTE between", value1, value2, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_AGENTENotBetween(Integer value1, Integer value2) {
            addCriterion("ID_AGENTE not between", value1, value2, "ID_AGENTE");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONIsNull() {
            addCriterion("ID_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONIsNotNull() {
            addCriterion("ID_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONEqualTo(Short value) {
            addCriterion("ID_VERSION =", value, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONNotEqualTo(Short value) {
            addCriterion("ID_VERSION <>", value, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONGreaterThan(Short value) {
            addCriterion("ID_VERSION >", value, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONGreaterThanOrEqualTo(Short value) {
            addCriterion("ID_VERSION >=", value, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONLessThan(Short value) {
            addCriterion("ID_VERSION <", value, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONLessThanOrEqualTo(Short value) {
            addCriterion("ID_VERSION <=", value, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONIn(List<Short> values) {
            addCriterion("ID_VERSION in", values, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONNotIn(List<Short> values) {
            addCriterion("ID_VERSION not in", values, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONBetween(Short value1, Short value2) {
            addCriterion("ID_VERSION between", value1, value2, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_VERSIONNotBetween(Short value1, Short value2) {
            addCriterion("ID_VERSION not between", value1, value2, "ID_VERSION");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIAIsNull() {
            addCriterion("ID_SUPERVISORIA is null");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIAIsNotNull() {
            addCriterion("ID_SUPERVISORIA is not null");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIAEqualTo(Short value) {
            addCriterion("ID_SUPERVISORIA =", value, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIANotEqualTo(Short value) {
            addCriterion("ID_SUPERVISORIA <>", value, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIAGreaterThan(Short value) {
            addCriterion("ID_SUPERVISORIA >", value, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIAGreaterThanOrEqualTo(Short value) {
            addCriterion("ID_SUPERVISORIA >=", value, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIALessThan(Short value) {
            addCriterion("ID_SUPERVISORIA <", value, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIALessThanOrEqualTo(Short value) {
            addCriterion("ID_SUPERVISORIA <=", value, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIAIn(List<Short> values) {
            addCriterion("ID_SUPERVISORIA in", values, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIANotIn(List<Short> values) {
            addCriterion("ID_SUPERVISORIA not in", values, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIABetween(Short value1, Short value2) {
            addCriterion("ID_SUPERVISORIA between", value1, value2, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_SUPERVISORIANotBetween(Short value1, Short value2) {
            addCriterion("ID_SUPERVISORIA not between", value1, value2, "ID_SUPERVISORIA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESAIsNull() {
            addCriterion("ID_EMPRESA is null");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESAIsNotNull() {
            addCriterion("ID_EMPRESA is not null");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESAEqualTo(Integer value) {
            addCriterion("ID_EMPRESA =", value, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESANotEqualTo(Integer value) {
            addCriterion("ID_EMPRESA <>", value, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESAGreaterThan(Integer value) {
            addCriterion("ID_EMPRESA >", value, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESAGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_EMPRESA >=", value, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESALessThan(Integer value) {
            addCriterion("ID_EMPRESA <", value, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESALessThanOrEqualTo(Integer value) {
            addCriterion("ID_EMPRESA <=", value, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESAIn(List<Integer> values) {
            addCriterion("ID_EMPRESA in", values, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESANotIn(List<Integer> values) {
            addCriterion("ID_EMPRESA not in", values, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESABetween(Integer value1, Integer value2) {
            addCriterion("ID_EMPRESA between", value1, value2, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andID_EMPRESANotBetween(Integer value1, Integer value2) {
            addCriterion("ID_EMPRESA not between", value1, value2, "ID_EMPRESA");
            return (Criteria) this;
        }

        public Criteria andRFCIsNull() {
            addCriterion("RFC is null");
            return (Criteria) this;
        }

        public Criteria andRFCIsNotNull() {
            addCriterion("RFC is not null");
            return (Criteria) this;
        }

        public Criteria andRFCEqualTo(String value) {
            addCriterion("RFC =", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCNotEqualTo(String value) {
            addCriterion("RFC <>", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCGreaterThan(String value) {
            addCriterion("RFC >", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCGreaterThanOrEqualTo(String value) {
            addCriterion("RFC >=", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCLessThan(String value) {
            addCriterion("RFC <", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCLessThanOrEqualTo(String value) {
            addCriterion("RFC <=", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCLike(String value) {
            addCriterion("RFC like", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCNotLike(String value) {
            addCriterion("RFC not like", value, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCIn(List<String> values) {
            addCriterion("RFC in", values, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCNotIn(List<String> values) {
            addCriterion("RFC not in", values, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCBetween(String value1, String value2) {
            addCriterion("RFC between", value1, value2, "RFC");
            return (Criteria) this;
        }

        public Criteria andRFCNotBetween(String value1, String value2) {
            addCriterion("RFC not between", value1, value2, "RFC");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGOIsNull() {
            addCriterion("TOT_IMP_PAGO is null");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGOIsNotNull() {
            addCriterion("TOT_IMP_PAGO is not null");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGOEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_PAGO =", value, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGONotEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_PAGO <>", value, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGOGreaterThan(BigDecimal value) {
            addCriterion("TOT_IMP_PAGO >", value, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGOGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_PAGO >=", value, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGOLessThan(BigDecimal value) {
            addCriterion("TOT_IMP_PAGO <", value, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGOLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_PAGO <=", value, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGOIn(List<BigDecimal> values) {
            addCriterion("TOT_IMP_PAGO in", values, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGONotIn(List<BigDecimal> values) {
            addCriterion("TOT_IMP_PAGO not in", values, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGOBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOT_IMP_PAGO between", value1, value2, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_PAGONotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOT_IMP_PAGO not between", value1, value2, "TOT_IMP_PAGO");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRIsNull() {
            addCriterion("TOT_IMP_ISR is null");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRIsNotNull() {
            addCriterion("TOT_IMP_ISR is not null");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISREqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_ISR =", value, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRNotEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_ISR <>", value, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRGreaterThan(BigDecimal value) {
            addCriterion("TOT_IMP_ISR >", value, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_ISR >=", value, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRLessThan(BigDecimal value) {
            addCriterion("TOT_IMP_ISR <", value, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_ISR <=", value, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRIn(List<BigDecimal> values) {
            addCriterion("TOT_IMP_ISR in", values, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRNotIn(List<BigDecimal> values) {
            addCriterion("TOT_IMP_ISR not in", values, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOT_IMP_ISR between", value1, value2, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_ISRNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOT_IMP_ISR not between", value1, value2, "TOT_IMP_ISR");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETIsNull() {
            addCriterion("TOT_IMP_IVA_RET is null");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETIsNotNull() {
            addCriterion("TOT_IMP_IVA_RET is not null");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_RET =", value, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETNotEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_RET <>", value, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETGreaterThan(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_RET >", value, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_RET >=", value, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETLessThan(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_RET <", value, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_RET <=", value, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETIn(List<BigDecimal> values) {
            addCriterion("TOT_IMP_IVA_RET in", values, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETNotIn(List<BigDecimal> values) {
            addCriterion("TOT_IMP_IVA_RET not in", values, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOT_IMP_IVA_RET between", value1, value2, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_RETNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOT_IMP_IVA_RET not between", value1, value2, "TOT_IMP_IVA_RET");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGIsNull() {
            addCriterion("TOT_IMP_IVA_PAG is null");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGIsNotNull() {
            addCriterion("TOT_IMP_IVA_PAG is not null");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_PAG =", value, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGNotEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_PAG <>", value, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGGreaterThan(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_PAG >", value, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_PAG >=", value, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGLessThan(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_PAG <", value, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOT_IMP_IVA_PAG <=", value, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGIn(List<BigDecimal> values) {
            addCriterion("TOT_IMP_IVA_PAG in", values, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGNotIn(List<BigDecimal> values) {
            addCriterion("TOT_IMP_IVA_PAG not in", values, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOT_IMP_IVA_PAG between", value1, value2, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andTOT_IMP_IVA_PAGNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOT_IMP_IVA_PAG not between", value1, value2, "TOT_IMP_IVA_PAG");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONIsNull() {
            addCriterion("IMP_DEDUCCION is null");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONIsNotNull() {
            addCriterion("IMP_DEDUCCION is not null");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONEqualTo(BigDecimal value) {
            addCriterion("IMP_DEDUCCION =", value, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONNotEqualTo(BigDecimal value) {
            addCriterion("IMP_DEDUCCION <>", value, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONGreaterThan(BigDecimal value) {
            addCriterion("IMP_DEDUCCION >", value, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("IMP_DEDUCCION >=", value, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONLessThan(BigDecimal value) {
            addCriterion("IMP_DEDUCCION <", value, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONLessThanOrEqualTo(BigDecimal value) {
            addCriterion("IMP_DEDUCCION <=", value, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONIn(List<BigDecimal> values) {
            addCriterion("IMP_DEDUCCION in", values, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONNotIn(List<BigDecimal> values) {
            addCriterion("IMP_DEDUCCION not in", values, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMP_DEDUCCION between", value1, value2, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_DEDUCCIONNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMP_DEDUCCION not between", value1, value2, "IMP_DEDUCCION");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALIsNull() {
            addCriterion("IMP_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALIsNotNull() {
            addCriterion("IMP_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALEqualTo(BigDecimal value) {
            addCriterion("IMP_TOTAL =", value, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALNotEqualTo(BigDecimal value) {
            addCriterion("IMP_TOTAL <>", value, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALGreaterThan(BigDecimal value) {
            addCriterion("IMP_TOTAL >", value, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("IMP_TOTAL >=", value, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALLessThan(BigDecimal value) {
            addCriterion("IMP_TOTAL <", value, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALLessThanOrEqualTo(BigDecimal value) {
            addCriterion("IMP_TOTAL <=", value, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALIn(List<BigDecimal> values) {
            addCriterion("IMP_TOTAL in", values, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALNotIn(List<BigDecimal> values) {
            addCriterion("IMP_TOTAL not in", values, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMP_TOTAL between", value1, value2, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_TOTALNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMP_TOTAL not between", value1, value2, "IMP_TOTAL");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACIsNull() {
            addCriterion("ID_USUARIO_CREAC is null");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACIsNotNull() {
            addCriterion("ID_USUARIO_CREAC is not null");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACEqualTo(String value) {
            addCriterion("ID_USUARIO_CREAC =", value, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACNotEqualTo(String value) {
            addCriterion("ID_USUARIO_CREAC <>", value, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACGreaterThan(String value) {
            addCriterion("ID_USUARIO_CREAC >", value, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACGreaterThanOrEqualTo(String value) {
            addCriterion("ID_USUARIO_CREAC >=", value, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACLessThan(String value) {
            addCriterion("ID_USUARIO_CREAC <", value, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACLessThanOrEqualTo(String value) {
            addCriterion("ID_USUARIO_CREAC <=", value, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACLike(String value) {
            addCriterion("ID_USUARIO_CREAC like", value, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACNotLike(String value) {
            addCriterion("ID_USUARIO_CREAC not like", value, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACIn(List<String> values) {
            addCriterion("ID_USUARIO_CREAC in", values, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACNotIn(List<String> values) {
            addCriterion("ID_USUARIO_CREAC not in", values, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACBetween(String value1, String value2) {
            addCriterion("ID_USUARIO_CREAC between", value1, value2, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andID_USUARIO_CREACNotBetween(String value1, String value2) {
            addCriterion("ID_USUARIO_CREAC not between", value1, value2, "ID_USUARIO_CREAC");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTIsNull() {
            addCriterion("B_FACT_ELECT is null");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTIsNotNull() {
            addCriterion("B_FACT_ELECT is not null");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTEqualTo(String value) {
            addCriterion("B_FACT_ELECT =", value, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTNotEqualTo(String value) {
            addCriterion("B_FACT_ELECT <>", value, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTGreaterThan(String value) {
            addCriterion("B_FACT_ELECT >", value, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTGreaterThanOrEqualTo(String value) {
            addCriterion("B_FACT_ELECT >=", value, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTLessThan(String value) {
            addCriterion("B_FACT_ELECT <", value, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTLessThanOrEqualTo(String value) {
            addCriterion("B_FACT_ELECT <=", value, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTLike(String value) {
            addCriterion("B_FACT_ELECT like", value, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTNotLike(String value) {
            addCriterion("B_FACT_ELECT not like", value, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTIn(List<String> values) {
            addCriterion("B_FACT_ELECT in", values, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTNotIn(List<String> values) {
            addCriterion("B_FACT_ELECT not in", values, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTBetween(String value1, String value2) {
            addCriterion("B_FACT_ELECT between", value1, value2, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andB_FACT_ELECTNotBetween(String value1, String value2) {
            addCriterion("B_FACT_ELECT not between", value1, value2, "b_FACT_ELECT");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICIsNull() {
            addCriterion("CVE_ORIGEN_APLIC is null");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICIsNotNull() {
            addCriterion("CVE_ORIGEN_APLIC is not null");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICEqualTo(String value) {
            addCriterion("CVE_ORIGEN_APLIC =", value, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICNotEqualTo(String value) {
            addCriterion("CVE_ORIGEN_APLIC <>", value, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICGreaterThan(String value) {
            addCriterion("CVE_ORIGEN_APLIC >", value, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICGreaterThanOrEqualTo(String value) {
            addCriterion("CVE_ORIGEN_APLIC >=", value, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICLessThan(String value) {
            addCriterion("CVE_ORIGEN_APLIC <", value, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICLessThanOrEqualTo(String value) {
            addCriterion("CVE_ORIGEN_APLIC <=", value, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICLike(String value) {
            addCriterion("CVE_ORIGEN_APLIC like", value, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICNotLike(String value) {
            addCriterion("CVE_ORIGEN_APLIC not like", value, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICIn(List<String> values) {
            addCriterion("CVE_ORIGEN_APLIC in", values, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICNotIn(List<String> values) {
            addCriterion("CVE_ORIGEN_APLIC not in", values, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICBetween(String value1, String value2) {
            addCriterion("CVE_ORIGEN_APLIC between", value1, value2, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andCVE_ORIGEN_APLICNotBetween(String value1, String value2) {
            addCriterion("CVE_ORIGEN_APLIC not between", value1, value2, "CVE_ORIGEN_APLIC");
            return (Criteria) this;
        }

        public Criteria andFH_CARGAIsNull() {
            addCriterion("FH_CARGA is null");
            return (Criteria) this;
        }

        public Criteria andFH_CARGAIsNotNull() {
            addCriterion("FH_CARGA is not null");
            return (Criteria) this;
        }

        public Criteria andFH_CARGAEqualTo(Date value) {
            addCriterionForJDBCDate("FH_CARGA =", value, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_CARGANotEqualTo(Date value) {
            addCriterionForJDBCDate("FH_CARGA <>", value, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_CARGAGreaterThan(Date value) {
            addCriterionForJDBCDate("FH_CARGA >", value, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_CARGAGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FH_CARGA >=", value, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_CARGALessThan(Date value) {
            addCriterionForJDBCDate("FH_CARGA <", value, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_CARGALessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FH_CARGA <=", value, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_CARGAIn(List<Date> values) {
            addCriterionForJDBCDate("FH_CARGA in", values, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_CARGANotIn(List<Date> values) {
            addCriterionForJDBCDate("FH_CARGA not in", values, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_CARGABetween(Timestamp value1, Timestamp value2) {
            addCriterionForJDBCTimeStamp("FH_CARGA between", value1, value2, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_CARGANotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FH_CARGA not between", value1, value2, "FH_CARGA");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIOIsNull() {
            addCriterion("FH_ENVIO is null");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIOIsNotNull() {
            addCriterion("FH_ENVIO is not null");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIOEqualTo(Date value) {
            addCriterionForJDBCDate("FH_ENVIO =", value, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIONotEqualTo(Date value) {
            addCriterionForJDBCDate("FH_ENVIO <>", value, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIOGreaterThan(Date value) {
            addCriterionForJDBCDate("FH_ENVIO >", value, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIOGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FH_ENVIO >=", value, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIOLessThan(Date value) {
            addCriterionForJDBCDate("FH_ENVIO <", value, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIOLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FH_ENVIO <=", value, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIOIn(List<Date> values) {
            addCriterionForJDBCDate("FH_ENVIO in", values, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIONotIn(List<Date> values) {
            addCriterionForJDBCDate("FH_ENVIO not in", values, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIOBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FH_ENVIO between", value1, value2, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_ENVIONotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FH_ENVIO not between", value1, value2, "FH_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTAIsNull() {
            addCriterion("FH_RESPUESTA is null");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTAIsNotNull() {
            addCriterion("FH_RESPUESTA is not null");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTAEqualTo(Date value) {
            addCriterionForJDBCDate("FH_RESPUESTA =", value, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTANotEqualTo(Date value) {
            addCriterionForJDBCDate("FH_RESPUESTA <>", value, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTAGreaterThan(Date value) {
            addCriterionForJDBCDate("FH_RESPUESTA >", value, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTAGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FH_RESPUESTA >=", value, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTALessThan(Date value) {
            addCriterionForJDBCDate("FH_RESPUESTA <", value, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTALessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FH_RESPUESTA <=", value, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTAIn(List<Date> values) {
            addCriterionForJDBCDate("FH_RESPUESTA in", values, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTANotIn(List<Date> values) {
            addCriterionForJDBCDate("FH_RESPUESTA not in", values, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTABetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FH_RESPUESTA between", value1, value2, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andFH_RESPUESTANotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FH_RESPUESTA not between", value1, value2, "FH_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTAIsNull() {
            addCriterion("COD_RESPUESTA is null");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTAIsNotNull() {
            addCriterion("COD_RESPUESTA is not null");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTAEqualTo(Long value) {
            addCriterion("COD_RESPUESTA =", value, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTANotEqualTo(Long value) {
            addCriterion("COD_RESPUESTA <>", value, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTAGreaterThan(Long value) {
            addCriterion("COD_RESPUESTA >", value, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTAGreaterThanOrEqualTo(Long value) {
            addCriterion("COD_RESPUESTA >=", value, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTALessThan(Long value) {
            addCriterion("COD_RESPUESTA <", value, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTALessThanOrEqualTo(Long value) {
            addCriterion("COD_RESPUESTA <=", value, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTAIn(List<Long> values) {
            addCriterion("COD_RESPUESTA in", values, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTANotIn(List<Long> values) {
            addCriterion("COD_RESPUESTA not in", values, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTABetween(Long value1, Long value2) {
            addCriterion("COD_RESPUESTA between", value1, value2, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_RESPUESTANotBetween(Long value1, Long value2) {
            addCriterion("COD_RESPUESTA not between", value1, value2, "COD_RESPUESTA");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONIsNull() {
            addCriterion("COD_TRANSACCION is null");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONIsNotNull() {
            addCriterion("COD_TRANSACCION is not null");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONEqualTo(Long value) {
            addCriterion("COD_TRANSACCION =", value, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONNotEqualTo(Long value) {
            addCriterion("COD_TRANSACCION <>", value, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONGreaterThan(Long value) {
            addCriterion("COD_TRANSACCION >", value, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONGreaterThanOrEqualTo(Long value) {
            addCriterion("COD_TRANSACCION >=", value, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONLessThan(Long value) {
            addCriterion("COD_TRANSACCION <", value, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONLessThanOrEqualTo(Long value) {
            addCriterion("COD_TRANSACCION <=", value, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONIn(List<Long> values) {
            addCriterion("COD_TRANSACCION in", values, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONNotIn(List<Long> values) {
            addCriterion("COD_TRANSACCION not in", values, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONBetween(Long value1, Long value2) {
            addCriterion("COD_TRANSACCION between", value1, value2, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_TRANSACCIONNotBetween(Long value1, Long value2) {
            addCriterion("COD_TRANSACCION not between", value1, value2, "COD_TRANSACCION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONIsNull() {
            addCriterion("COD_CONFIRMACION is null");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONIsNotNull() {
            addCriterion("COD_CONFIRMACION is not null");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONEqualTo(String value) {
            addCriterion("COD_CONFIRMACION =", value, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONNotEqualTo(String value) {
            addCriterion("COD_CONFIRMACION <>", value, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONGreaterThan(String value) {
            addCriterion("COD_CONFIRMACION >", value, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONGreaterThanOrEqualTo(String value) {
            addCriterion("COD_CONFIRMACION >=", value, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONLessThan(String value) {
            addCriterion("COD_CONFIRMACION <", value, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONLessThanOrEqualTo(String value) {
            addCriterion("COD_CONFIRMACION <=", value, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONLike(String value) {
            addCriterion("COD_CONFIRMACION like", value, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONNotLike(String value) {
            addCriterion("COD_CONFIRMACION not like", value, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONIn(List<String> values) {
            addCriterion("COD_CONFIRMACION in", values, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONNotIn(List<String> values) {
            addCriterion("COD_CONFIRMACION not in", values, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONBetween(String value1, String value2) {
            addCriterion("COD_CONFIRMACION between", value1, value2, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andCOD_CONFIRMACIONNotBetween(String value1, String value2) {
            addCriterion("COD_CONFIRMACION not between", value1, value2, "COD_CONFIRMACION");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOIsNull() {
            addCriterion("B_CORRECTO is null");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOIsNotNull() {
            addCriterion("B_CORRECTO is not null");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOEqualTo(String value) {
            addCriterion("B_CORRECTO =", value, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTONotEqualTo(String value) {
            addCriterion("B_CORRECTO <>", value, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOGreaterThan(String value) {
            addCriterion("B_CORRECTO >", value, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOGreaterThanOrEqualTo(String value) {
            addCriterion("B_CORRECTO >=", value, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOLessThan(String value) {
            addCriterion("B_CORRECTO <", value, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOLessThanOrEqualTo(String value) {
            addCriterion("B_CORRECTO <=", value, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOLike(String value) {
            addCriterion("B_CORRECTO like", value, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTONotLike(String value) {
            addCriterion("B_CORRECTO not like", value, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOIn(List<String> values) {
            addCriterion("B_CORRECTO in", values, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTONotIn(List<String> values) {
            addCriterion("B_CORRECTO not in", values, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTOBetween(String value1, String value2) {
            addCriterion("B_CORRECTO between", value1, value2, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andB_CORRECTONotBetween(String value1, String value2) {
            addCriterion("B_CORRECTO not between", value1, value2, "b_CORRECTO");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGIsNull() {
            addCriterion("F_INI_REG is null");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGIsNotNull() {
            addCriterion("F_INI_REG is not null");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGEqualTo(Date value) {
            addCriterionForJDBCDate("F_INI_REG =", value, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGNotEqualTo(Date value) {
            addCriterionForJDBCDate("F_INI_REG <>", value, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGGreaterThan(Date value) {
            addCriterionForJDBCDate("F_INI_REG >", value, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("F_INI_REG >=", value, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGLessThan(Date value) {
            addCriterionForJDBCDate("F_INI_REG <", value, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("F_INI_REG <=", value, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGIn(List<Date> values) {
            addCriterionForJDBCDate("F_INI_REG in", values, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGNotIn(List<Date> values) {
            addCriterionForJDBCDate("F_INI_REG not in", values, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("F_INI_REG between", value1, value2, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_INI_REGNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("F_INI_REG not between", value1, value2, "f_INI_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGIsNull() {
            addCriterion("F_TER_REG is null");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGIsNotNull() {
            addCriterion("F_TER_REG is not null");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGEqualTo(Date value) {
            addCriterionForJDBCDate("F_TER_REG =", value, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGNotEqualTo(Date value) {
            addCriterionForJDBCDate("F_TER_REG <>", value, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGGreaterThan(Date value) {
            addCriterionForJDBCDate("F_TER_REG >", value, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("F_TER_REG >=", value, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGLessThan(Date value) {
            addCriterionForJDBCDate("F_TER_REG <", value, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("F_TER_REG <=", value, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGIn(List<Date> values) {
            addCriterionForJDBCDate("F_TER_REG in", values, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGNotIn(List<Date> values) {
            addCriterionForJDBCDate("F_TER_REG not in", values, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("F_TER_REG between", value1, value2, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andF_TER_REGNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("F_TER_REG not between", value1, value2, "f_TER_REG");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIAIsNull() {
            addCriterion("B_ULT_REG_DIA is null");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIAIsNotNull() {
            addCriterion("B_ULT_REG_DIA is not null");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIAEqualTo(String value) {
            addCriterion("B_ULT_REG_DIA =", value, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIANotEqualTo(String value) {
            addCriterion("B_ULT_REG_DIA <>", value, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIAGreaterThan(String value) {
            addCriterion("B_ULT_REG_DIA >", value, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIAGreaterThanOrEqualTo(String value) {
            addCriterion("B_ULT_REG_DIA >=", value, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIALessThan(String value) {
            addCriterion("B_ULT_REG_DIA <", value, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIALessThanOrEqualTo(String value) {
            addCriterion("B_ULT_REG_DIA <=", value, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIALike(String value) {
            addCriterion("B_ULT_REG_DIA like", value, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIANotLike(String value) {
            addCriterion("B_ULT_REG_DIA not like", value, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIAIn(List<String> values) {
            addCriterion("B_ULT_REG_DIA in", values, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIANotIn(List<String> values) {
            addCriterion("B_ULT_REG_DIA not in", values, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIABetween(String value1, String value2) {
            addCriterion("B_ULT_REG_DIA between", value1, value2, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andB_ULT_REG_DIANotBetween(String value1, String value2) {
            addCriterion("B_ULT_REG_DIA not between", value1, value2, "b_ULT_REG_DIA");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALIsNull() {
            addCriterion("IMP_SUBTOTAL is null");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALIsNotNull() {
            addCriterion("IMP_SUBTOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALEqualTo(BigDecimal value) {
            addCriterion("IMP_SUBTOTAL =", value, "IMP_SUBTOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALNotEqualTo(BigDecimal value) {
            addCriterion("IMP_SUBTOTAL <>", value, "IMP_SUBTOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALGreaterThan(BigDecimal value) {
            addCriterion("IMP_SUBTOTAL >", value, "IMP_SUBTOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("IMP_SUBTOTAL >=", value, "IMP_SUBTOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALLessThan(BigDecimal value) {
            addCriterion("IMP_SUBTOTAL <", value, "IMP_SUBTOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALLessThanOrEqualTo(BigDecimal value) {
            addCriterion("IMP_SUBTOTAL <=", value, "IMP_SUBTOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALIn(List<BigDecimal> values) {
            addCriterion("IMP_SUBTOTAL in", values, "IMP_SUBTOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALNotIn(List<BigDecimal> values) {
            addCriterion("IMP_SUBTOTAL not in", values, "IMP_SUBTOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMP_SUBTOTAL between", value1, value2, "IMP_SUBTOTAL");
            return (Criteria) this;
        }

        public Criteria andIMP_SUBTOTALNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("IMP_SUBTOTAL not between", value1, value2, "IMP_SUBTOTAL");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 24 13:21:56 CDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}