package mx.com.ebs.inter.data.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RecAccesoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public RecAccesoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEBS_RFCIsNull() {
            addCriterion("EBS_RFC is null");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCIsNotNull() {
            addCriterion("EBS_RFC is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCEqualTo(String value) {
            addCriterion("EBS_RFC =", value, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCNotEqualTo(String value) {
            addCriterion("EBS_RFC <>", value, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCGreaterThan(String value) {
            addCriterion("EBS_RFC >", value, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCGreaterThanOrEqualTo(String value) {
            addCriterion("EBS_RFC >=", value, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCLessThan(String value) {
            addCriterion("EBS_RFC <", value, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCLessThanOrEqualTo(String value) {
            addCriterion("EBS_RFC <=", value, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCLike(String value) {
            addCriterion("EBS_RFC like", value, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCNotLike(String value) {
            addCriterion("EBS_RFC not like", value, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCIn(List<String> values) {
            addCriterion("EBS_RFC in", values, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCNotIn(List<String> values) {
            addCriterion("EBS_RFC not in", values, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCBetween(String value1, String value2) {
            addCriterion("EBS_RFC between", value1, value2, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_RFCNotBetween(String value1, String value2) {
            addCriterion("EBS_RFC not between", value1, value2, "EBS_RFC");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDIsNull() {
            addCriterion("EBS_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDIsNotNull() {
            addCriterion("EBS_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDEqualTo(String value) {
            addCriterion("EBS_USER_ID =", value, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDNotEqualTo(String value) {
            addCriterion("EBS_USER_ID <>", value, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDGreaterThan(String value) {
            addCriterion("EBS_USER_ID >", value, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDGreaterThanOrEqualTo(String value) {
            addCriterion("EBS_USER_ID >=", value, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDLessThan(String value) {
            addCriterion("EBS_USER_ID <", value, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDLessThanOrEqualTo(String value) {
            addCriterion("EBS_USER_ID <=", value, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDLike(String value) {
            addCriterion("EBS_USER_ID like", value, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDNotLike(String value) {
            addCriterion("EBS_USER_ID not like", value, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDIn(List<String> values) {
            addCriterion("EBS_USER_ID in", values, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDNotIn(List<String> values) {
            addCriterion("EBS_USER_ID not in", values, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDBetween(String value1, String value2) {
            addCriterion("EBS_USER_ID between", value1, value2, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_USER_IDNotBetween(String value1, String value2) {
            addCriterion("EBS_USER_ID not between", value1, value2, "EBS_USER_ID");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALIsNull() {
            addCriterion("EBS_PW_ACTUAL is null");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALIsNotNull() {
            addCriterion("EBS_PW_ACTUAL is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALEqualTo(String value) {
            addCriterion("EBS_PW_ACTUAL =", value, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALNotEqualTo(String value) {
            addCriterion("EBS_PW_ACTUAL <>", value, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALGreaterThan(String value) {
            addCriterion("EBS_PW_ACTUAL >", value, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALGreaterThanOrEqualTo(String value) {
            addCriterion("EBS_PW_ACTUAL >=", value, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALLessThan(String value) {
            addCriterion("EBS_PW_ACTUAL <", value, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALLessThanOrEqualTo(String value) {
            addCriterion("EBS_PW_ACTUAL <=", value, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALLike(String value) {
            addCriterion("EBS_PW_ACTUAL like", value, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALNotLike(String value) {
            addCriterion("EBS_PW_ACTUAL not like", value, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALIn(List<String> values) {
            addCriterion("EBS_PW_ACTUAL in", values, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALNotIn(List<String> values) {
            addCriterion("EBS_PW_ACTUAL not in", values, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALBetween(String value1, String value2) {
            addCriterion("EBS_PW_ACTUAL between", value1, value2, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_PW_ACTUALNotBetween(String value1, String value2) {
            addCriterion("EBS_PW_ACTUAL not between", value1, value2, "EBS_PW_ACTUAL");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERIsNull() {
            addCriterion("EBS_TIPO_USER is null");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERIsNotNull() {
            addCriterion("EBS_TIPO_USER is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USEREqualTo(String value) {
            addCriterion("EBS_TIPO_USER =", value, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERNotEqualTo(String value) {
            addCriterion("EBS_TIPO_USER <>", value, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERGreaterThan(String value) {
            addCriterion("EBS_TIPO_USER >", value, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERGreaterThanOrEqualTo(String value) {
            addCriterion("EBS_TIPO_USER >=", value, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERLessThan(String value) {
            addCriterion("EBS_TIPO_USER <", value, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERLessThanOrEqualTo(String value) {
            addCriterion("EBS_TIPO_USER <=", value, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERLike(String value) {
            addCriterion("EBS_TIPO_USER like", value, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERNotLike(String value) {
            addCriterion("EBS_TIPO_USER not like", value, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERIn(List<String> values) {
            addCriterion("EBS_TIPO_USER in", values, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERNotIn(List<String> values) {
            addCriterion("EBS_TIPO_USER not in", values, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERBetween(String value1, String value2) {
            addCriterion("EBS_TIPO_USER between", value1, value2, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_TIPO_USERNotBetween(String value1, String value2) {
            addCriterion("EBS_TIPO_USER not between", value1, value2, "EBS_TIPO_USER");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILIsNull() {
            addCriterion("EBS_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILIsNotNull() {
            addCriterion("EBS_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILEqualTo(String value) {
            addCriterion("EBS_EMAIL =", value, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILNotEqualTo(String value) {
            addCriterion("EBS_EMAIL <>", value, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILGreaterThan(String value) {
            addCriterion("EBS_EMAIL >", value, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILGreaterThanOrEqualTo(String value) {
            addCriterion("EBS_EMAIL >=", value, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILLessThan(String value) {
            addCriterion("EBS_EMAIL <", value, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILLessThanOrEqualTo(String value) {
            addCriterion("EBS_EMAIL <=", value, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILLike(String value) {
            addCriterion("EBS_EMAIL like", value, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILNotLike(String value) {
            addCriterion("EBS_EMAIL not like", value, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILIn(List<String> values) {
            addCriterion("EBS_EMAIL in", values, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILNotIn(List<String> values) {
            addCriterion("EBS_EMAIL not in", values, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILBetween(String value1, String value2) {
            addCriterion("EBS_EMAIL between", value1, value2, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_EMAILNotBetween(String value1, String value2) {
            addCriterion("EBS_EMAIL not between", value1, value2, "EBS_EMAIL");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBREIsNull() {
            addCriterion("EBS_NOMBRE is null");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBREIsNotNull() {
            addCriterion("EBS_NOMBRE is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBREEqualTo(String value) {
            addCriterion("EBS_NOMBRE =", value, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBRENotEqualTo(String value) {
            addCriterion("EBS_NOMBRE <>", value, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBREGreaterThan(String value) {
            addCriterion("EBS_NOMBRE >", value, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBREGreaterThanOrEqualTo(String value) {
            addCriterion("EBS_NOMBRE >=", value, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBRELessThan(String value) {
            addCriterion("EBS_NOMBRE <", value, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBRELessThanOrEqualTo(String value) {
            addCriterion("EBS_NOMBRE <=", value, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBRELike(String value) {
            addCriterion("EBS_NOMBRE like", value, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBRENotLike(String value) {
            addCriterion("EBS_NOMBRE not like", value, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBREIn(List<String> values) {
            addCriterion("EBS_NOMBRE in", values, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBRENotIn(List<String> values) {
            addCriterion("EBS_NOMBRE not in", values, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBREBetween(String value1, String value2) {
            addCriterion("EBS_NOMBRE between", value1, value2, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_NOMBRENotBetween(String value1, String value2) {
            addCriterion("EBS_NOMBRE not between", value1, value2, "EBS_NOMBRE");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOIsNull() {
            addCriterion("EBS_TELEFONO is null");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOIsNotNull() {
            addCriterion("EBS_TELEFONO is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOEqualTo(String value) {
            addCriterion("EBS_TELEFONO =", value, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONONotEqualTo(String value) {
            addCriterion("EBS_TELEFONO <>", value, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOGreaterThan(String value) {
            addCriterion("EBS_TELEFONO >", value, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOGreaterThanOrEqualTo(String value) {
            addCriterion("EBS_TELEFONO >=", value, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOLessThan(String value) {
            addCriterion("EBS_TELEFONO <", value, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOLessThanOrEqualTo(String value) {
            addCriterion("EBS_TELEFONO <=", value, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOLike(String value) {
            addCriterion("EBS_TELEFONO like", value, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONONotLike(String value) {
            addCriterion("EBS_TELEFONO not like", value, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOIn(List<String> values) {
            addCriterion("EBS_TELEFONO in", values, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONONotIn(List<String> values) {
            addCriterion("EBS_TELEFONO not in", values, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONOBetween(String value1, String value2) {
            addCriterion("EBS_TELEFONO between", value1, value2, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_TELEFONONotBetween(String value1, String value2) {
            addCriterion("EBS_TELEFONO not between", value1, value2, "EBS_TELEFONO");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONIsNull() {
            addCriterion("EBS_DIRECCION is null");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONIsNotNull() {
            addCriterion("EBS_DIRECCION is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONEqualTo(String value) {
            addCriterion("EBS_DIRECCION =", value, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONNotEqualTo(String value) {
            addCriterion("EBS_DIRECCION <>", value, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONGreaterThan(String value) {
            addCriterion("EBS_DIRECCION >", value, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONGreaterThanOrEqualTo(String value) {
            addCriterion("EBS_DIRECCION >=", value, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONLessThan(String value) {
            addCriterion("EBS_DIRECCION <", value, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONLessThanOrEqualTo(String value) {
            addCriterion("EBS_DIRECCION <=", value, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONLike(String value) {
            addCriterion("EBS_DIRECCION like", value, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONNotLike(String value) {
            addCriterion("EBS_DIRECCION not like", value, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONIn(List<String> values) {
            addCriterion("EBS_DIRECCION in", values, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONNotIn(List<String> values) {
            addCriterion("EBS_DIRECCION not in", values, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONBetween(String value1, String value2) {
            addCriterion("EBS_DIRECCION between", value1, value2, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andEBS_DIRECCIONNotBetween(String value1, String value2) {
            addCriterion("EBS_DIRECCION not between", value1, value2, "EBS_DIRECCION");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSTATUSEqualTo(BigDecimal value) {
            addCriterion("STATUS =", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotEqualTo(BigDecimal value) {
            addCriterion("STATUS <>", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThan(BigDecimal value) {
            addCriterion("STATUS >", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STATUS >=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThan(BigDecimal value) {
            addCriterion("STATUS <", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STATUS <=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSIn(List<BigDecimal> values) {
            addCriterion("STATUS in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotIn(List<BigDecimal> values) {
            addCriterion("STATUS not in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATUS between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATUS not between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHAIsNull() {
            addCriterion("EBS_FECHA is null");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHAIsNotNull() {
            addCriterion("EBS_FECHA is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHAEqualTo(Date value) {
            addCriterion("EBS_FECHA =", value, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHANotEqualTo(Date value) {
            addCriterion("EBS_FECHA <>", value, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHAGreaterThan(Date value) {
            addCriterion("EBS_FECHA >", value, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHAGreaterThanOrEqualTo(Date value) {
            addCriterion("EBS_FECHA >=", value, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHALessThan(Date value) {
            addCriterion("EBS_FECHA <", value, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHALessThanOrEqualTo(Date value) {
            addCriterion("EBS_FECHA <=", value, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHAIn(List<Date> values) {
            addCriterion("EBS_FECHA in", values, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHANotIn(List<Date> values) {
            addCriterion("EBS_FECHA not in", values, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHABetween(Date value1, Date value2) {
            addCriterion("EBS_FECHA between", value1, value2, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andEBS_FECHANotBetween(Date value1, Date value2) {
            addCriterion("EBS_FECHA not between", value1, value2, "EBS_FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONIsNull() {
            addCriterion("FECHA_MODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONIsNotNull() {
            addCriterion("FECHA_MODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONEqualTo(Date value) {
            addCriterion("FECHA_MODIFICACION =", value, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONNotEqualTo(Date value) {
            addCriterion("FECHA_MODIFICACION <>", value, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONGreaterThan(Date value) {
            addCriterion("FECHA_MODIFICACION >", value, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONGreaterThanOrEqualTo(Date value) {
            addCriterion("FECHA_MODIFICACION >=", value, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONLessThan(Date value) {
            addCriterion("FECHA_MODIFICACION <", value, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONLessThanOrEqualTo(Date value) {
            addCriterion("FECHA_MODIFICACION <=", value, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONIn(List<Date> values) {
            addCriterion("FECHA_MODIFICACION in", values, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONNotIn(List<Date> values) {
            addCriterion("FECHA_MODIFICACION not in", values, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONBetween(Date value1, Date value2) {
            addCriterion("FECHA_MODIFICACION between", value1, value2, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andFECHA_MODIFICACIONNotBetween(Date value1, Date value2) {
            addCriterion("FECHA_MODIFICACION not between", value1, value2, "FECHA_MODIFICACION");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKIsNull() {
            addCriterion("M_ENVIO_CHK is null");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKIsNotNull() {
            addCriterion("M_ENVIO_CHK is not null");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKEqualTo(BigDecimal value) {
            addCriterion("M_ENVIO_CHK =", value, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKNotEqualTo(BigDecimal value) {
            addCriterion("M_ENVIO_CHK <>", value, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKGreaterThan(BigDecimal value) {
            addCriterion("M_ENVIO_CHK >", value, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("M_ENVIO_CHK >=", value, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKLessThan(BigDecimal value) {
            addCriterion("M_ENVIO_CHK <", value, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKLessThanOrEqualTo(BigDecimal value) {
            addCriterion("M_ENVIO_CHK <=", value, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKIn(List<BigDecimal> values) {
            addCriterion("M_ENVIO_CHK in", values, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKNotIn(List<BigDecimal> values) {
            addCriterion("M_ENVIO_CHK not in", values, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("M_ENVIO_CHK between", value1, value2, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andM_ENVIO_CHKNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("M_ENVIO_CHK not between", value1, value2, "m_ENVIO_CHK");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOIsNull() {
            addCriterion("MAIL_ENVIO is null");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOIsNotNull() {
            addCriterion("MAIL_ENVIO is not null");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOEqualTo(String value) {
            addCriterion("MAIL_ENVIO =", value, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIONotEqualTo(String value) {
            addCriterion("MAIL_ENVIO <>", value, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOGreaterThan(String value) {
            addCriterion("MAIL_ENVIO >", value, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOGreaterThanOrEqualTo(String value) {
            addCriterion("MAIL_ENVIO >=", value, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOLessThan(String value) {
            addCriterion("MAIL_ENVIO <", value, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOLessThanOrEqualTo(String value) {
            addCriterion("MAIL_ENVIO <=", value, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOLike(String value) {
            addCriterion("MAIL_ENVIO like", value, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIONotLike(String value) {
            addCriterion("MAIL_ENVIO not like", value, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOIn(List<String> values) {
            addCriterion("MAIL_ENVIO in", values, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIONotIn(List<String> values) {
            addCriterion("MAIL_ENVIO not in", values, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIOBetween(String value1, String value2) {
            addCriterion("MAIL_ENVIO between", value1, value2, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andMAIL_ENVIONotBetween(String value1, String value2) {
            addCriterion("MAIL_ENVIO not between", value1, value2, "MAIL_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPIsNull() {
            addCriterion("FTP_ENVIO_IP is null");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPIsNotNull() {
            addCriterion("FTP_ENVIO_IP is not null");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPEqualTo(String value) {
            addCriterion("FTP_ENVIO_IP =", value, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPNotEqualTo(String value) {
            addCriterion("FTP_ENVIO_IP <>", value, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPGreaterThan(String value) {
            addCriterion("FTP_ENVIO_IP >", value, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPGreaterThanOrEqualTo(String value) {
            addCriterion("FTP_ENVIO_IP >=", value, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPLessThan(String value) {
            addCriterion("FTP_ENVIO_IP <", value, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPLessThanOrEqualTo(String value) {
            addCriterion("FTP_ENVIO_IP <=", value, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPLike(String value) {
            addCriterion("FTP_ENVIO_IP like", value, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPNotLike(String value) {
            addCriterion("FTP_ENVIO_IP not like", value, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPIn(List<String> values) {
            addCriterion("FTP_ENVIO_IP in", values, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPNotIn(List<String> values) {
            addCriterion("FTP_ENVIO_IP not in", values, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPBetween(String value1, String value2) {
            addCriterion("FTP_ENVIO_IP between", value1, value2, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_IPNotBetween(String value1, String value2) {
            addCriterion("FTP_ENVIO_IP not between", value1, value2, "FTP_ENVIO_IP");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHIsNull() {
            addCriterion("FTP_ENVIO_PATH is null");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHIsNotNull() {
            addCriterion("FTP_ENVIO_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHEqualTo(String value) {
            addCriterion("FTP_ENVIO_PATH =", value, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHNotEqualTo(String value) {
            addCriterion("FTP_ENVIO_PATH <>", value, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHGreaterThan(String value) {
            addCriterion("FTP_ENVIO_PATH >", value, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHGreaterThanOrEqualTo(String value) {
            addCriterion("FTP_ENVIO_PATH >=", value, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHLessThan(String value) {
            addCriterion("FTP_ENVIO_PATH <", value, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHLessThanOrEqualTo(String value) {
            addCriterion("FTP_ENVIO_PATH <=", value, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHLike(String value) {
            addCriterion("FTP_ENVIO_PATH like", value, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHNotLike(String value) {
            addCriterion("FTP_ENVIO_PATH not like", value, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHIn(List<String> values) {
            addCriterion("FTP_ENVIO_PATH in", values, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHNotIn(List<String> values) {
            addCriterion("FTP_ENVIO_PATH not in", values, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHBetween(String value1, String value2) {
            addCriterion("FTP_ENVIO_PATH between", value1, value2, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PATHNotBetween(String value1, String value2) {
            addCriterion("FTP_ENVIO_PATH not between", value1, value2, "FTP_ENVIO_PATH");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USIsNull() {
            addCriterion("FTP_ENVIO_US is null");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USIsNotNull() {
            addCriterion("FTP_ENVIO_US is not null");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USEqualTo(String value) {
            addCriterion("FTP_ENVIO_US =", value, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USNotEqualTo(String value) {
            addCriterion("FTP_ENVIO_US <>", value, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USGreaterThan(String value) {
            addCriterion("FTP_ENVIO_US >", value, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USGreaterThanOrEqualTo(String value) {
            addCriterion("FTP_ENVIO_US >=", value, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USLessThan(String value) {
            addCriterion("FTP_ENVIO_US <", value, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USLessThanOrEqualTo(String value) {
            addCriterion("FTP_ENVIO_US <=", value, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USLike(String value) {
            addCriterion("FTP_ENVIO_US like", value, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USNotLike(String value) {
            addCriterion("FTP_ENVIO_US not like", value, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USIn(List<String> values) {
            addCriterion("FTP_ENVIO_US in", values, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USNotIn(List<String> values) {
            addCriterion("FTP_ENVIO_US not in", values, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USBetween(String value1, String value2) {
            addCriterion("FTP_ENVIO_US between", value1, value2, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_USNotBetween(String value1, String value2) {
            addCriterion("FTP_ENVIO_US not between", value1, value2, "FTP_ENVIO_US");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWIsNull() {
            addCriterion("FTP_ENVIO_PW is null");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWIsNotNull() {
            addCriterion("FTP_ENVIO_PW is not null");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWEqualTo(String value) {
            addCriterion("FTP_ENVIO_PW =", value, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWNotEqualTo(String value) {
            addCriterion("FTP_ENVIO_PW <>", value, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWGreaterThan(String value) {
            addCriterion("FTP_ENVIO_PW >", value, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWGreaterThanOrEqualTo(String value) {
            addCriterion("FTP_ENVIO_PW >=", value, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWLessThan(String value) {
            addCriterion("FTP_ENVIO_PW <", value, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWLessThanOrEqualTo(String value) {
            addCriterion("FTP_ENVIO_PW <=", value, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWLike(String value) {
            addCriterion("FTP_ENVIO_PW like", value, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWNotLike(String value) {
            addCriterion("FTP_ENVIO_PW not like", value, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWIn(List<String> values) {
            addCriterion("FTP_ENVIO_PW in", values, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWNotIn(List<String> values) {
            addCriterion("FTP_ENVIO_PW not in", values, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWBetween(String value1, String value2) {
            addCriterion("FTP_ENVIO_PW between", value1, value2, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFTP_ENVIO_PWNotBetween(String value1, String value2) {
            addCriterion("FTP_ENVIO_PW not between", value1, value2, "FTP_ENVIO_PW");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOIsNull() {
            addCriterion("FAX_ENVIO is null");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOIsNotNull() {
            addCriterion("FAX_ENVIO is not null");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOEqualTo(String value) {
            addCriterion("FAX_ENVIO =", value, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIONotEqualTo(String value) {
            addCriterion("FAX_ENVIO <>", value, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOGreaterThan(String value) {
            addCriterion("FAX_ENVIO >", value, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOGreaterThanOrEqualTo(String value) {
            addCriterion("FAX_ENVIO >=", value, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOLessThan(String value) {
            addCriterion("FAX_ENVIO <", value, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOLessThanOrEqualTo(String value) {
            addCriterion("FAX_ENVIO <=", value, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOLike(String value) {
            addCriterion("FAX_ENVIO like", value, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIONotLike(String value) {
            addCriterion("FAX_ENVIO not like", value, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOIn(List<String> values) {
            addCriterion("FAX_ENVIO in", values, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIONotIn(List<String> values) {
            addCriterion("FAX_ENVIO not in", values, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIOBetween(String value1, String value2) {
            addCriterion("FAX_ENVIO between", value1, value2, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andFAX_ENVIONotBetween(String value1, String value2) {
            addCriterion("FAX_ENVIO not between", value1, value2, "FAX_ENVIO");
            return (Criteria) this;
        }

        public Criteria andSUCURSALIsNull() {
            addCriterion("SUCURSAL is null");
            return (Criteria) this;
        }

        public Criteria andSUCURSALIsNotNull() {
            addCriterion("SUCURSAL is not null");
            return (Criteria) this;
        }

        public Criteria andSUCURSALEqualTo(String value) {
            addCriterion("SUCURSAL =", value, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALNotEqualTo(String value) {
            addCriterion("SUCURSAL <>", value, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALGreaterThan(String value) {
            addCriterion("SUCURSAL >", value, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALGreaterThanOrEqualTo(String value) {
            addCriterion("SUCURSAL >=", value, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALLessThan(String value) {
            addCriterion("SUCURSAL <", value, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALLessThanOrEqualTo(String value) {
            addCriterion("SUCURSAL <=", value, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALLike(String value) {
            addCriterion("SUCURSAL like", value, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALNotLike(String value) {
            addCriterion("SUCURSAL not like", value, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALIn(List<String> values) {
            addCriterion("SUCURSAL in", values, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALNotIn(List<String> values) {
            addCriterion("SUCURSAL not in", values, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALBetween(String value1, String value2) {
            addCriterion("SUCURSAL between", value1, value2, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andSUCURSALNotBetween(String value1, String value2) {
            addCriterion("SUCURSAL not between", value1, value2, "SUCURSAL");
            return (Criteria) this;
        }

        public Criteria andCTA_PADREIsNull() {
            addCriterion("CTA_PADRE is null");
            return (Criteria) this;
        }

        public Criteria andCTA_PADREIsNotNull() {
            addCriterion("CTA_PADRE is not null");
            return (Criteria) this;
        }

        public Criteria andCTA_PADREEqualTo(String value) {
            addCriterion("CTA_PADRE =", value, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADRENotEqualTo(String value) {
            addCriterion("CTA_PADRE <>", value, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADREGreaterThan(String value) {
            addCriterion("CTA_PADRE >", value, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADREGreaterThanOrEqualTo(String value) {
            addCriterion("CTA_PADRE >=", value, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADRELessThan(String value) {
            addCriterion("CTA_PADRE <", value, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADRELessThanOrEqualTo(String value) {
            addCriterion("CTA_PADRE <=", value, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADRELike(String value) {
            addCriterion("CTA_PADRE like", value, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADRENotLike(String value) {
            addCriterion("CTA_PADRE not like", value, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADREIn(List<String> values) {
            addCriterion("CTA_PADRE in", values, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADRENotIn(List<String> values) {
            addCriterion("CTA_PADRE not in", values, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADREBetween(String value1, String value2) {
            addCriterion("CTA_PADRE between", value1, value2, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andCTA_PADRENotBetween(String value1, String value2) {
            addCriterion("CTA_PADRE not between", value1, value2, "CTA_PADRE");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSIsNull() {
            addCriterion("NINTENTOS is null");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSIsNotNull() {
            addCriterion("NINTENTOS is not null");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSEqualTo(BigDecimal value) {
            addCriterion("NINTENTOS =", value, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSNotEqualTo(BigDecimal value) {
            addCriterion("NINTENTOS <>", value, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSGreaterThan(BigDecimal value) {
            addCriterion("NINTENTOS >", value, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NINTENTOS >=", value, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSLessThan(BigDecimal value) {
            addCriterion("NINTENTOS <", value, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NINTENTOS <=", value, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSIn(List<BigDecimal> values) {
            addCriterion("NINTENTOS in", values, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSNotIn(List<BigDecimal> values) {
            addCriterion("NINTENTOS not in", values, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NINTENTOS between", value1, value2, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andNINTENTOSNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NINTENTOS not between", value1, value2, "NINTENTOS");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESOIsNull() {
            addCriterion("ULTIMOACCESO is null");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESOIsNotNull() {
            addCriterion("ULTIMOACCESO is not null");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESOEqualTo(Date value) {
            addCriterionForJDBCDate("ULTIMOACCESO =", value, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESONotEqualTo(Date value) {
            addCriterionForJDBCDate("ULTIMOACCESO <>", value, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESOGreaterThan(Date value) {
            addCriterionForJDBCDate("ULTIMOACCESO >", value, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESOGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ULTIMOACCESO >=", value, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESOLessThan(Date value) {
            addCriterionForJDBCDate("ULTIMOACCESO <", value, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESOLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ULTIMOACCESO <=", value, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESOIn(List<Date> values) {
            addCriterionForJDBCDate("ULTIMOACCESO in", values, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESONotIn(List<Date> values) {
            addCriterionForJDBCDate("ULTIMOACCESO not in", values, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESOBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ULTIMOACCESO between", value1, value2, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andULTIMOACCESONotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ULTIMOACCESO not between", value1, value2, "ULTIMOACCESO");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILIsNull() {
            addCriterion("EBS_PERFIL is null");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILIsNotNull() {
            addCriterion("EBS_PERFIL is not null");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILEqualTo(String value) {
            addCriterion("EBS_PERFIL =", value, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILNotEqualTo(String value) {
            addCriterion("EBS_PERFIL <>", value, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILGreaterThan(String value) {
            addCriterion("EBS_PERFIL >", value, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILGreaterThanOrEqualTo(String value) {
            addCriterion("EBS_PERFIL >=", value, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILLessThan(String value) {
            addCriterion("EBS_PERFIL <", value, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILLessThanOrEqualTo(String value) {
            addCriterion("EBS_PERFIL <=", value, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILLike(String value) {
            addCriterion("EBS_PERFIL like", value, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILNotLike(String value) {
            addCriterion("EBS_PERFIL not like", value, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILIn(List<String> values) {
            addCriterion("EBS_PERFIL in", values, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILNotIn(List<String> values) {
            addCriterion("EBS_PERFIL not in", values, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILBetween(String value1, String value2) {
            addCriterion("EBS_PERFIL between", value1, value2, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andEBS_PERFILNotBetween(String value1, String value2) {
            addCriterion("EBS_PERFIL not between", value1, value2, "EBS_PERFIL");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWIsNull() {
            addCriterion("CHANGEPW is null");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWIsNotNull() {
            addCriterion("CHANGEPW is not null");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWEqualTo(BigDecimal value) {
            addCriterion("CHANGEPW =", value, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWNotEqualTo(BigDecimal value) {
            addCriterion("CHANGEPW <>", value, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWGreaterThan(BigDecimal value) {
            addCriterion("CHANGEPW >", value, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CHANGEPW >=", value, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWLessThan(BigDecimal value) {
            addCriterion("CHANGEPW <", value, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CHANGEPW <=", value, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWIn(List<BigDecimal> values) {
            addCriterion("CHANGEPW in", values, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWNotIn(List<BigDecimal> values) {
            addCriterion("CHANGEPW not in", values, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHANGEPW between", value1, value2, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andCHANGEPWNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHANGEPW not between", value1, value2, "CHANGEPW");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEIsNull() {
            addCriterion("NUMERO_CLIENTE is null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEIsNotNull() {
            addCriterion("NUMERO_CLIENTE is not null");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEEqualTo(String value) {
            addCriterion("NUMERO_CLIENTE =", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTENotEqualTo(String value) {
            addCriterion("NUMERO_CLIENTE <>", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEGreaterThan(String value) {
            addCriterion("NUMERO_CLIENTE >", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEGreaterThanOrEqualTo(String value) {
            addCriterion("NUMERO_CLIENTE >=", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTELessThan(String value) {
            addCriterion("NUMERO_CLIENTE <", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTELessThanOrEqualTo(String value) {
            addCriterion("NUMERO_CLIENTE <=", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTELike(String value) {
            addCriterion("NUMERO_CLIENTE like", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTENotLike(String value) {
            addCriterion("NUMERO_CLIENTE not like", value, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEIn(List<String> values) {
            addCriterion("NUMERO_CLIENTE in", values, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTENotIn(List<String> values) {
            addCriterion("NUMERO_CLIENTE not in", values, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTEBetween(String value1, String value2) {
            addCriterion("NUMERO_CLIENTE between", value1, value2, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andNUMERO_CLIENTENotBetween(String value1, String value2) {
            addCriterion("NUMERO_CLIENTE not between", value1, value2, "NUMERO_CLIENTE");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURAIsNull() {
            addCriterion("FECHA_ULTIMA_FACTURA is null");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURAIsNotNull() {
            addCriterion("FECHA_ULTIMA_FACTURA is not null");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURAEqualTo(Date value) {
            addCriterion("FECHA_ULTIMA_FACTURA =", value, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURANotEqualTo(Date value) {
            addCriterion("FECHA_ULTIMA_FACTURA <>", value, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURAGreaterThan(Date value) {
            addCriterion("FECHA_ULTIMA_FACTURA >", value, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURAGreaterThanOrEqualTo(Date value) {
            addCriterion("FECHA_ULTIMA_FACTURA >=", value, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURALessThan(Date value) {
            addCriterion("FECHA_ULTIMA_FACTURA <", value, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURALessThanOrEqualTo(Date value) {
            addCriterion("FECHA_ULTIMA_FACTURA <=", value, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURAIn(List<Date> values) {
            addCriterion("FECHA_ULTIMA_FACTURA in", values, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURANotIn(List<Date> values) {
            addCriterion("FECHA_ULTIMA_FACTURA not in", values, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURABetween(Date value1, Date value2) {
            addCriterion("FECHA_ULTIMA_FACTURA between", value1, value2, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andFECHA_ULTIMA_FACTURANotBetween(Date value1, Date value2) {
            addCriterion("FECHA_ULTIMA_FACTURA not between", value1, value2, "FECHA_ULTIMA_FACTURA");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSIsNull() {
            addCriterion("CONTRATO_EBS is null");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSIsNotNull() {
            addCriterion("CONTRATO_EBS is not null");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSEqualTo(String value) {
            addCriterion("CONTRATO_EBS =", value, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSNotEqualTo(String value) {
            addCriterion("CONTRATO_EBS <>", value, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSGreaterThan(String value) {
            addCriterion("CONTRATO_EBS >", value, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRATO_EBS >=", value, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSLessThan(String value) {
            addCriterion("CONTRATO_EBS <", value, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSLessThanOrEqualTo(String value) {
            addCriterion("CONTRATO_EBS <=", value, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSLike(String value) {
            addCriterion("CONTRATO_EBS like", value, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSNotLike(String value) {
            addCriterion("CONTRATO_EBS not like", value, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSIn(List<String> values) {
            addCriterion("CONTRATO_EBS in", values, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSNotIn(List<String> values) {
            addCriterion("CONTRATO_EBS not in", values, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSBetween(String value1, String value2) {
            addCriterion("CONTRATO_EBS between", value1, value2, "CONTRATO_EBS");
            return (Criteria) this;
        }

        public Criteria andCONTRATO_EBSNotBetween(String value1, String value2) {
            addCriterion("CONTRATO_EBS not between", value1, value2, "CONTRATO_EBS");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 23 01:38:48 CDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FACTURADOR.REC_ACCESO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}