package mx.com.ebs.inter.data.model;

import mx.com.ebs.inter.util.Variables;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecFeloggerAgtExample  extends PaginatedResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public RecFeloggerAgtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        private int resultLimitRows = Variables.DEFAULT_SIZE_RESULT;

        public int getResultLimitRows() {
            return resultLimitRows;
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFECHAIsNull() {
            addCriterion("FECHA is null");
            return (Criteria) this;
        }

        public Criteria andFECHAIsNotNull() {
            addCriterion("FECHA is not null");
            return (Criteria) this;
        }

        public Criteria andFECHAEqualTo(Date value) {
            addCriterion("FECHA =", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHANotEqualTo(Date value) {
            addCriterion("FECHA <>", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHAGreaterThan(Date value) {
            addCriterion("FECHA >", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHAGreaterThanOrEqualTo(Date value) {
            addCriterion("FECHA >=", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHALessThan(Date value) {
            addCriterion("FECHA <", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHALessThanOrEqualTo(Date value) {
            addCriterion("FECHA <=", value, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHAIn(List<Date> values) {
            addCriterion("FECHA in", values, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHANotIn(List<Date> values) {
            addCriterion("FECHA not in", values, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHABetween(Date value1, Date value2) {
            addCriterion("trunc(FECHA) between", value1, value2, "FECHA");
            return (Criteria) this;
        }

        public Criteria andFECHANotBetween(Date value1, Date value2) {
            addCriterion("FECHA not between", value1, value2, "FECHA");
            return (Criteria) this;
        }

        public Criteria andCLASEIsNull() {
            addCriterion("CLASE is null");
            return (Criteria) this;
        }

        public Criteria andCLASEIsNotNull() {
            addCriterion("CLASE is not null");
            return (Criteria) this;
        }

        public Criteria andCLASEEqualTo(String value) {
            addCriterion("CLASE =", value, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASENotEqualTo(String value) {
            addCriterion("CLASE <>", value, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASEGreaterThan(String value) {
            addCriterion("CLASE >", value, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASEGreaterThanOrEqualTo(String value) {
            addCriterion("CLASE >=", value, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASELessThan(String value) {
            addCriterion("CLASE <", value, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASELessThanOrEqualTo(String value) {
            addCriterion("CLASE <=", value, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASELike(String value) {
            addCriterion("CLASE like", value, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASENotLike(String value) {
            addCriterion("CLASE not like", value, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASEIn(List<String> values) {
            addCriterion("CLASE in", values, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASENotIn(List<String> values) {
            addCriterion("CLASE not in", values, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASEBetween(String value1, String value2) {
            addCriterion("CLASE between", value1, value2, "CLASE");
            return (Criteria) this;
        }

        public Criteria andCLASENotBetween(String value1, String value2) {
            addCriterion("CLASE not between", value1, value2, "CLASE");
            return (Criteria) this;
        }

        public Criteria andMETODOIsNull() {
            addCriterion("METODO is null");
            return (Criteria) this;
        }

        public Criteria andMETODOIsNotNull() {
            addCriterion("METODO is not null");
            return (Criteria) this;
        }

        public Criteria andMETODOEqualTo(String value) {
            addCriterion("METODO =", value, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODONotEqualTo(String value) {
            addCriterion("METODO <>", value, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODOGreaterThan(String value) {
            addCriterion("METODO >", value, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODOGreaterThanOrEqualTo(String value) {
            addCriterion("METODO >=", value, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODOLessThan(String value) {
            addCriterion("METODO <", value, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODOLessThanOrEqualTo(String value) {
            addCriterion("METODO <=", value, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODOLike(String value) {
            addCriterion("METODO like", value, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODONotLike(String value) {
            addCriterion("METODO not like", value, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODOIn(List<String> values) {
            addCriterion("METODO in", values, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODONotIn(List<String> values) {
            addCriterion("METODO not in", values, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODOBetween(String value1, String value2) {
            addCriterion("METODO between", value1, value2, "METODO");
            return (Criteria) this;
        }

        public Criteria andMETODONotBetween(String value1, String value2) {
            addCriterion("METODO not between", value1, value2, "METODO");
            return (Criteria) this;
        }

        public Criteria andNIVELIsNull() {
            addCriterion("NIVEL is null");
            return (Criteria) this;
        }

        public Criteria andNIVELIsNotNull() {
            addCriterion("NIVEL is not null");
            return (Criteria) this;
        }

        public Criteria andNIVELEqualTo(String value) {
            addCriterion("NIVEL =", value, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELNotEqualTo(String value) {
            addCriterion("NIVEL <>", value, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELGreaterThan(String value) {
            addCriterion("NIVEL >", value, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELGreaterThanOrEqualTo(String value) {
            addCriterion("NIVEL >=", value, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELLessThan(String value) {
            addCriterion("NIVEL <", value, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELLessThanOrEqualTo(String value) {
            addCriterion("NIVEL <=", value, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELLike(String value) {
            addCriterion("NIVEL like", value, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELNotLike(String value) {
            addCriterion("NIVEL not like", value, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELIn(List<String> values) {
            addCriterion("NIVEL in", values, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELNotIn(List<String> values) {
            addCriterion("NIVEL not in", values, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELBetween(String value1, String value2) {
            addCriterion("NIVEL between", value1, value2, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andNIVELNotBetween(String value1, String value2) {
            addCriterion("NIVEL not between", value1, value2, "NIVEL");
            return (Criteria) this;
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andMENSAJEIsNull() {
            addCriterion("MENSAJE is null");
            return (Criteria) this;
        }

        public Criteria andMENSAJEIsNotNull() {
            addCriterion("MENSAJE is not null");
            return (Criteria) this;
        }

        public Criteria andMENSAJEEqualTo(String value) {
            addCriterion("MENSAJE =", value, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJENotEqualTo(String value) {
            addCriterion("MENSAJE <>", value, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJEGreaterThan(String value) {
            addCriterion("MENSAJE >", value, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJEGreaterThanOrEqualTo(String value) {
            addCriterion("MENSAJE >=", value, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJELessThan(String value) {
            addCriterion("MENSAJE <", value, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJELessThanOrEqualTo(String value) {
            addCriterion("MENSAJE <=", value, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJELike(String value) {
            addCriterion("MENSAJE like", value, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJENotLike(String value) {
            addCriterion("MENSAJE not like", value, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJEIn(List<String> values) {
            addCriterion("MENSAJE in", values, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJENotIn(List<String> values) {
            addCriterion("MENSAJE not in", values, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJEBetween(String value1, String value2) {
            addCriterion("MENSAJE between", value1, value2, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andMENSAJENotBetween(String value1, String value2) {
            addCriterion("MENSAJE not between", value1, value2, "MENSAJE");
            return (Criteria) this;
        }

        public Criteria andAGENTEIsNull() {
            addCriterion("AGENTE is null");
            return (Criteria) this;
        }

        public Criteria andAGENTEIsNotNull() {
            addCriterion("AGENTE is not null");
            return (Criteria) this;
        }

        public Criteria andAGENTEEqualTo(String value) {
            addCriterion("AGENTE =", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTENotEqualTo(String value) {
            addCriterion("AGENTE <>", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTEGreaterThan(String value) {
            addCriterion("AGENTE >", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTEGreaterThanOrEqualTo(String value) {
            addCriterion("AGENTE >=", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTELessThan(String value) {
            addCriterion("AGENTE <", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTELessThanOrEqualTo(String value) {
            addCriterion("AGENTE <=", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTELike(String value) {
            addCriterion("AGENTE like", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTENotLike(String value) {
            addCriterion("AGENTE not like", value, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTEIn(List<String> values) {
            addCriterion("AGENTE in", values, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTENotIn(List<String> values) {
            addCriterion("AGENTE not in", values, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTEBetween(String value1, String value2) {
            addCriterion("AGENTE between", value1, value2, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andAGENTENotBetween(String value1, String value2) {
            addCriterion("AGENTE not between", value1, value2, "AGENTE");
            return (Criteria) this;
        }

        public Criteria andANOIsNull() {
            addCriterion("ANO is null");
            return (Criteria) this;
        }

        public Criteria andANOIsNotNull() {
            addCriterion("ANO is not null");
            return (Criteria) this;
        }

        public Criteria andANOEqualTo(String value) {
            addCriterion("ANO =", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANONotEqualTo(String value) {
            addCriterion("ANO <>", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOGreaterThan(String value) {
            addCriterion("ANO >", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOGreaterThanOrEqualTo(String value) {
            addCriterion("ANO >=", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOLessThan(String value) {
            addCriterion("ANO <", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOLessThanOrEqualTo(String value) {
            addCriterion("ANO <=", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOLike(String value) {
            addCriterion("ANO like", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANONotLike(String value) {
            addCriterion("ANO not like", value, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOIn(List<String> values) {
            addCriterion("ANO in", values, "ANO");
            return (Criteria) this;
        }

        public Criteria andANONotIn(List<String> values) {
            addCriterion("ANO not in", values, "ANO");
            return (Criteria) this;
        }

        public Criteria andANOBetween(String value1, String value2) {
            addCriterion("ANO between", value1, value2, "ANO");
            return (Criteria) this;
        }

        public Criteria andANONotBetween(String value1, String value2) {
            addCriterion("ANO not between", value1, value2, "ANO");
            return (Criteria) this;
        }

        public Criteria andMESIsNull() {
            addCriterion("MES is null");
            return (Criteria) this;
        }

        public Criteria andMESIsNotNull() {
            addCriterion("MES is not null");
            return (Criteria) this;
        }

        public Criteria andMESEqualTo(String value) {
            addCriterion("MES =", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESNotEqualTo(String value) {
            addCriterion("MES <>", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESGreaterThan(String value) {
            addCriterion("MES >", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESGreaterThanOrEqualTo(String value) {
            addCriterion("MES >=", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESLessThan(String value) {
            addCriterion("MES <", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESLessThanOrEqualTo(String value) {
            addCriterion("MES <=", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESLike(String value) {
            addCriterion("MES like", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESNotLike(String value) {
            addCriterion("MES not like", value, "MES");
            return (Criteria) this;
        }

        public Criteria andMESIn(List<String> values) {
            addCriterion("MES in", values, "MES");
            return (Criteria) this;
        }

        public Criteria andMESNotIn(List<String> values) {
            addCriterion("MES not in", values, "MES");
            return (Criteria) this;
        }

        public Criteria andMESBetween(String value1, String value2) {
            addCriterion("MES between", value1, value2, "MES");
            return (Criteria) this;
        }

        public Criteria andMESNotBetween(String value1, String value2) {
            addCriterion("MES not between", value1, value2, "MES");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEIsNull() {
            addCriterion("SIT_COMPROBANTE is null");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEIsNotNull() {
            addCriterion("SIT_COMPROBANTE is not null");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEEqualTo(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE =", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTENotEqualTo(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE <>", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEGreaterThan(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE >", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE >=", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTELessThan(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE <", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTELessThanOrEqualTo(BigDecimal value) {
            addCriterion("SIT_COMPROBANTE <=", value, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEIn(List<BigDecimal> values) {
            addCriterion("SIT_COMPROBANTE in", values, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTENotIn(List<BigDecimal> values) {
            addCriterion("SIT_COMPROBANTE not in", values, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTEBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SIT_COMPROBANTE between", value1, value2, "SIT_COMPROBANTE");
            return (Criteria) this;
        }

        public Criteria andSIT_COMPROBANTENotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SIT_COMPROBANTE not between", value1, value2, "SIT_COMPROBANTE");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 24 13:21:56 CDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FACTURADOR.REC_FELOGGER_AGT
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}