package mx.com.ebs.inter.data.model;

import java.math.BigDecimal;
import java.util.Date;

public class RecInvoiceAgt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.FECHA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Date FECHA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_FACTURA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String NUMERO_FACTURA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.SERIE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String SERIE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.FOLIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String FOLIO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.NO_APROBACION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal NO_APROBACION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.APROBACION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal APROBACION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.NO_CERTIFICADO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String NO_CERTIFICADO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Double IMPORTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_IVA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Double IMPORTE_IVA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_TOTAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Double IMPORTE_TOTAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.RFC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String RFC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.RAZON_SOCIAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String RAZON_SOCIAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.CALLE_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String CALLE_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_EXTERIOR_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String NUMERO_EXTERIOR_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_INTERIOR_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String NUMERO_INTERIOR_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.COLONIA_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String COLONIA_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.CIUDAD_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String CIUDAD_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.MUNICIPIO_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String MUNICIPIO_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.ESTADO_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String ESTADO_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.PAIS_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String PAIS_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.CODI_POSTAL_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String CODI_POSTAL_FISCAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.TIPO_DOCUMENTO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String TIPO_DOCUMENTO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.AGENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String AGENTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.ANO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String ANO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.MES
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String MES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.SIT_COMPROBANTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private BigDecimal SIT_COMPROBANTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_CLIENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String NUMERO_CLIENTE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_ISR
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Double IMPORTE_ISR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_RET
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private Double IMPORTE_RET;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.POLIZA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String POLIZA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_INVOICE_AGT.DIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String DIA;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.FECHA
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.FECHA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Date getFECHA() {
        return FECHA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.FECHA
     *
     * @param FECHA the value for FACTURADOR.REC_INVOICE_AGT.FECHA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setFECHA(Date FECHA) {
        this.FECHA = FECHA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_FACTURA
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.NUMERO_FACTURA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getNUMERO_FACTURA() {
        return NUMERO_FACTURA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_FACTURA
     *
     * @param NUMERO_FACTURA the value for FACTURADOR.REC_INVOICE_AGT.NUMERO_FACTURA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setNUMERO_FACTURA(String NUMERO_FACTURA) {
        this.NUMERO_FACTURA = NUMERO_FACTURA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.SERIE
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.SERIE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getSERIE() {
        return SERIE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.SERIE
     *
     * @param SERIE the value for FACTURADOR.REC_INVOICE_AGT.SERIE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setSERIE(String SERIE) {
        this.SERIE = SERIE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.FOLIO
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.FOLIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getFOLIO() {
        return FOLIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.FOLIO
     *
     * @param FOLIO the value for FACTURADOR.REC_INVOICE_AGT.FOLIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setFOLIO(String FOLIO) {
        this.FOLIO = FOLIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.NO_APROBACION
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.NO_APROBACION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getNO_APROBACION() {
        return NO_APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.NO_APROBACION
     *
     * @param NO_APROBACION the value for FACTURADOR.REC_INVOICE_AGT.NO_APROBACION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setNO_APROBACION(BigDecimal NO_APROBACION) {
        this.NO_APROBACION = NO_APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.APROBACION
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.APROBACION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getAPROBACION() {
        return APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.APROBACION
     *
     * @param APROBACION the value for FACTURADOR.REC_INVOICE_AGT.APROBACION
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setAPROBACION(BigDecimal APROBACION) {
        this.APROBACION = APROBACION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.NO_CERTIFICADO
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.NO_CERTIFICADO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getNO_CERTIFICADO() {
        return NO_CERTIFICADO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.NO_CERTIFICADO
     *
     * @param NO_CERTIFICADO the value for FACTURADOR.REC_INVOICE_AGT.NO_CERTIFICADO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setNO_CERTIFICADO(String NO_CERTIFICADO) {
        this.NO_CERTIFICADO = NO_CERTIFICADO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.IMPORTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Double getIMPORTE() {
        return IMPORTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE
     *
     * @param IMPORTE the value for FACTURADOR.REC_INVOICE_AGT.IMPORTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setIMPORTE(Double IMPORTE) {
        this.IMPORTE = IMPORTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_IVA
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.IMPORTE_IVA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Double getIMPORTE_IVA() {
        return IMPORTE_IVA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_IVA
     *
     * @param IMPORTE_IVA the value for FACTURADOR.REC_INVOICE_AGT.IMPORTE_IVA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setIMPORTE_IVA(Double IMPORTE_IVA) {
        this.IMPORTE_IVA = IMPORTE_IVA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_TOTAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.IMPORTE_TOTAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Double getIMPORTE_TOTAL() {
        return IMPORTE_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_TOTAL
     *
     * @param IMPORTE_TOTAL the value for FACTURADOR.REC_INVOICE_AGT.IMPORTE_TOTAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setIMPORTE_TOTAL(Double IMPORTE_TOTAL) {
        this.IMPORTE_TOTAL = IMPORTE_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.RFC
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.RFC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getRFC() {
        return RFC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.RFC
     *
     * @param RFC the value for FACTURADOR.REC_INVOICE_AGT.RFC
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setRFC(String RFC) {
        this.RFC = RFC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.RAZON_SOCIAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.RAZON_SOCIAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getRAZON_SOCIAL() {
        return RAZON_SOCIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.RAZON_SOCIAL
     *
     * @param RAZON_SOCIAL the value for FACTURADOR.REC_INVOICE_AGT.RAZON_SOCIAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setRAZON_SOCIAL(String RAZON_SOCIAL) {
        this.RAZON_SOCIAL = RAZON_SOCIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.CALLE_FISCAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.CALLE_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getCALLE_FISCAL() {
        return CALLE_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.CALLE_FISCAL
     *
     * @param CALLE_FISCAL the value for FACTURADOR.REC_INVOICE_AGT.CALLE_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setCALLE_FISCAL(String CALLE_FISCAL) {
        this.CALLE_FISCAL = CALLE_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_EXTERIOR_FISCAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.NUMERO_EXTERIOR_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getNUMERO_EXTERIOR_FISCAL() {
        return NUMERO_EXTERIOR_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_EXTERIOR_FISCAL
     *
     * @param NUMERO_EXTERIOR_FISCAL the value for FACTURADOR.REC_INVOICE_AGT.NUMERO_EXTERIOR_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setNUMERO_EXTERIOR_FISCAL(String NUMERO_EXTERIOR_FISCAL) {
        this.NUMERO_EXTERIOR_FISCAL = NUMERO_EXTERIOR_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_INTERIOR_FISCAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.NUMERO_INTERIOR_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getNUMERO_INTERIOR_FISCAL() {
        return NUMERO_INTERIOR_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_INTERIOR_FISCAL
     *
     * @param NUMERO_INTERIOR_FISCAL the value for FACTURADOR.REC_INVOICE_AGT.NUMERO_INTERIOR_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setNUMERO_INTERIOR_FISCAL(String NUMERO_INTERIOR_FISCAL) {
        this.NUMERO_INTERIOR_FISCAL = NUMERO_INTERIOR_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.COLONIA_FISCAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.COLONIA_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getCOLONIA_FISCAL() {
        return COLONIA_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.COLONIA_FISCAL
     *
     * @param COLONIA_FISCAL the value for FACTURADOR.REC_INVOICE_AGT.COLONIA_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setCOLONIA_FISCAL(String COLONIA_FISCAL) {
        this.COLONIA_FISCAL = COLONIA_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.CIUDAD_FISCAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.CIUDAD_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getCIUDAD_FISCAL() {
        return CIUDAD_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.CIUDAD_FISCAL
     *
     * @param CIUDAD_FISCAL the value for FACTURADOR.REC_INVOICE_AGT.CIUDAD_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setCIUDAD_FISCAL(String CIUDAD_FISCAL) {
        this.CIUDAD_FISCAL = CIUDAD_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.MUNICIPIO_FISCAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.MUNICIPIO_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getMUNICIPIO_FISCAL() {
        return MUNICIPIO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.MUNICIPIO_FISCAL
     *
     * @param MUNICIPIO_FISCAL the value for FACTURADOR.REC_INVOICE_AGT.MUNICIPIO_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setMUNICIPIO_FISCAL(String MUNICIPIO_FISCAL) {
        this.MUNICIPIO_FISCAL = MUNICIPIO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.ESTADO_FISCAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.ESTADO_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getESTADO_FISCAL() {
        return ESTADO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.ESTADO_FISCAL
     *
     * @param ESTADO_FISCAL the value for FACTURADOR.REC_INVOICE_AGT.ESTADO_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setESTADO_FISCAL(String ESTADO_FISCAL) {
        this.ESTADO_FISCAL = ESTADO_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.PAIS_FISCAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.PAIS_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getPAIS_FISCAL() {
        return PAIS_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.PAIS_FISCAL
     *
     * @param PAIS_FISCAL the value for FACTURADOR.REC_INVOICE_AGT.PAIS_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setPAIS_FISCAL(String PAIS_FISCAL) {
        this.PAIS_FISCAL = PAIS_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.CODI_POSTAL_FISCAL
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.CODI_POSTAL_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getCODI_POSTAL_FISCAL() {
        return CODI_POSTAL_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.CODI_POSTAL_FISCAL
     *
     * @param CODI_POSTAL_FISCAL the value for FACTURADOR.REC_INVOICE_AGT.CODI_POSTAL_FISCAL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setCODI_POSTAL_FISCAL(String CODI_POSTAL_FISCAL) {
        this.CODI_POSTAL_FISCAL = CODI_POSTAL_FISCAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.TIPO_DOCUMENTO
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.TIPO_DOCUMENTO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getTIPO_DOCUMENTO() {
        return TIPO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.TIPO_DOCUMENTO
     *
     * @param TIPO_DOCUMENTO the value for FACTURADOR.REC_INVOICE_AGT.TIPO_DOCUMENTO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setTIPO_DOCUMENTO(String TIPO_DOCUMENTO) {
        this.TIPO_DOCUMENTO = TIPO_DOCUMENTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.AGENTE
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.AGENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getAGENTE() {
        return AGENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.AGENTE
     *
     * @param AGENTE the value for FACTURADOR.REC_INVOICE_AGT.AGENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setAGENTE(String AGENTE) {
        this.AGENTE = AGENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.ANO
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.ANO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getANO() {
        return ANO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.ANO
     *
     * @param ANO the value for FACTURADOR.REC_INVOICE_AGT.ANO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setANO(String ANO) {
        this.ANO = ANO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.MES
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.MES
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getMES() {
        return MES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.MES
     *
     * @param MES the value for FACTURADOR.REC_INVOICE_AGT.MES
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setMES(String MES) {
        this.MES = MES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.SIT_COMPROBANTE
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.SIT_COMPROBANTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public BigDecimal getSIT_COMPROBANTE() {
        return SIT_COMPROBANTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.SIT_COMPROBANTE
     *
     * @param SIT_COMPROBANTE the value for FACTURADOR.REC_INVOICE_AGT.SIT_COMPROBANTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setSIT_COMPROBANTE(BigDecimal SIT_COMPROBANTE) {
        this.SIT_COMPROBANTE = SIT_COMPROBANTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_CLIENTE
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.NUMERO_CLIENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getNUMERO_CLIENTE() {
        return NUMERO_CLIENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.NUMERO_CLIENTE
     *
     * @param NUMERO_CLIENTE the value for FACTURADOR.REC_INVOICE_AGT.NUMERO_CLIENTE
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setNUMERO_CLIENTE(String NUMERO_CLIENTE) {
        this.NUMERO_CLIENTE = NUMERO_CLIENTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_ISR
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.IMPORTE_ISR
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Double getIMPORTE_ISR() {
        return IMPORTE_ISR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_ISR
     *
     * @param IMPORTE_ISR the value for FACTURADOR.REC_INVOICE_AGT.IMPORTE_ISR
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setIMPORTE_ISR(Double IMPORTE_ISR) {
        this.IMPORTE_ISR = IMPORTE_ISR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_RET
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.IMPORTE_RET
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public Double getIMPORTE_RET() {
        return IMPORTE_RET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.IMPORTE_RET
     *
     * @param IMPORTE_RET the value for FACTURADOR.REC_INVOICE_AGT.IMPORTE_RET
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setIMPORTE_RET(Double IMPORTE_RET) {
        this.IMPORTE_RET = IMPORTE_RET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.POLIZA
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.POLIZA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getPOLIZA() {
        return POLIZA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.POLIZA
     *
     * @param POLIZA the value for FACTURADOR.REC_INVOICE_AGT.POLIZA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setPOLIZA(String POLIZA) {
        this.POLIZA = POLIZA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_INVOICE_AGT.DIA
     *
     * @return the value of FACTURADOR.REC_INVOICE_AGT.DIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getDIA() {
        return DIA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_INVOICE_AGT.DIA
     *
     * @param DIA the value for FACTURADOR.REC_INVOICE_AGT.DIA
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setDIA(String DIA) {
        this.DIA = DIA;
    }
}