package mx.com.ebs.inter.data.model;

public class RecPerfiles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_PERFILES.PERFIL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String PERFIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTURADOR.REC_PERFILES.NUMERO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    private String NUMERO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_PERFILES.PERFIL
     *
     * @return the value of FACTURADOR.REC_PERFILES.PERFIL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getPERFIL() {
        return PERFIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_PERFILES.PERFIL
     *
     * @param PERFIL the value for FACTURADOR.REC_PERFILES.PERFIL
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setPERFIL(String PERFIL) {
        this.PERFIL = PERFIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTURADOR.REC_PERFILES.NUMERO
     *
     * @return the value of FACTURADOR.REC_PERFILES.NUMERO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public String getNUMERO() {
        return NUMERO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTURADOR.REC_PERFILES.NUMERO
     *
     * @param NUMERO the value for FACTURADOR.REC_PERFILES.NUMERO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    public void setNUMERO(String NUMERO) {
        this.NUMERO = NUMERO;
    }
}