package mx.com.ebs.inter.data.dao.proc;

import java.util.List;
import mx.com.ebs.inter.data.model.proc.AgtFelEnvio;
import mx.com.ebs.inter.data.model.proc.AgtFelEnvioExample;
import mx.com.ebs.inter.data.model.proc.AgtFelEnvioKey;
import org.apache.ibatis.annotations.Param;

public interface AgtFelEnvioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int countByExample(AgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int deleteByExample(AgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int deleteByPrimaryKey(AgtFelEnvioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int insert(AgtFelEnvio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int insertSelective(AgtFelEnvio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    List<AgtFelEnvio> selectByExample(AgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    AgtFelEnvio selectByPrimaryKey(AgtFelEnvioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int updateByExampleSelective(@Param("record") AgtFelEnvio record, @Param("example") AgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int updateByExample(@Param("record") AgtFelEnvio record, @Param("example") AgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int updateByPrimaryKeySelective(AgtFelEnvio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int updateByPrimaryKey(AgtFelEnvio record);
}