package mx.com.ebs.inter.data.dao.proc;

import java.util.List;
import mx.com.ebs.inter.data.model.ProcRecInvoice;
import mx.com.ebs.inter.data.model.ProcRecInvoiceExample;
import org.apache.ibatis.annotations.Param;

public interface ProcRecInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int countByExample(ProcRecInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int deleteByExample(ProcRecInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int insert(ProcRecInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int insertSelective(ProcRecInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    List<ProcRecInvoice> selectByExample(ProcRecInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int updateByExampleSelective(@Param("record") ProcRecInvoice record, @Param("example") ProcRecInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.REC_INVOICE
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int updateByExample(@Param("record") ProcRecInvoice record, @Param("example") ProcRecInvoiceExample example);
}