package mx.com.ebs.inter.data.dao.proc;

import java.util.List;
import mx.com.ebs.inter.data.model.ProcAgtFelEnvio;
import mx.com.ebs.inter.data.model.ProcAgtFelEnvioExample;
import mx.com.ebs.inter.data.model.ProcAgtFelEnvioKey;
import org.apache.ibatis.annotations.Param;

public interface ProcAgtFelEnvioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int countByExample(ProcAgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int deleteByExample(ProcAgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int deleteByPrimaryKey(ProcAgtFelEnvioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int insert(ProcAgtFelEnvio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int insertSelective(ProcAgtFelEnvio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    List<ProcAgtFelEnvio> selectByExample(ProcAgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    ProcAgtFelEnvio selectByPrimaryKey(ProcAgtFelEnvioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int updateByExampleSelective(@Param("record") ProcAgtFelEnvio record, @Param("example") ProcAgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int updateByExample(@Param("record") ProcAgtFelEnvio record, @Param("example") ProcAgtFelEnvioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int updateByPrimaryKeySelective(ProcAgtFelEnvio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTES.AGT_FEL_ENVIO
     *
     * @mbggenerated Fri Apr 24 13:21:56 CDT 2015
     */
    int updateByPrimaryKey(ProcAgtFelEnvio record);
}