package mx.com.ebs.inter.data.dao;

import java.util.List;
import mx.com.ebs.inter.data.model.RecInvoiceAgt;
import mx.com.ebs.inter.data.model.RecInvoiceAgtExample;
import org.apache.ibatis.annotations.Param;

public interface RecInvoiceAgtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_INVOICE_AGT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int countByExample(RecInvoiceAgtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_INVOICE_AGT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int deleteByExample(RecInvoiceAgtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_INVOICE_AGT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int insert(RecInvoiceAgt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_INVOICE_AGT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int insertSelective(RecInvoiceAgt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_INVOICE_AGT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    List<RecInvoiceAgt> selectByExample(RecInvoiceAgtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_INVOICE_AGT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int updateByExampleSelective(@Param("record") RecInvoiceAgt record, @Param("example") RecInvoiceAgtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FACTURADOR.REC_INVOICE_AGT
     *
     * @mbggenerated Thu Apr 23 01:38:48 CDT 2015
     */
    int updateByExample(@Param("record") RecInvoiceAgt record, @Param("example") RecInvoiceAgtExample example);
}